<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
  <data name="$this.Icon" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        AAABAAIAICAAAAEACACoCAAAJgAAACAgAAABACAAqBAAAM4IAAAoAAAAIAAAAEAAAAABAAgAAAAAAAAA
        AAAAAAAAAAAAAAABAAAAAAAAAjZqAAJOggCCkpIAAqbaAFa+2gDOtpodYnaCHQZ6qgACxvYA4sbGAB6G
        rgD+5sYAzmYCAGbe7h0izvYdApLGAMbq9gCG1uYALqrSAPLq6gCuakIAsuryHQKCth0CZpoAArbqAOb+
        /gBC4v4Azq6yACLW/gCG9vodfur6HRrG8gCybj4AVtbuAC5WegAajroAMt7+AJb2+h0CWo4dFqbSAP72
        5gACiroAAkJ2APq+hgDagioABq7eHRJ6ph3u2toAIpa+ABKeygDmlkoAAnKmAAK+8gD69vYdcvL+HVLi
        +gAGzv4AKrriAP7SpgAq2v4ADlqKAAKOwh3uxpod7qpmAP7+9gB68v4AWuL6AAKCsgD+7tYAYu7+HQKa
        yh06rs4A9u7uALL2/gCK+v4AEtL+AJ72/gAKirodEkZyHTKaugCuno4A6tbWAC7G6gACbqIADrbmAErm
        /h3CdjodOt7+AAJilgD++u4AAo6+AAJKfgDejjoADq7aHf7Gkh3+8t4Aau7+AL7+/gAa1v4AAj5yAAJW
        igACqtodQtLuHQJ+rgACyv4A5s7OANZ2GgDK/v4AmuryAC6y1h3+8uYdAoa2AM7GrgAi2v4Ahvr+AJL+
        /gACXo4AAoq+HQZGdh3KejoA5uLmAOqiWgAScp4AAsLyAP769gB29v4dUur+HQ7S/gD+1q4AXo6aAK6y
        ogDytnYARlZqAB664h1WyuId3r6+ADKCogDexp4AmtbqAL6ulgAu0vYALqLKHRKGsh3Sbg4A8uLiABZi
        jgDW/v4A5p5SAKr+/gD+zpodHprGHVrq/gA2yu4ACrLiAPa6fgC6cj4Amv7+AC6awh0Kbp4d/v7+AAqC
        sgCy/v4A5srKABaizgA2stIA+vLyHc5+Nh0COm4AAlKGAAJ6rgAClsoAKq7SAAJqngACuu4dgvb+HfrC
        igACruIAAnaqAC7e/gB69v4AAprOAMZ6Oh3+ypYd/vbiAG7y/gACRnoA/tqyAALG+gD26uoARuL+HTbe
        /h3+9uoABoq6AHby/gAKzv4ALtr+AP7++gD+7todZu7+HY76/gAW0v4ADrrmAE7m/gA64v4A/vryAB7W
        /h0Cqt4dAoa6ACba/gCW/v4AAl6SAALC9gD++voAVur+HV7q/h1+9v4ABprOAAAAAAAAAAAAAAAAAAAA
        AAAAAAAdAAAAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0AAAAdAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAHQAAAB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdAAAAHQAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAB0AAAAdAAAAAP9GDw89WinPFkNnqbEzU1OsFxdYWNJkZAFbW7kqY6f/sbC0isQZ
        GZJrYZScnHNK18G4xtY3VRq+wxxiyNi5ZwCprUInBBkeV71VfkKX1taX1X5VvVckO83IYg4HWK0Dp2et
        xkU5EhBJl37WRcZgYMZF1n7KvVeyO75SnsDCOANjQ61gxkVmMYqSHkW4NsF9NrjG1n5VGldVq55dS3/C
        A2MWrbhgxkU3owSSTLPXrtfXQTbGQn7VQjAHH2LIS3/OKhY0NrhgxkXWOY0QYUpKx0rXs7jGNg0uMRwc
        zWLIS84qFjTBNrhgxkXWZjERkpQlx0rXQUqGB4U7HA4czWLILbkWNH3BNrhgxkXWN6MEa6GcSsclR02M
        JMM70BwczWItuc80s33BNrhgxkXW1m2NFWGhbDAnV1e+JMM70BwczS1bz9PXs0HBNrhgxtY3I3qWEREj
        kY5XV1e+JMM70A4cmQF1CK7Xs33BNrjGIS6BPolPT4k+BjyYV1e+JMM70ByZAVq7Ha7Xs319YASxApWV
        toCAlba2AiqrV1ckJMM70JmoPQhKcq7X12CNeou2toBfzFlEgLa2i04KGle+JMM7mag9u8dKctcNMIg+
        lbpuxHx8zFm/RICVPiI8mFe+JMOZZA9oc8cdhqCBlYBun5+fxHx8zFm/KEQ6tgYqq76+JFQmD7tzHaSO
        gjpEn5+fn5+fxEB8zFm/KCgLOlBOLiQkVCaqaB4xnXBEn5+fn5+fn5+fxEB8zFm/KChfCwUiPJhUJqoY
        D4F4n5+fn5+fn5+fn5+fxEB8zFm/KCi3XxuEYynSRqoPMhOfn5+fn5+fn5+fn5+fxHx8zFm/KCi3hxQA
        ACr/RqqTvJ+fn5+fn5+fn5+fn5+fxEB8zFm/KG6HIGOn////RnlIn5+fn5+fn5+fn5+fn5/ExHx8zFm/
        KIcgKv//////eUifn5+fn5+fn5+fn5+fn5+fxHx8zFm/hyD///////8/SJ+fn5+fn5+fn5+fn5+fn5+f
        xHx8zFkJm////////z+ln5+fn5+fn5+fn5+fn5+fn5+fxEB8zAmb////////gzWfn5+fn5+fn5+fn5+f
        n5+fn5+fxEB8CVb///////+DNZ+fn5+fn5+fn5+fn5+fn5+fn5+fQHyiVv///////5rUn5+fn5+fn5+f
        n5+fn5+fn5+fn5+fxKK1////////K9Sfn5+fn5+fn5+fn5+fn5+fn5+fn5/Eonf///////+vn5+fn5+f
        n5+fn5+fn5+fn5+fn5+fn59ppv///////16fn9TUNaWlSEi8vBMTE5AvLy8vUVFRaWmm////////tl6v
        K5qDgz8/eXmTMjJcXFwsLGpqao8MDAz///+AAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAHAAAAD4AAAB+AA
        AAfgAAAH4AAAB+AAAAfgAAAH4AAAB+AAAAfgAAAH4AAABygAAAAgAAAAQAAAAAEAIAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAjL98AJjL/wCVyP8AksX/AI/C/wCMv/8Aibz/AIe6/wCEt/8AgbT/AH2w/wB6
        rf8Ad6r/AHWo/wBypf8Ab6H/AGue/wBpnP8AZpn/AGWY/wBgk/8AXZD/AFqN/wBViP8AUIP/AE2A/wBK
        ff8ARXj/AEJ1/wA+cf8AOm3/ADZpfAB4q/8AreD/AJrN/5/X6v/8////7v///+D////S////yf///7v/
        //+t////n////5n///+R/f//ivr//4D3//918///bvH//2Xu//9b6///Uuf//0vk//9A4f//Nd7//y7c
        //8k2P//G9X//xLS//8Fmsz/AEh7/wB9sP8AN2r/AHqt/wC67f9X4vn/EqjV/2C93f/g9vv/fOr//zvg
        //9F4///S+X//1Lo//9X6f//Wur//17r//9d6///Wur//1bp//9S6P//TOX//0Xj//874P//M93//yna
        //8e1v//FdP//xnV//8iz/f/CoCw/wFjlf8Dve7/AKfa/wA6bf8AfK//ALvu/2fv//9j7f//Krzi/zCp
        0v/M6vT/sPX//1jo//9V6f//Xuv//2Ls//9m7v//aO///2jv//9m7v//Yuz//13r//9U6P//Tub//0Xj
        //874P//Ltz//yjZ//8z3f//LMXq/wlunv8Gibn/Cs///wfO//8BqNv/AD1w/wB+sf8AvfD/au///2fv
        //9j7f//QdHu/xagzv+c1un/0vv//3vv//9l7v//bvH//3Py//929P//dvT//3Pz//9u8f//Zu7//17r
        //9U6P//TOX//0Pi//884P//SuX//y6y1v8GbJ7/Dq3b/xLS//8O0f//Cs///wKq3P8AP3L/AICz/wC+
        8f9u8P//au///2fv//9j7f//U+D4/xGl0v9du9v/1/f7/5z3//969f//ffb//4H3//+B9///ffb//3r1
        //9w8f//Zu7//1vq//9S6P//Vuj//1zl+f8imL//Bnqr/xnH8f8Z1P//FdP//xLS//8O0f//A6vd/wBB
        dP8AgbT/AL/y/3Ly//9u8P//au///2fv//9j7f//X+v//yi74P8tp9D/wOr0/738//+O+v//jfv//4z6
        //+K+v//gPf//3r1//9u8f//Ze3//3Dy//9g2u3/FYSw/xGax/8j2P//INf//x3W//8Z1P//FdP//xLS
        //8ErN3/AEN2/wCDtv8AwPP/dfP//3Ly//9u8P//au///2fv//9j7f//X+v//z/Q7v8Vnsz/k9Xo/9P/
        //+m////mf///5D8//+K+v//ffb//3r1//+K+v//Vsje/wuBsP8fueL/Ktr//ybZ//8j2P//INf//x3W
        //8Z1P//FdP//wWt3v8ARXj/AIW4/wDB9P938///dfP//3Ly//9u8P//au///2fv//9j7f//X+v//1Dg
        +P8Ros//WLnZ/834+/+z////mf///4v6//+S+v//lPb6/zqszP8Li7r/LtH0/zHc//8t2///Ktr//ybZ
        //8j2P//INf//x3W//8Z1P//Bq7f/wBHev8Ah7r/AML1/3v1//938///dfP//3Ly//9u8P//au///2fv
        //9j7f//X+v//1zr//8nuN3/LKTN/7Pp8/+/////sv3//5jo8f8gmcL/HKnT/zvg//843///Nd7//zHc
        //8t2///Ktr//ybZ//8j2P//INf//x3W//8Hr+D/AEp9/wCIu/8Aw/b/f/f//3v1//938///dfP//3Ly
        //9u8P//au///2fv//9j7f//WeL4/yORuP8Wcpz/GpfC/4rU5/+E0+b/GZC8/xZijf8dhq//P+H//zvg
        //843///Nd7//zHc//8t2///Ktr//ybZ//8j2P//INf//wiw4f8ATYD/AIq9/wDE9/+C9///f/f//3v1
        //938///dfP//3Ly//9u8P//au///1TV7P8Te6f/UICT/+/FmP/fxJ7/MJq5/zCYuP/fw53/78SX/1Bt
        gP8NXYz/N83t/zvg//843///Nd7//zHc//8t2///Ktr//ybZ//8j2P//CLHh/wBPgv8AjL//AMX4/4b4
        //+C9///f/f//3v1//938///dfP//3Ly//9Fvdr/B2+f/4CZmf//zJn//8yZ///Mmf//167//9eu///M
        mf//zJn//8yZ/4CHh/8ESHr/K63S/zvg//843///Nd7//zHc//8t2///Ktr//ybZ//8JsuL/AFGE/wCO
        wf8Axvn/ivr//4b4//+C9///f/f//3v1//9w6/n/LKHE/xBxnv+/s5r//8yZ///Mmf//2LH///De///6
        8v//+O7//+zX///Xrf//zJn//8yZ/7+pkP8QR3T/HISu/zvg//843///Nd7//zHc//8t2///Ktr//wqz
        4/8AU4b/AI/C/wDH+v+N+///ivr//4b4//+C9///Z9/v/xeNuP8wg6P/78aa///Mmf//2bP///Ll///9
        +////Pf///v1///68v//+O7///fr///s1f//1qz//8yZ/+/Dl/8wWXn/DFmI/zTL7f843///Nd7//zHc
        //8t2///C7Xk/wBViP8AkcT/AMj7/5D8//+N+///ivr//1TK4f8IgrL/cJyj///Mmf//1qz///Lm////
        ///////////+///9+////Pf///v1///68v//+O7///fr///26P//69L//9Sn///Mmf9wfIP/BER2/yis
        0f843///Nd7//zHc//8MteT/AFiL/wCTxv8Ayfz/lP3//4f1+/81sdL/EIay/6+zoP//0qb//+zZ////
        ///////////////////////////+///9+////Pf///v1///68v//+O7///fr///26P//9eX//+XH///R
        ov+vn4z/EENw/xqCrf843///Nd7//w235v8AWo3/AJXI/wDK/f976fP/HJ/J/y6Zwv/Pxaz//+zZ////
        ///////////////////////////////////////////+///9+////Pf///v1///68v//+O7///fr///2
        6P//9eX///Ti///kxf/Ptpr/KVF7/wtYh/8xyez/Drjn/wBcj/8Alsn/ALbp/wKTxf9Vj5H/5OHk////
        ///////////////////////////////////////////////////////////+///9+////Pf///v1///6
        8v//+O7///fr///26P//9eX///Ti///z3//Nr7P/R1Vr/wE/cv8Cibr/AF+S/wCYy/8Alcj/AJLF/+WY
        S//z6en////////////////////////////////////////////////////////////////////+///9
        +////Pf///v1///68v//+O7///fr///26P//9eX///Ti/9y5uf+saUD/ADpt/wA3av8AQnX/AJnMnwCY
        y/8Alcj/55xS//Xr6///////////////////////////////////////////////////////////////
        ///////////+///9+////Pf///v1///68v//+O7///fr///26P//9eX/3bu7/7BrPv8APnH/ADpt/wA2
        aY8AAAAAAJnMYACYy+/poVj/9u3t////////////////////////////////////////////////////
        ///////////////////////////+///9+////Pf///v1///68v//+O7///fr///26P/evb3/sm0+/wBC
        de8APnFQAAAAAAAAAAAAAAAAAJnMMOukXf/37+//////////////////////////////////////////
        ///////////////////////////////////////////+///9+////Pf///v1///68v//+O7///fr/9+/
        v/+1bj3/AER3IAAAAAAAAAAAAAAAAAAAAAAAAAAA7ahk//jw8P//////////////////////////////
        ///////////////////////////////////////////////////////////+///9+////Pf///v1///6
        8v//+O7/4MHB/7lwPP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvrWr/+fLy////////////////////
        ///////////////////////////////////////////////////////////////////////////+///9
        +////Pf///v1///68v/hxMT/vHM7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPKycv/69PT/////////
        ////////////////////////////////////////////////////////////////////////////////
        ///////////+///9+////Pf///v1/+LGxv/AdTr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9LV3//v3
        9///////////////////////////////////////////////////////////////////////////////
        ///////////////////////////+///9+////Pf/48jI/8J2Ov8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAD2un3//Pn5////////////////////////////////////////////////////////////////////
        ///////////////////////////////////////////+///9+//kysr/xXg4/wAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAPi+hP/9+/v/////////////////////////////////////////////////////////
        ///////////////////////////////////////////////////////////+/+XMzP/Iejj/AAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAA+sKK//79/f//////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////5s3N/8t8
        N/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8xpH///////79/f/9+/v//Pn5//v39//69PT/+fLy//jw
        8P/37+//9u3t//Xr6//z6en/8+fn//Lk5P/w4uL/7+Dg/+/e3v/u3Nz/7Nra/+zY2P/r1tb/6dTU/+jR
        0f/oz8//z342/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7Ll//8xpH/+sKK//i+hP/2un3/9LV3//Ky
        cv/vrWr/7ahk/+ukXf/poVj/55xS/+WYS//jlEX/4ZA+/9+LOP/diDP/2oMr/9h+Jf/Weh7/1HcZ/9Jy
        E//Qbgz/zmoG/8xmAP/LZQH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAcAA
        AAPgAAAH4AAAB+AAAAfgAAAH4AAAB+AAAAfgAAAH4AAAB+AAAAc=
</value>
  </data>
</root>