<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
  <data name="$this.Icon" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        AAABAAIAICAAAAEACACoCAAAJgAAACAgAAABACAAqBAAAM4IAAAoAAAAIAAAAEAAAAABAAgAAAAAAAAA
        AAAAAAAAAAAAAAABAAAAAAAAAgKaAGaG/gAmQtIAAhrOAGJiwgASIrodIkruHQIq6gACEroAMlruAD5i
        6gDOrs4AYm7iAAoSqh0KLuIdEjbqACZK7gBGcvoABjb2AAIKqgB+lv4ALl7+Hf7e3h0yMq4AMlLiABJC
        /gAaMs4AOmb2AAYKogACIt4dAhbCHT5i9gAOGrIAIkr6AAoiygDO0u4AJlL+AE5y/h0OOvodHkLeAAYi
        0gACLvYAWnb6AAIGogByiv4AChKuHTJS7h2Knv4AOlr2AE5q9gAWIrYADh62AA4y5gACNv4dGkr+HRo6
        2gBGbvYAJkrmAAIGngBujv4AUlbWAAIu8h3+zs4dEi7eABI69gAqUvIARnb+AAIOsgDu8voAGkb+HTZm
        /h0GHsoAHk7+AM7W+gBKev4AIkLmAAIi2gBafv4dZor+HQIe1gAKLuoAQmryAM663gBibu4AEhKmAB4+
        7h1Ccv4dBg6qAIaa/gAyYv4AIjbGADpa5gAWRv4AIjrOHQYOph0GGsoAQmb+ABIesgAeLsIADj7+ACZG
        3gAKJtYdAjL+HVp6/gASFq4Ajqb+ADZi+gAaKr4AEh6+AAY6/h1ibt4d/vb2ADpq/gACAp4Aaob+ACpG
        2gAGHs4ADiK+HQIq7h0GFr4AOl7qAD5m7gDOrtIAYnLiAA4WqgAOMt4dEjbuHSZO7gAGNvoAMj7KAHqW
        /gAGKuYAPmr+AP7+/h02Xv4dRmb2AC5W/gAyTvYAUl7WAB4+3gAmPtIAgpr+HTZW4h0GGsIAHkr+AA4m
        ygBKdv4ACjr+ACJC4gACMvodVnb+HQ4WrgAWJroAEh66ABIy4gACCq4AMl7+ABZC/h0SGrIdztLyAAYi
        1gACBqYABjb+AAYGngAqUvYAOmb+HSJO/h3O1v4ATnr+AEZy/gAKDqYAkqb+AAAAAAAAAAAdAAAAHQAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0AAAAdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHQAA
        AB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdAAAAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AB0AAAAdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHQAAAB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAdAAAAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0AAAAdAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAHQAAAB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdAAAAHQAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAB0AAAAdAAAAAP///////////////0ObmxMToSsr////////////////////////
        ////CI+PVSGQNlwZJlATEwD/////////////////////HiIQiEVjNWZmZmY1NW1tg5sA////////////
        /////19Lhp2VDpEzl3wNqld3TJU1NU8A//////////////90MIg1fWuYMmEgl3wNqhwcKwNmNQcr////
        ////////KB9IEhpidQWYMmEgl3wNqhw6ABM9NQcr/////////6CHJBJdWo+KgQWYMmEgl3xeVBcAACsH
        NQcr//////9MLmAmjF1HboVEgQWYMmEgDWgjhQQAACs9NU8A/////5pnXGQCKAyFhYVEgQWYMiAgI4WF
        hQQAABNmNZv///8dMZwGc2UMhYWFhYVEgQUzMyOFhYWFhQQAAAM1gwD//zQBSBiLPD5vhYWFhYVEgWyf
        hYWFhYWFhRc6K5VtE///NCVBGGQ/Cz5vhYWFhYVEn4WFhYWFhYUjVBwcTG0T/wcqhAmOGCc/Cz5vhYWF
        hYWFhYWFhYWFI2heqhx3NVArBywVeFuOGCc/Cz5vhYWFhYWFhYWFhSMgDXwNqlc1Jit2FBUKeFuOGCc/
        Cz5vhYWFhYWFhYWfMyAgl3wNqmYZoXYUWXkKeFuOGCc/em+FhYWFhYWFn2wzMmEgl3wNlRkTPVhGUXkK
        eFuOlJpJhYWFhYWFhYVEgQWYMmEgl3yVRRM9L3BRUXkKeDkPSYWFhYWFhYWFhYVEgQWYMmEgl2aQmymN
        VjhRUXl/fkmFhYWFhYWFhYWFhYVEgQWYMmEzNSGbKXJNEThRQUBJhYWFhYWFhW9vhYWFhYVEgQWYMpFj
        VUP/GTtWERtAUoWFhYWFhYVJej5vhYWFhYVEgQWYDkWP//8ZaUJCaok+FoWFhYWFSZo/Cz5vhYWFhYWK
        dWuViI///2YsTpKSY1M+FoWFhUkPlCc/Cz5vhYWFbo9ifZ0QCP///5CrqEoRY1M+FoVJfjmOGCc/Cz5v
        hQxHWho1hiL/////ZpaNSkoRY1M+UkB/eFuOGCc/Cz4MKF1dEohLHv//////k4I7SkoRY4lAQXkKeFuO
        GCc/PGUCAhJIMF//////////k4I7SkqSahtRUXkKeFuOGGQ3c2QmJB90////////////k4KNqJJCEThR
        UXkKeFuOGBgGXGCHKP//////////////k5arTkJWEThRUXkKeAlBSJxnLqD/////////////////ZpAs
        aTtNVnBGWRUVhCUBMZpM/////////////////////2YZGXKNL4KCFCwqNDQd////////////////////
        ////////KSk9PXZ2Bwf/////////////////8A///4AB//4AAH/8AAA/+AAAH/AAAA/gAAAHwAAAA8AA
        AAOAAAABgAAAAYAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAGAAAABgAAAAcAA
        AAPAAAAD4AAAB/AAAA/4AAAf/AAAP/4AAH//gAH///AP/ygAAAAgAAAAQAAAAAEAIAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA62MAAN
        tIAADbK/AAuv/wAKrf8ACar/AAio/wAGpv8ABaT/AAWivwADn4AAAp0wAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABK9YAAR
        us8GGcH/Ei3W/xw/7P8gSfr/Hkv//xpI//8WRf//E0L//w47+f8ILuj/BBzL/wEKqv8AApzPAAKcYAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABbEIAAU
        wb8LIcv/J0nu/y1W//8ZR///DT3//wI1//8AM///ADP//wAz//8AM///ATT//wQ3//8GOP//CDn//wQq
        5/8AC6//AAGbvwAAmSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY
        yTAEG8rwI0Ll/zdf//8VQ///ATL7/wgt4/8NJsv/Dx21/w4Xrf8NFav/CxGo/wkOpf8GDaj/BBa+/wEi
        2v8AMPn/AjX//wQ2//8BHdT/AAGa7wAAmVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAGswwBR7O8Dlb9f8uV///BDb//w4w3/8YKr//FyW4/xUitf8TH7P/EBuw/w4Xrf8NFav/CxGo/wkO
        pf8HCqL/BQig/wIHo/8AGsz/ADP//wM1//8AKuz/AASg/wAAmWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAABzRMAUh0vA/YPb/IEz//wQ0+P8aM8//HC7B/w8hvv8TI7v/FyW4/xUitf8TH7P/EBuw/w4X
        rf8NFav/CxGo/wkOpf8GCaH/BAae/wIEnP8ACqz/AC3y/wE0//8AKuz/AASg/wAAmVAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAe1iAGI9fwRGT2/yVR//8HNfX/ITnN/yA0x/8GG8P/UF3U/zA/yf8QILv/FyW4/xUi
        tf8TH7P/EBuw/w4Xrf8NFav/Bwym/xATpv8wMa//AQKa/wIEnP8ABKD/ACns/wE0//8AKuz/AASh8AAA
        mSAAAAAAAAAAAAAAAAAAAAAAACDYvzNS7f9AZv//DDv5/yU/0v8jOsz/Bx7J/2Bu3P//////7/D7/zA/
        yf8QILv/FyW4/xUitf8TH7P/EBuw/wkRrP8QFqz/z9Du//////9gYcH/AQKa/wIEnP8ABKD/AC3y/wM1
        //8BHdT/AAGbvwAAAAAAAAAAAAAAAAAh3GATM+L/W3v//xRF//8mRd3/JkHS/wcj0P9gcOD/////////
        ////////7/D7/zA/yf8QILv/FyW4/xUitf8MGLL/EBmy/8/R7/////////////////9gYcH/AQKa/wIE
        nP8ACqz/ADP//wQ2//8AC6//AAKcUAAAAAAAAAAAACPfz01r9v8zXv//Iknt/ytH2P8IJtb/YG/h////
        ////////////////////////7/D7/zA/yf8QILv/Dhy3/xAcuP/P0fD/////////////////////////
        //9gYcH/AQKa/wIEnP8AGsz/AjX//wQq5/8AApzPAAAAAAAl4jAOMeX/ZoT//x1N/f8wUOD/Hj3c/1BW
        1f//z8////X1////////////////////////////7/D7/zA/yf8QH73/z9Lx////////////////////
        //////////////////8wMa//BAae/wIHo/8AMPn/CDn//wEKqv8AAp0wACblgDJS7/9Ncv//KFP0/zRU
        4P8lRd7/EC3c/8+sz///z8////X1////////////////////////////7/D7/8/T8///////////////
        ////////////////////////z9Du/xATpv8GCaH/BQig/wEi2v8GOP//BBzL/wADn4AAKOi/WHX4/z5o
        //8yWe7/Nlfj/zRU4P8fQN7/EC3c/8+sz///z8////X1////////////////////////////////////
        /////////////////////////////8/R7/8QFqz/Bwym/wkOpf8HCqL/BBa+/wQ3//8ILuj/AAWivwAp
        6/9xi/7/L17//zle6f85W+b/Nlfj/zRU4P8fQN7/EC3c/8+sz///z8////X1////////////////////
        ///////////////////////////////////P0fD/EBmy/wkRrP8NFav/CxGo/wkOpf8GDaj/ATT//w47
        +f8ABaT/ACnt/32W//8uXv//PWLr/zte6P85W+b/Nlfj/zRU4P8fQN7/EC3c/8+sz///z8////X1////
        ////////////////////////////////////////z9Lx/xAcuP8MGLL/EBuw/w4Xrf8NFav/CxGo/wkO
        pf8AM///E0L//wAGpv8AK+//gJj//zJi//8/Ze7/PWLr/zte6P85W+b/Nlfj/zRU4P8fQN7/EC3c/8+v
        0v//9fX//////////////////////////////////////8/T8/8QH73/Dhy3/xUitf8TH7P/EBuw/w4X
        rf8NFav/CxGo/wEx+f8UQ///AAio/wAt8f+Em///NmX//0Bo8f8/Ze7/PWLr/zte6P85W+b/Nlfj/yBC
        4f8QMuP/z9b5////////////////////////////////////////////7/D7/zA/yf8QILv/FyW4/xUi
        tf8TH7P/EBuw/w4Xrf8NFav/ATH6/xhH//8ACar/AC3z/4ie//86af//Qmvz/0Bo8f8/Ze7/PWLr/zte
        6P8kSOf/EDTp/8/W+v//////////////////////////////////////////////////////7/D7/zA/
        yf8QILv/FyW4/xUitf8TH7P/EBuw/w4Xrf8AM///Hkv//wAKrf8ALvX/gpn+/0Nw//9Eb/f/Qmvz/0Bo
        8f8/Ze7/Jk7t/xA37v/P1/v/////////////////////////////////////////////////////////
        ////////7/D7/zA/yf8QILv/FyW4/xUitf8TH7P/Dx21/wI1//8gSfr/AAuv/wAw+L9qhvz/WH///0Rx
        +/9Eb/b/Qmvz/yhT8/8QOvX/z9f8////////////////////////////////////////9fX///X1////
        ////////////////////////7/D7/zA/yf8QILv/FyW4/xUitf8NJsv/DT3//xw/7P8ADbK/ADD6gEBk
        +/9vj///RHL+/0dz+v87Z/f/EDv3/8+43f//////////////////////////////////////z9b5/8+v
        0v//z8////X1////////////////////////////7/D7/zA/yf8TI7v/FyW4/wgt4/8ZR///Ei3W/wAN
        tIAAMfwwEkD8/46k//9GdP//SHX8/zVj+/8wT/X//8zM///f3////////////////////////////8/W
        +v8QMuP/EC3c/8+sz///z8////X1////////////////////////////UF3U/w8hvv8YKr//ATL7/y1W
        //8GGcH/AA62MAAAAAAAMfzPcIv+/2WJ//9Jd///SXX8/w0//v9gbOz//8zM///f3///////////////
        ///P1/v/EDTp/yBC4f8fQN7/EC3c/8+sz///z8////X1/////////////////2Bu3P8GG8P/HC7B/w4w
        3/8VQ///J0nu/wARus8AAAAAAAAAAAAz/2AdSP3/kqf//097//9KeP//RHH8/w0//v9gbOz//8zM///f
        3///////z9f8/xA37v8kSOf/Nlfj/zRU4P8fQN7/EC3c/8+sz///z8////X1//////9gcOD/Bx7J/yA0
        x/8aM8//BDb//zdf//8LIcv/ABK9YAAAAAAAAAAAAAAAAAAz/79Vdf7/gJv//0t5//9Lef//RHH8/w0/
        /v9gbOz//8zM/8+43f8QOvX/Jk7t/zte6P85W+b/Nlfj/zRU4P8fQN7/EC3c/8+sz///z8//YG/h/wcj
        0P8jOsz/ITnN/wQ0+P8uV///I0Ll/wAUwb8AAAAAAAAAAAAAAAAAAAAAADP/IAo7//B7lP//bY///0t5
        //9Lef//RHH8/w0//v8wT/X/EDv3/yhT8/8/Ze7/PWLr/zte6P85W+b/Nlfj/zRU4P8fQN7/EC3c/1BW
        1f8IJtb/JkHS/yVA0v8HNfX/IEz//zlb9f8EG8rwABbEIAAAAAAAAAAAAAAAAAAAAAAAAAAAADP/UAo7
        //97lP//bY///0t5//9KeP//SXX8/zVj+/87Z/f/Qmvz/0Bo8f8/Ze7/PWLr/zte6P85W+b/Nlfj/zRU
        4P8lRd7/Gzrb/ytH2P8mRd3/DDv5/yVR//8/YPb/BB7N/wAYyVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAADP/YAo7//97lP//gJv//097//9Jd///SHX8/0dz+v9Eb/b/Qmvz/0Bo8f8/Ze7/PWLr/zte
        6P85W+b/Nlfj/zRU4P8wUOD/Iknt/xRF//9AZv//RGT2/wUh0v8AGsxgAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAADP/UAo7//BVdf7/kqf//2WJ//9GdP//RHL+/0Rx+/9Eb/f/Qmvz/0Bo
        8f8/Ze7/PWLr/zle6f8yWe7/KFP0/x1N/f8zXv//W3v//zNS7f8GI9fwABzRUAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADP/IAAz/78dSP3/cIv+/46k//9vj///WH///0Nw
        //86af//OGb+/zNi/v8uXv//L17//z5o//9Ncv//ZoT//01r9v8TM+L/ACDYvwAe1iAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAz/2AAMfzPEkD8/0Bk
        +/9qhvz/gpn+/4ie//97lf//e5X//32W//9xi/7/WHX4/zJS7/8OMeX/ACPfzwAh3GAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAMfwwADD6gAAw+L8ALvX/AC3z/wAt8f8AK+//ACnt/wAp6/8AKOi/ACblgAAl4jAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AD//8AAP/8AAA/+AAAH/AAAA/gAAAHwAAAA8AA
        AAOAAAABgAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAA
        AAGAAAABwAAAA8AAAAPgAAAH8AAAD/gAAB/8AAA//wAA///AA/8=
</value>
  </data>
</root>