<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="&gt;&gt;ucBotDenkprotokoll.Type" xml:space="preserve">
    <value>GaitoBotEditorCore.controls.ucBotDenkprotokoll, GaitoBotEditorCore, Version=2.0.3814.38206, Culture=neutral, PublicKeyToken=null</value>
  </data>
  <data name="&gt;&gt;ucBotDenkprotokoll.Name" xml:space="preserve">
    <value>ucBotDenkprotokoll</value>
  </data>
  <data name="&gt;&gt;webBrowserBotAusgabe.Name" xml:space="preserve">
    <value>webBrowserBotAusgabe</value>
  </data>
  <data name="&gt;&gt;webBrowserBotAusgabe.Type" xml:space="preserve">
    <value>System.Windows.Forms.WebBrowser, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <assembly alias="System.Windows.Forms" name="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="buttonAbsenden.Anchor" type="System.Windows.Forms.AnchorStyles, System.Windows.Forms">
    <value>Bottom, Left</value>
  </data>
  <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
  <data name="$this.Size" type="System.Drawing.Size, System.Drawing">
    <value>794, 313</value>
  </data>
  <data name="webBrowserBotAusgabe.Size" type="System.Drawing.Size, System.Drawing">
    <value>343, 250</value>
  </data>
  <data name="toolStrip.Location" type="System.Drawing.Point, System.Drawing">
    <value>0, 0</value>
  </data>
  <data name="textBoxBenutzerEingabe.Location" type="System.Drawing.Point, System.Drawing">
    <value>12, 287</value>
  </data>
  <data name="toolStripButtonWissenNeuLaden.ToolTipText" xml:space="preserve">
    <value>Begrüßung</value>
  </data>
  <data name="&gt;&gt;webBrowserBotAusgabe.ZOrder" xml:space="preserve">
    <value>4</value>
  </data>
  <data name="&gt;&gt;webBrowserBotAusgabe.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="ucBotDenkprotokoll.Size" type="System.Drawing.Size, System.Drawing">
    <value>430, 283</value>
  </data>
  <data name="toolStrip.Size" type="System.Drawing.Size, System.Drawing">
    <value>794, 25</value>
  </data>
  <data name="toolStrip.Text" xml:space="preserve">
    <value>toolStrip1</value>
  </data>
  <data name="toolStripButtonLadeProtokollZeigen.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="&gt;&gt;ucBotDenkprotokoll.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="&gt;&gt;toolStripSeparator1.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripSeparator, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripSeparator1.Name" xml:space="preserve">
    <value>toolStripSeparator1</value>
  </data>
  <data name="&gt;&gt;buttonAbsenden.ZOrder" xml:space="preserve">
    <value>3</value>
  </data>
  <data name="&gt;&gt;buttonAbsenden.Name" xml:space="preserve">
    <value>buttonAbsenden</value>
  </data>
  <data name="&gt;&gt;buttonAbsenden.Type" xml:space="preserve">
    <value>System.Windows.Forms.Button, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="toolStripButtonZeigeStart.Image" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAO
        wgAADsIBFShKgAAAAgNJREFUOE+lkutLk2EYxvePhJaHShFBUTEPiCieQOmDiEZgrEbpYGiCQxkqA80I
        RUkUEZ0YRMS+DDI70MkTmzJnDc8iU8QT2mAEItnle90wHwTDyBduXnie5/rd133Q4ZKfAJqHFs9E08A8
        zD1emDpmYXjqRlnTFIrMk8iuGkNaxWekGEaQrHecBfw+/vPXODw6hj9whN2fh/Bt/8LSRgA3cxr/DeBZ
        9kvmTNMoHGNbIrYN+3Aj23IxgJkpds0doP3VstgmsNexhutZ9QrAms8T0zYzU5xXM46kcjsmvfvoeL2i
        AeoUgA07T8yaaZuZKab1rzN74jgys1YB2O2gmBZzH49LODXrrJlnzEzxe9cOLH1ziMioVgCOiuIFX0CE
        Q+/WYf+yieiCFrRp9tkwxnP7Kt5MbKGm6wfC000KwDlTXNLgEvHMkh+Db32o7fYivtQm1l9+3IBOp5P7
        yjYPwlKNCsAluWudxgvtknb5t9oWcL/VLU2Mvd2JFq3uqs7vAtE/ceNayiMF4KiYMSjmY2O7B4Ua+NaD
        YQGEJumRbvyG1IcfBHI12aAAXM8R57aIWTNrLLY4tfNPiCvpR1SeVeu6WWzHFD6THSDwFMDdpmUG62NJ
        PKM4Or9ZxBxb8H8l7g5CEu8pAOfM3WanSeeS8CFHxW4zM2umbWamOCShXAH+/wNOANABIDUxWnDPAAAA
        AElFTkSuQmCC
</value>
  </data>
  <data name="&gt;&gt;ucBotDenkprotokoll.ZOrder" xml:space="preserve">
    <value>1</value>
  </data>
  <data name="buttonAbsenden.Location" type="System.Drawing.Point, System.Drawing">
    <value>243, 285</value>
  </data>
  <assembly alias="mscorlib" name="mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="textBoxBenutzerEingabe.TabIndex" type="System.Int32, mscorlib">
    <value>1</value>
  </data>
  <data name="toolStripProgressBarWissenLaden.Size" type="System.Drawing.Size, System.Drawing">
    <value>100, 22</value>
  </data>
  <data name="&gt;&gt;toolStrip.ZOrder" xml:space="preserve">
    <value>2</value>
  </data>
  <data name="&gt;&gt;buttonAbsenden.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="&gt;&gt;toolStripLabelWissenWirdGeladen.Name" xml:space="preserve">
    <value>toolStripLabelWissenWirdGeladen</value>
  </data>
  <data name="&gt;&gt;toolStripLabelWissenWirdGeladen.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripLabel, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStrip.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="textBoxBenutzerEingabe.Anchor" type="System.Windows.Forms.AnchorStyles, System.Windows.Forms">
    <value>Bottom, Left</value>
  </data>
  <data name="ucBotDenkprotokoll.Location" type="System.Drawing.Point, System.Drawing">
    <value>361, 27</value>
  </data>
  <data name="toolStripButtonZeigeStart.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="toolStripButtonWissenNeuLaden.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="&gt;&gt;toolStripProgressBarWissenLaden.Name" xml:space="preserve">
    <value>toolStripProgressBarWissenLaden</value>
  </data>
  <data name="&gt;&gt;toolStripProgressBarWissenLaden.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripProgressBar, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="toolStripLabelWissenWirdGeladen.Text" xml:space="preserve">
    <value>Begrüßung</value>
  </data>
  <data name="toolStripLabelWissenWirdGeladen.Size" type="System.Drawing.Size, System.Drawing">
    <value>66, 22</value>
  </data>
  <data name="toolStripButtonLadeProtokollZeigen.Text" xml:space="preserve">
    <value>toolStripButtonWissenNeuLaden</value>
  </data>
  <data name="toolStripButtonLadeProtokollZeigen.Size" type="System.Drawing.Size, System.Drawing">
    <value>199, 22</value>
  </data>
  <data name="&gt;&gt;toolStripButtonLadeProtokollZeigen.Name" xml:space="preserve">
    <value>toolStripButtonLadeProtokollZeigen</value>
  </data>
  <data name="&gt;&gt;toolStripButtonLadeProtokollZeigen.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="webBrowserBotAusgabe.Location" type="System.Drawing.Point, System.Drawing">
    <value>12, 28</value>
  </data>
  <data name="ucBotDenkprotokoll.TabIndex" type="System.Int32, mscorlib">
    <value>5</value>
  </data>
  <data name="toolStripSeparator1.Size" type="System.Drawing.Size, System.Drawing">
    <value>6, 25</value>
  </data>
  <data name="toolStripSeparatorBitteWarten.Size" type="System.Drawing.Size, System.Drawing">
    <value>6, 25</value>
  </data>
  <data name="&gt;&gt;$this.Name" xml:space="preserve">
    <value>ucBotTest</value>
  </data>
  <data name="&gt;&gt;$this.Type" xml:space="preserve">
    <value>System.Windows.Forms.UserControl, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripButtonWissenNeuLaden.Name" xml:space="preserve">
    <value>toolStripButtonWissenNeuLaden</value>
  </data>
  <data name="&gt;&gt;toolStripButtonWissenNeuLaden.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;textBoxBenutzerEingabe.Name" xml:space="preserve">
    <value>textBoxBenutzerEingabe</value>
  </data>
  <data name="&gt;&gt;textBoxBenutzerEingabe.Type" xml:space="preserve">
    <value>System.Windows.Forms.TextBox, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="toolStrip.TabIndex" type="System.Int32, mscorlib">
    <value>4</value>
  </data>
  <data name="&gt;&gt;textBoxBenutzerEingabe.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="toolStripButtonZeigeStart.Text" xml:space="preserve">
    <value>Begrüßung</value>
  </data>
  <data name="toolStripButtonZeigeStart.Size" type="System.Drawing.Size, System.Drawing">
    <value>70, 22</value>
  </data>
  <data name="&gt;&gt;toolStripButtonZeigeStart.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripButtonZeigeStart.Name" xml:space="preserve">
    <value>toolStripButtonZeigeStart</value>
  </data>
  <data name="webBrowserBotAusgabe.TabIndex" type="System.Int32, mscorlib">
    <value>2</value>
  </data>
  <data name="toolStripButtonWissenNeuLaden.Text" xml:space="preserve">
    <value>Begrüßung</value>
  </data>
  <data name="toolStripButtonWissenNeuLaden.Size" type="System.Drawing.Size, System.Drawing">
    <value>86, 22</value>
  </data>
  <data name="&gt;&gt;textBoxBenutzerEingabe.ZOrder" xml:space="preserve">
    <value>0</value>
  </data>
  <data name="buttonAbsenden.TabIndex" type="System.Int32, mscorlib">
    <value>3</value>
  </data>
  <data name="textBoxBenutzerEingabe.Size" type="System.Drawing.Size, System.Drawing">
    <value>225, 20</value>
  </data>
  <data name="buttonAbsenden.Text" xml:space="preserve">
    <value>buttonAbsenden</value>
  </data>
  <data name="buttonAbsenden.Size" type="System.Drawing.Size, System.Drawing">
    <value>112, 23</value>
  </data>
  <data name="$this.AutoScaleDimensions" type="System.Drawing.SizeF, System.Drawing">
    <value>6, 13</value>
  </data>
  <data name="&gt;&gt;toolStrip.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStrip, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStrip.Name" xml:space="preserve">
    <value>toolStrip</value>
  </data>
  <data name="&gt;&gt;toolStripSeparatorBitteWarten.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripSeparator, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripSeparatorBitteWarten.Name" xml:space="preserve">
    <value>toolStripSeparatorBitteWarten</value>
  </data>
</root>