<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
  <data name="labelDenkprotokoll.Location" type="System.Drawing.Point, System.Drawing">
    <value>14, 13</value>
  </data>
  <data name="listViewSchritte.Location" type="System.Drawing.Point, System.Drawing">
    <value>17, 29</value>
  </data>
  <data name="&gt;&gt;listViewSchritte.Name" xml:space="preserve">
    <value>listViewSchritte</value>
  </data>
  <data name="&gt;&gt;listViewSchritte.Type" xml:space="preserve">
    <value>System.Windows.Forms.ListView, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="$this.Size" type="System.Drawing.Size, System.Drawing">
    <value>450, 259</value>
  </data>
  <data name="listViewSchritte.Size" type="System.Drawing.Size, System.Drawing">
    <value>417, 214</value>
  </data>
  <data name="&gt;&gt;labelDenkprotokoll.Type" xml:space="preserve">
    <value>System.Windows.Forms.Label, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;labelDenkprotokoll.Name" xml:space="preserve">
    <value>labelDenkprotokoll</value>
  </data>
  <data name="labelDenkprotokoll.Size" type="System.Drawing.Size, System.Drawing">
    <value>95, 13</value>
  </data>
  <data name="labelDenkprotokoll.Text" xml:space="preserve">
    <value>labelDenkprotokoll</value>
  </data>
  <data name="&gt;&gt;imageListDenkprotokoll.Type" xml:space="preserve">
    <value>System.Windows.Forms.ImageList, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;imageListDenkprotokoll.Name" xml:space="preserve">
    <value>imageListDenkprotokoll</value>
  </data>
  <data name="imageListDenkprotokoll.ImageStream" mimetype="application/x-microsoft.net.object.binary.base64">
    <value>
        AAEAAAD/////AQAAAAAAAAAMAgAAAFdTeXN0ZW0uV2luZG93cy5Gb3JtcywgVmVyc2lvbj00LjAuMC4w
        LCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkFAQAAACZTeXN0
        ZW0uV2luZG93cy5Gb3Jtcy5JbWFnZUxpc3RTdHJlYW1lcgEAAAAERGF0YQcCAgAAAAkDAAAADwMAAAAk
        CAAAAk1TRnQBSQFMAgEBBAEAAQwBAAEEAQABEAEAARABAAT/AREBEAj/AUIBTQE2BwABNgMAASgDAAFA
        AwABIAMAAQEBAAEQBgABEP8A/wD/AP8A/wD/AP8A/wAcAAEQAUIBEAFCARABQgEQAUIBEAFCARABQgEQ
        AUIBEAFCARABQgEQAUIBEAFCARABQgEQAUIBEAFCOAABEAFCRAABEAFCARABQi4AARABQgIAAf8BfwIA
        ARABQhoAARgBYwEYAWMBGAFjARgBYwYAAeABfwHgAX8B4AF/AeABfwHgAX8B4AF/AeABfwHgAX8B4AF/
        AeABfwHgAX8B4AF/AeABfwEYAWMCAAEQAUIOAAEYAWMBEAFCGAABEAFCBAAB/wF/Af8BfwIAARABQhwA
        ARgBYwEYAWMCAAEQAUIBEAFCAgAB4AF/AeABfwHgAX8B4AF/AeABfwHgAX8BGAFjAgABGAFjAeABfwHg
        AX8B4AF/AeABfwEYAWMCAAEQAUIOAAEYAWMBEAFCGgABGAFjAf8BfwH/AX8B/wF/AgABEAFCARABQigA
        AeABfwHgAX8B4AF/AeABfwHgAX8BGAFjAgABGAFjAeABfwHgAX8B4AF/AeABfwIAARABQhAAARgBYwEQ
        AUIWAAEYAWMB/wF/Af8BfwH/AX8B/wF/Af8BfwQAARABQgEQAUIMAAH/AX8MAAEYAWMBGAFjCAAB4AF/
        AeABfwHgAX8B4AF/AeABfwHgAX8BGAFjAeABfwHgAX8B4AF/AeABfwEYAWMCAAEQAUIQAAEQAUIB4AF/
        EgABEAFCARgBYwH/AX8B/wF/Af8BfwH/AX8B/wF/Af8BfwH/AX8BGAFjAgABEAFCARABQgoAAf8BfxoA
        AeABfwHgAX8B4AF/AeABfwHgAX8CAAHgAX8B4AF/AeABfwHgAX8CAAEQAUISAAEQAUIB4AF/EAABEAFC
        Af8BfwH/AX8B/wF/Af8BfwH/AX8B/wF/Af8BfwH/AX8B/wF/Af8BfwH/AX8CAAEQAUIKAAH/AX8KAAH/
        AX8EAAH/AX8IAAHgAX8B4AF/AeABfwHgAX8BGAFjAgABGAFjAeABfwHgAX8BGAFjAgABEAFCEAAB/wF/
        ARABQgHgAX8B4AF/DgABEAFCAf8BfwH/AX8B/wF/Af8BfwEfAQABHwEAAR8BAAEfAQAB/wF/Af8BfwH/
        AX8CAAEQAUIBEAFCCAAB/wF/CAAB/wF/Af8BfwEQAUIB/wF/DAAB4AF/AeABfwHgAX8GAAHgAX8B4AF/
        AgABEAFCEgAB/wF/ARABQgEQAUIB4AF/DAABEAFCAf8BfwH/AX8B/wF/Af8BfwH/AX8B/wF/AR8BAAEf
        AQAB/wF/Af8BfwH/AX8B/wF/Af8BfwIAARABQggAAf8BfwH/AX8EAAH/AX8B/wF/ARABQgH/AX8OAAHg
        AX8B4AF/AeABfwYAAeABfwEYAWMCAAEQAUIQAAH/AX8BEAFCAeABfwHgAX8BEAFCAeABfwoAARABQgH/
        AX8B/wF/Af8BfwH/AX8B/wF/Af8BfwEfAQABHwEAAf8BfwH/AX8B/wF/Af8BfwH/AX8CAAEQAUIGAAH/
        AX8B/wF/Af8BfwH/AX8B/wF/Af8BfwEQAUIB/wF/EgAB4AF/AeABfwYAAeABfwIAARABQhIAAf8BfwH/
        AX8B4AF/AeABfwHgAX8B4AF/CgABEAFCAf8BfwH/AX8B/wF/Af8BfwH/AX8BHwEAAR8BAAEfAQAB/wF/
        Af8BfwH/AX8B/wF/Af8BfwIAARABQgYAAf8BfwH/AX8B/wF/Af8BfwH/AX8B/wF/Af8BfxQAAeABfwHg
        AX8BGAFjAgABGAFjARgBYwIAARABQhQAAf8BfwH/AX8B4AF/AeABfwwAARABQgH/AX8B/wF/Af8BfwH/
        AX8B/wF/Af8BfwH/AX8B/wF/Af8BfwH/AX8B/wF/Af8BfwH/AX8KAAH/AX8B/wF/Af8BfwH/AX8B/wF/
        Af8BfxgAAeABfwHgAX8B4AF/AeABfwIAARABQhgAAf8BfwHgAX8QAAEQAUIB/wF/Af8BfwH/AX8B/wF/
        Af8BfwEfAQABHwEAAf8BfwH/AX8B/wF/Af8Bfw4AAf8BfwH/AX8B/wF/Af8BfxoAAeABfwHgAX8B4AF/
        ARgBYwIAARABQiwAARABQgEYAWMB/wF/Af8BfwH/AX8B/wF/ARgBYwEYAWMB/wF/Af8BfwH/AX8B/wF/
        CQABfAEAAXwmAAHgAX8B4AF/AgABEAFCMAABEAFCARABQgEYAWMB/wF/Af8BfwH/AX8B/wF/Af8BfwH/
        AX8BEAFCARABQgkAAUABAAFAAQABfAEAAXwBAAF8JAABEAFCNgABEAFCARABQgEQAUIBEAFCARABQgEQ
        AUIBEAFCKgABQgFNAT4HAAE+AwABKAMAAUADAAEgAwABAQEAAQEGAAEBFgAD/4EAAYABAQP/AY8B/wED
        AgAB/gF/Af4BDwH/AQECAAH8AT8B+AEPAf8BgAIAAfwBPwHwAQcB8wGBAYABAQHcATsB4AEDAeMBwQGA
        AQEB7AE3AcABAQHjAYMBwAEDAfgBHwGAAQEB4wGJAcABAwH4AR8BgAEAAeMBAwHgAQcB8AEPAgAB4AEH
        AeABBwGQAQkCAAHAAQ8B8AEPAfABDwIAAcABHwHwAQ8B8AEPAQABAQGAAT8B+AEfAfgBHwGAAQMBAAF/
        AfgBHwHsATcBgAEDAQAB/wH8AT8B3wH7AcABBwEAAf8B/AF/Av8B8AEfAYEB/xYACw==
</value>
  </data>
  <assembly alias="mscorlib" name="mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="labelDenkprotokoll.AutoSize" type="System.Boolean, mscorlib">
    <value>True</value>
  </data>
  <data name="&gt;&gt;labelDenkprotokoll.ZOrder" xml:space="preserve">
    <value>0</value>
  </data>
  <data name="&gt;&gt;$this.Name" xml:space="preserve">
    <value>ucBotDenkprotokoll</value>
  </data>
  <data name="&gt;&gt;$this.Type" xml:space="preserve">
    <value>System.Windows.Forms.UserControl, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="listViewSchritte.TabIndex" type="System.Int32, mscorlib">
    <value>0</value>
  </data>
  <data name="&gt;&gt;labelDenkprotokoll.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="labelDenkprotokoll.TabIndex" type="System.Int32, mscorlib">
    <value>1</value>
  </data>
  <data name="&gt;&gt;listViewSchritte.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="$this.AutoScaleDimensions" type="System.Drawing.SizeF, System.Drawing">
    <value>6, 13</value>
  </data>
  <data name="&gt;&gt;listViewSchritte.ZOrder" xml:space="preserve">
    <value>1</value>
  </data>
</root>