<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="_8" xml:space="preserve">
    <value>delete category</value>
  </data>
  <data name="_9" xml:space="preserve">
    <value>sort</value>
  </data>
  <data name="_2" xml:space="preserve">
    <value>new fitting THAT</value>
  </data>
  <data name="_3" xml:space="preserve">
    <value>new fitting SRAI</value>
  </data>
  <data name="_1" xml:space="preserve">
    <value>toolStrip</value>
  </data>
  <data name="_6" xml:space="preserve">
    <value>clone</value>
  </data>
  <data name="_7" xml:space="preserve">
    <value>add new category</value>
  </data>
  <data name="_4" xml:space="preserve">
    <value>clone THAT</value>
  </data>
  <data name="_5" xml:space="preserve">
    <value>clone TEMPLATE</value>
  </data>
  <data name="_91" xml:space="preserve">
    <value>toolStripButtonWissenNeuLaden</value>
  </data>
  <data name="_90" xml:space="preserve">
    <value>Zusätzliche Inhalte auswählen</value>
  </data>
  <data name="_82" xml:space="preserve">
    <value>WebDokumentAdresse</value>
  </data>
  <data name="_83" xml:space="preserve">
    <value>Export</value>
  </data>
  <data name="_80" xml:space="preserve">
    <value>keineGaitobotID</value>
  </data>
  <data name="_81" xml:space="preserve">
    <value>WebGoAdresse</value>
  </data>
  <data name="_86" xml:space="preserve">
    <value>checkBox1</value>
  </data>
  <data name="_87" xml:space="preserve">
    <value>label1</value>
  </data>
  <data name="_84" xml:space="preserve">
    <value>ExportErfolgreich</value>
  </data>
  <data name="_85" xml:space="preserve">
    <value>openFileDialog</value>
  </data>
  <data name="_88" xml:space="preserve">
    <value>Fertig</value>
  </data>
  <data name="_89" xml:space="preserve">
    <value>Bitte wählen Sie die das Wissen und die Bausteine aus, welche zusätzlich in den Arbeitsbereich integriert werden sollen:</value>
  </data>
  <data name="_39" xml:space="preserve">
    <value>search</value>
  </data>
  <data name="_38" xml:space="preserve">
    <value>Test</value>
  </data>
  <data name="_31" xml:space="preserve">
    <value>search in actual topic</value>
  </data>
  <data name="_30" xml:space="preserve">
    <value>search in actual aiml-file</value>
  </data>
  <data name="_33" xml:space="preserve">
    <value>save all</value>
  </data>
  <data name="_32" xml:space="preserve">
    <value>search in workspace</value>
  </data>
  <data name="_35" xml:space="preserve">
    <value>export</value>
  </data>
  <data name="_34" xml:space="preserve">
    <value>publish</value>
  </data>
  <data name="_37" xml:space="preserve">
    <value>Automatische Tests</value>
  </data>
  <data name="_36" xml:space="preserve">
    <value>Manueller Test</value>
  </data>
  <data name="_28" xml:space="preserve">
    <value>checkBoxAlleStarTagsInEineDatei</value>
  </data>
  <data name="_29" xml:space="preserve">
    <value>toolStrip1</value>
  </data>
  <data name="_20" xml:space="preserve">
    <value>toolStripButtonSave</value>
  </data>
  <data name="_21" xml:space="preserve">
    <value>open file</value>
  </data>
  <data name="_22" xml:space="preserve">
    <value>new file</value>
  </data>
  <data name="_23" xml:space="preserve">
    <value>rename</value>
  </data>
  <data name="_24" xml:space="preserve">
    <value>buttonDurchsuchen</value>
  </data>
  <data name="_25" xml:space="preserve">
    <value>labelExportVerzeichnis</value>
  </data>
  <data name="_26" xml:space="preserve">
    <value>buttonExportStarten</value>
  </data>
  <data name="_27" xml:space="preserve">
    <value>checkBoxVorExportVerzeichnisLeeren</value>
  </data>
  <data name="_19" xml:space="preserve">
    <value>toolStripButton1</value>
  </data>
  <data name="_18" xml:space="preserve">
    <value>delete</value>
  </data>
  <data name="_13" xml:space="preserve">
    <value>Thema 3</value>
  </data>
  <data name="_12" xml:space="preserve">
    <value>Thema 2</value>
  </data>
  <data name="_11" xml:space="preserve">
    <value>Thema</value>
  </data>
  <data name="_10" xml:space="preserve">
    <value>miniToolStrip</value>
  </data>
  <data name="_17" xml:space="preserve">
    <value>new topic</value>
  </data>
  <data name="_16" xml:space="preserve">
    <value>Thema 6</value>
  </data>
  <data name="_15" xml:space="preserve">
    <value>Thema 5</value>
  </data>
  <data name="_14" xml:space="preserve">
    <value>Thema 4</value>
  </data>
  <data name="_79" xml:space="preserve">
    <value>new startup file</value>
  </data>
  <data name="_78" xml:space="preserve">
    <value>new aiml file</value>
  </data>
  <data name="_75" xml:space="preserve">
    <value />
  </data>
  <data name="_74" xml:space="preserve">
    <value>Begrüßung</value>
  </data>
  <data name="_77" xml:space="preserve">
    <value>http://www.gaitobot.de/gaitobot/EditorDocuments/news_de.aspx</value>
  </data>
  <data name="_76" xml:space="preserve">
    <value>toolStripLabelWissenWirdGeladen</value>
  </data>
  <data name="_71" xml:space="preserve">
    <value>Die Datei '{0}' konnte nicht gelöscht werden: {1}</value>
  </data>
  <data name="_70" xml:space="preserve">
    <value>Das Verzeichnis '{0}' konnte nicht gelöscht werden: {1}</value>
  </data>
  <data name="_73" xml:space="preserve">
    <value>Begrüßung</value>
  </data>
  <data name="_72" xml:space="preserve">
    <value>Begrüßung</value>
  </data>
  <data name="_68" xml:space="preserve">
    <value>Root-Topic can´t be deleted!</value>
  </data>
  <data name="_69" xml:space="preserve">
    <value>Wahrscheinlich wird das Programm gerade während des Ladens geschlossen?</value>
  </data>
  <data name="_64" xml:space="preserve">
    <value>Root-Topic kann nicht gelöscht werden!</value>
  </data>
  <data name="_65" xml:space="preserve">
    <value>Dieser Arbeitsbereich wurde bereits geöffnet!</value>
  </data>
  <data name="_66" xml:space="preserve">
    <value>Unbehandelte Wissensprache '{0}' für BotEigenschaften-Standardwerte</value>
  </data>
  <data name="_67" xml:space="preserve">
    <value>Diesem ExportSteuerelement wurde bereits ein Arbeitsbereich zugeordnet</value>
  </data>
  <data name="_60" xml:space="preserve">
    <value>Inhalt</value>
  </data>
  <data name="_61" xml:space="preserve">
    <value>Neue Eigenschaft hinzufügen</value>
  </data>
  <data name="_62" xml:space="preserve">
    <value>Eigenschaften mit Beispielwerten füllen</value>
  </data>
  <data name="_63" xml:space="preserve">
    <value>Eigenschaften bearbeiten</value>
  </data>
  <data name="_59" xml:space="preserve">
    <value>Name</value>
  </data>
  <data name="_58" xml:space="preserve">
    <value>werwer</value>
  </data>
  <data name="_57" xml:space="preserve">
    <value>Löschen</value>
  </data>
  <data name="_56" xml:space="preserve">
    <value>Eine Eigenschaft bearbeiten</value>
  </data>
  <data name="_55" xml:space="preserve">
    <value>Speichern</value>
  </data>
  <data name="_54" xml:space="preserve">
    <value>Inhalt:</value>
  </data>
  <data name="_53" xml:space="preserve">
    <value>Name:</value>
  </data>
  <data name="_52" xml:space="preserve">
    <value>toolStripButtonRefresh</value>
  </data>
  <data name="_51" xml:space="preserve">
    <value>toolStripTop</value>
  </data>
  <data name="_50" xml:space="preserve">
    <value>labelBotWissensLokalisierung</value>
  </data>
  <data name="_48" xml:space="preserve">
    <value>Begrüßung</value>
  </data>
  <data name="_49" xml:space="preserve">
    <value />
  </data>
  <data name="_46" xml:space="preserve">
    <value>buttonAbsenden</value>
  </data>
  <data name="_47" xml:space="preserve">
    <value>Begrüßung</value>
  </data>
  <data name="_44" xml:space="preserve">
    <value>GaitoBot-ID:</value>
  </data>
  <data name="_45" xml:space="preserve">
    <value>linkLabelKeineBotID</value>
  </data>
  <data name="_42" xml:space="preserve">
    <value>labelDenkprotokoll</value>
  </data>
  <data name="_43" xml:space="preserve">
    <value>buttonPublish</value>
  </data>
  <data name="_40" xml:space="preserve">
    <value>history back</value>
  </data>
  <data name="_41" xml:space="preserve">
    <value>toolStripButtonSyncronisieren</value>
  </data>
</root>