<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="CategoryListeCellAIMLCategory" xml:space="preserve">
    <value>category</value>
  </data>
  <data name="toolStripButtonUmbenennen" xml:space="preserve">
    <value>rename</value>
  </data>
  <data name="GruppeStandard" xml:space="preserve">
    <value>standard</value>
  </data>
  <data name="SuchenCellAIMLCategory" xml:space="preserve">
    <value>category</value>
  </data>
  <data name="Export" xml:space="preserve">
    <value>Export</value>
  </data>
  <data name="ToolbarButtonNichtBehandelt" xml:space="preserve">
    <value>Toolbarbutton '{0}' not handled.</value>
  </data>
  <data name="Template" xml:space="preserve">
    <value>reaction</value>
  </data>
  <data name="WebDokumentAdresse" xml:space="preserve">
    <value>http://www.gaitobot.de/gaitobot/EditorDocuments/document.asp?documentname={4}&amp;language=en&amp;major={0}&amp;minor={1}&amp;revision={2}&amp;licence={3}</value>
  </data>
  <data name="toolStripLabelWonachSuchen" xml:space="preserve">
    <value>search:</value>
  </data>
  <data name="toolStripButtonHistoryBack" xml:space="preserve">
    <value>History back</value>
  </data>
  <data name="GaitotbotIDExistiertNicht" xml:space="preserve">
    <value>Invalid GaitoBot-ID</value>
  </data>
  <data name="checkBoxVorExportVerzeichnisLeeren" xml:space="preserve">
    <value>Clear export directory before exporting</value>
  </data>
  <data name="Fehler" xml:space="preserve">
    <value>Error</value>
  </data>
  <data name="ExportAbgebrochen" xml:space="preserve">
    <value>Export aborted.</value>
  </data>
  <data name="AIMLDateienWerdenExportiert" xml:space="preserve">
    <value>Exporting AIML files</value>
  </data>
  <data name="SuchenOrtNameInAktuellerAIMLDatei" xml:space="preserve">
    <value>selected aiml-file</value>
  </data>
  <data name="toolStripButtonOpenFile" xml:space="preserve">
    <value>import existing AIML file</value>
  </data>
  <data name="toolStripButtonCreateTHATReferenceTooltip" xml:space="preserve">
    <value>generate new category with THAT fitting to the actual category </value>
  </data>
  <data name="toolStripButtonSortieren" xml:space="preserve">
    <value>sort</value>
  </data>
  <data name="toolStripLabelWoSuchen" xml:space="preserve">
    <value>in:</value>
  </data>
  <data name="AktuelleCategoryLoeschen" xml:space="preserve">
    <value>Delete category</value>
  </data>
  <data name="DokumentElementNichtGaitoBotStartup" xml:space="preserve">
    <value>The document-element has to be &lt;gaitobot-startup&gt;</value>
  </data>
  <data name="toolStripButtonCreateTHATReferenceText" xml:space="preserve">
    <value>new fitting THAT</value>
  </data>
  <data name="NodeNichtVorhandenOderFehlerhaft" xml:space="preserve">
    <value>node '{0}' not found or invalid</value>
  </data>
  <data name="NochKeinDateinameVergeben" xml:space="preserve">
    <value>No filename has been defined</value>
  </data>
  <data name="toolStripButtonNeuesThema" xml:space="preserve">
    <value>new topic</value>
  </data>
  <data name="labelExportVerzeichnis" xml:space="preserve">
    <value>export directory</value>
  </data>
  <data name="toolStripButtonDeleteKategory" xml:space="preserve">
    <value>delete category</value>
  </data>
  <data name="PublizierenbuttonPublish" xml:space="preserve">
    <value>Publish</value>
  </data>
  <data name="ungueltig" xml:space="preserve">
    <value>invalid</value>
  </data>
  <data name="BitteNeuenNamenFuerAIMLDatei" xml:space="preserve">
    <value>Please enter a new name for this aiml-file.</value>
  </data>
  <data name="PublizierenlinkLabelKeineBotID" xml:space="preserve">
    <value>You don´t have a GaitoBot-ID?</value>
  </data>
  <data name="DerInhaltDesArbeitsbereichesWurdeVeraendert" xml:space="preserve">
    <value>The properties of workspace '{0}' has been changed.</value>
  </data>
  <data name="ExportButtonDurchsuchenText" xml:space="preserve">
    <value>browse</value>
  </data>
  <data name="MeisteSRAIEndZieleAnzahl" xml:space="preserve">
    <value>count</value>
  </data>
  <data name="ArbeitsbereichWissensSprachenEnglisch" xml:space="preserve">
    <value>english</value>
  </data>
  <data name="DateiIstDefektUndSollteVorSpeichernKorrigiertWerden" xml:space="preserve">
    <value>File '{0}' is invalid and should be corrected before saving.</value>
  </data>
  <data name="ExportStarten" xml:space="preserve">
    <value>start export</value>
  </data>
  <data name="SollDasThemaWirklichGeloeschtWerden" xml:space="preserve">
    <value>Do you really want to delete topic '{0}'?</value>
  </data>
  <data name="ThemaLoeschen" xml:space="preserve">
    <value>delete topic</value>
  </data>
  <data name="LoescheAlteAIMLDateienRemote" xml:space="preserve">
    <value>Deleting outdated remote files</value>
  </data>
  <data name="VerzeichnisErstellungFehlgeschlagen" xml:space="preserve">
    <value>Failed to create directory '{0}':{1}</value>
  </data>
  <data name="automatischeTestsToolStripMenuItem" xml:space="preserve">
    <value>automatic tests</value>
  </data>
  <data name="SollenDieAenderungenGespeichertWerden" xml:space="preserve">
    <value>Do you want to save the changes?</value>
  </data>
  <data name="DTDFehler" xml:space="preserve">
    <value>dtd error</value>
  </data>
  <data name="DieseDateiNichtExportieren" xml:space="preserve">
    <value>don´t export</value>
  </data>
  <data name="ButtonSuchen" xml:space="preserve">
    <value>search</value>
  </data>
  <data name="CategoryListeCellAIMLDateiThema" xml:space="preserve">
    <value>topic</value>
  </data>
  <data name="AIMLDateiUmbenennen" xml:space="preserve">
    <value>rename aiml-file</value>
  </data>
  <data name="SucheNachIn" xml:space="preserve">
    <value>Search for '{0}' in {1}</value>
  </data>
  <data name="MeisteSRAIEndZieleZiel" xml:space="preserve">
    <value>target</value>
  </data>
  <data name="KonnteAIMLTopicNichtUmbenennen" xml:space="preserve">
    <value>Unable to rename topic.</value>
  </data>
  <data name="AIMLExportGroesseErlaubtKB" xml:space="preserve">
    <value>Allowed size is {0}kb</value>
  </data>
  <data name="PublizierenLabelGaitoBotID" xml:space="preserve">
    <value>GaitoBot-ID:</value>
  </data>
  <data name="NeuenArbeitsbereicherzeugen" xml:space="preserve">
    <value>Create new workspace</value>
  </data>
  <data name="KonnteAIMLDateiNichtUmbenennen" xml:space="preserve">
    <value>Unable to rename aiml-file.</value>
  </data>
  <data name="toolStripButtonTopicUmbenennen" xml:space="preserve">
    <value>rename topic</value>
  </data>
  <data name="cloneToolStripMenuItem" xml:space="preserve">
    <value>clone</value>
  </data>
  <data name="GaitotbotIDExistiert" xml:space="preserve">
    <value>GaitoBot-ID checked</value>
  </data>
  <data name="StartupDateiInhaltlichFehlerhaft" xml:space="preserve">
    <value>Content of Startup is invalid:\n{0}</value>
  </data>
  <data name="SuchTitelMitTreffer" xml:space="preserve">
    <value>{0}: {1} hit(s)</value>
  </data>
  <data name="BotTestLadeProtokollZeigenButton" xml:space="preserve">
    <value>display load protocol</value>
  </data>
  <data name="DokumentElementAIMLNurEinmal" xml:space="preserve">
    <value>There can only be one element &lt;aiml&gt; inside a document. In this document there are more than one &lt;aiml&gt;-tag.</value>
  </data>
  <data name="AIMLDateiLadeFehler" xml:space="preserve">
    <value>File \"{0}\" is not valid and has not been loaded.\n\nDetails:\n{1}</value>
  </data>
  <data name="toolStripButtonCloneTemplateText" xml:space="preserve">
    <value>clone Template</value>
  </data>
  <data name="Pattern" xml:space="preserve">
    <value>pattern</value>
  </data>
  <data name="DokumentElementNichtAIML" xml:space="preserve">
    <value>The document-element has to be &lt;aiml&gt;</value>
  </data>
  <data name="AIMLDateiNameUngueltigOderKeinZugriff" xml:space="preserve">
    <value>No valid name for an AIML file ({0}).</value>
  </data>
  <data name="toolStripButtonSave" xml:space="preserve">
    <value>save selected file</value>
  </data>
  <data name="WebGoAdresse" xml:space="preserve">
    <value>http://www.gaitobot.de/gaitobot/go/{4}/?language=en&amp;major={0}&amp;minor={1}&amp;revision={2}&amp;licence={3}</value>
  </data>
  <data name="NamenFuerNeueAIMLDateiAngeben" xml:space="preserve">
    <value>Please enter a name for the new AIML file</value>
  </data>
  <data name="toolStripButtonPassendesSRAITooltip" xml:space="preserve">
    <value>generate new category with SRAI fitting to the actual category </value>
  </data>
  <data name="DokumentElementHatNamespace" xml:space="preserve">
    <value>The document-element contains a special namespace xmlns \"{0}\" inside the aiml-tag. This is not yet supported in this editor-version.</value>
  </data>
  <data name="AIMLDateiNichtDTDGueltig" xml:space="preserve">
    <value>The AIML-file is not valid on AIML-rules.</value>
  </data>
  <data name="DenkprotokollInfo" xml:space="preserve">
    <value>Info</value>
  </data>
  <data name="BotTestButtonAbsenden" xml:space="preserve">
    <value>say</value>
  </data>
  <data name="toolStripSplitButtonTest" xml:space="preserve">
    <value>test</value>
  </data>
  <data name="AIMLDateiInhaltlichFehlerhaft" xml:space="preserve">
    <value>Content of AIML is invalid:\n{0}</value>
  </data>
  <data name="searchInActualTopicToolStripMenuItem" xml:space="preserve">
    <value>Search in actual topic</value>
  </data>
  <data name="searchInActualAimlfileToolStripMenuItem" xml:space="preserve">
    <value>Search in actual AIML file</value>
  </data>
  <data name="NameFuerAIMLTopicVergeben" xml:space="preserve">
    <value>Set topic name</value>
  </data>
  <data name="toolStripButtonFehlerzeigen" xml:space="preserve">
    <value>Show errors</value>
  </data>
  <data name="ArbeitsbereichUmbenennen" xml:space="preserve">
    <value>Rename workspace</value>
  </data>
  <data name="toolStripButtonDelete" xml:space="preserve">
    <value>delete selected file</value>
  </data>
  <data name="PublizierungGestartet" xml:space="preserve">
    <value>Publishing started</value>
  </data>
  <data name="toolStripButtonExport" xml:space="preserve">
    <value>export</value>
  </data>
  <data name="toolStripButtonHistoryForward" xml:space="preserve">
    <value>History forward</value>
  </data>
  <data name="BestSRAISRAI" xml:space="preserve">
    <value>srai</value>
  </data>
  <data name="ArbeitsBereichMussVorExportGespeichertWerden" xml:space="preserve">
    <value>The workspace must be saved before exporting. Save now?</value>
  </data>
  <data name="toolStripButtonTopicLoeschen" xml:space="preserve">
    <value>delete topic</value>
  </data>
  <data name="ucMeisteSRAIStoolStripButtonRefresh" xml:space="preserve">
    <value>refresh</value>
  </data>
  <data name="AktuelleCategoryWirklichLoeschen" xml:space="preserve">
    <value>Do you really want to delete this category?</value>
  </data>
  <data name="ArbeitsbereichWissensSprachenDeutsch" xml:space="preserve">
    <value>german</value>
  </data>
  <data name="DokumentElementStartupNurEinmal" xml:space="preserve">
    <value>There can only be one element &lt;gaitobot-startup&gt; inside a document. In this document there are more than one &lt;aiml&gt;-tag.</value>
  </data>
  <data name="SollDieDateiDefektGespeichertWerden" xml:space="preserve">
    <value>Save this invalid file anyway?</value>
  </data>
  <data name="AIMLExportGroesseLautetKB" xml:space="preserve">
    <value>Size of AIML export is {0}kb</value>
  </data>
  <data name="SuchenCellAIMLDateiThema" xml:space="preserve">
    <value>topic</value>
  </data>
  <data name="NamenFuerNeuenArbeitsbereichEingeben" xml:space="preserve">
    <value>Please enter a name for the new workspace</value>
  </data>
  <data name="DateiInhaltHatSichSeitSpeichernGeaendert" xml:space="preserve">
    <value> The content of aiml file "{0}" has changed since last saving.</value>
  </data>
  <data name="RootTopicKannNichtGeloeschtWerden" xml:space="preserve">
    <value>Root-Topic cannot be deleted.</value>
  </data>
  <data name="GruppeHTML" xml:space="preserve">
    <value>html</value>
  </data>
  <data name="PublizierenNichtAlleAIMLDateienKorrekt" xml:space="preserve">
    <value>Your workspace contains AIML-files which are not valid on AIML-rules. </value>
  </data>
  <data name="AnzahlDateienZuPublizieren" xml:space="preserve">
    <value>{0} AIML files to publish</value>
  </data>
  <data name="MeineErsteAimlDatei" xml:space="preserve">
    <value>MyFirstAimlFile</value>
  </data>
  <data name="ExportErfolgreich" xml:space="preserve">
    <value>Export done.</value>
  </data>
  <data name="PublizierungFehlerhaft" xml:space="preserve">
    <value>Publishing not successfull</value>
  </data>
  <data name="SollExportVerzeichnisAngelegtWerden" xml:space="preserve">
    <value>Export directory does not exist. Create now?</value>
  </data>
  <data name="BetaVersionVeraltet" xml:space="preserve">
    <value>This beta version is outdated. \n\n Please download a current version at http://www.gaitobot.de </value>
  </data>
  <data name="DenkprotokollColumnInhalt" xml:space="preserve">
    <value>content</value>
  </data>
  <data name="checkBoxAlleStarTagsInEineDatei" xml:space="preserve">
    <value>Export all star-tags into a extra aiml-file.</value>
  </data>
  <data name="NochKeineSucheAusgefuehrt" xml:space="preserve">
    <value>No search started.</value>
  </data>
  <data name="toolStripButtonTHATKlonenToolTipp" xml:space="preserve">
    <value>create new categoy with same THAT as the actual category</value>
  </data>
  <data name="manuellerTestToolStripMenuItem" xml:space="preserve">
    <value>non-automatic test</value>
  </data>
  <data name="toolStripLabelWissenWirdGeladen" xml:space="preserve">
    <value>loading knowledge (file {0} of {1})</value>
  </data>
  <data name="AIMLDateiDefekt" xml:space="preserve">
    <value>AIML contains errors:\n{0}</value>
  </data>
  <data name="BitteAIMLDateiWaehlen" xml:space="preserve">
    <value>Please choose the aiml file</value>
  </data>
  <data name="GruppeFortgeschritten" xml:space="preserve">
    <value>advanced</value>
  </data>
  <data name="toolStripButtonPassendesSRAIText" xml:space="preserve">
    <value>new fitting SRAI</value>
  </data>
  <data name="toolStripButtonSearch" xml:space="preserve">
    <value>search</value>
  </data>
  <data name="toolStripButtonNeueKategorie" xml:space="preserve">
    <value>new category</value>
  </data>
  <data name="StartupDateiDefekt" xml:space="preserve">
    <value>Startup-File contains errors:\n{0}</value>
  </data>
  <data name="buttonExportStarten" xml:space="preserve">
    <value>start export</value>
  </data>
  <data name="SuchenCellAIMLDatei" xml:space="preserve">
    <value>AIML file</value>
  </data>
  <data name="UngueltigeSuchEingabe" xml:space="preserve">
    <value>Invalid search '{0}'</value>
  </data>
  <data name="unbenannt" xml:space="preserve">
    <value>noname</value>
  </data>
  <data name="toolStripButtonPublish" xml:space="preserve">
    <value>publish</value>
  </data>
  <data name="toolStripButtonWissenNeuLaden" xml:space="preserve">
    <value>reload knowledge</value>
  </data>
  <data name="toolStripButtonAIMLDateiUmbenennen" xml:space="preserve">
    <value>rename AIML-file</value>
  </data>
  <data name="labelDenkprotokoll" xml:space="preserve">
    <value>matching protocol</value>
  </data>
  <data name="labelBotWissensLokalisierung" xml:space="preserve">
    <value>Language of bot knowledge</value>
  </data>
  <data name="DenkProtokollEingabe" xml:space="preserve">
    <value>Input</value>
  </data>
  <data name="toolStripButtonTHATKlonenText" xml:space="preserve">
    <value>clone THAT</value>
  </data>
  <data name="AIMLDateiSchonVorhanden" xml:space="preserve">
    <value>An aiml file with this name already exists.</value>
  </data>
  <data name="AIMLExportZuGrossFuerPublizieren" xml:space="preserve">
    <value>The AIML export is bigger than the allowed size of your GaitoBot licence</value>
  </data>
  <data name="TopicNameSchonVorhanden" xml:space="preserve">
    <value>Topic name '{0}' already exists.</value>
  </data>
  <data name="NeueAIMLDateiErzeugen" xml:space="preserve">
    <value>Create new AIML file</value>
  </data>
  <data name="PublizierungErfolgreich" xml:space="preserve">
    <value>Publishing successfull</value>
  </data>
  <data name="CategoryListeCellAIMLDatei" xml:space="preserve">
    <value>aiml file</value>
  </data>
  <data name="SuchenOrtNameImArbeitsbereich" xml:space="preserve">
    <value>workspace</value>
  </data>
  <data name="FehlerImXMLDokJetztAnzeigen" xml:space="preserve">
    <value>Errors found in xml document. Do you want to watch these errors now?</value>
  </data>
  <data name="DenkprotokollColumnArt" xml:space="preserve">
    <value>step</value>
  </data>
  <data name="passendeKategorieGefunden" xml:space="preserve">
    <value>Found matching category</value>
  </data>
  <data name="FehlerBeimDateiPublizieren" xml:space="preserve">
    <value>Error transfering file '{0}': {1}</value>
  </data>
  <data name="toolStripButtonSaveAll" xml:space="preserve">
    <value>save all</value>
  </data>
  <data name="FehlerBeiGaitoBotWebServiceZugriff" xml:space="preserve">
    <value>Error requesting GaitoBot Webservice: {0}</value>
  </data>
  <data name="KeinDateiNameUebergeben" xml:space="preserve">
    <value>No filename received</value>
  </data>
  <data name="EsLaeuftBereitsEineSuche" xml:space="preserve">
    <value>There is already a search running.</value>
  </data>
  <data name="BitteNeuenNamenFuerArbeitsbereich" xml:space="preserve">
    <value>Please enter a new name for this workspace.</value>
  </data>
  <data name="toolStripSplitButtonSucheImArbeitsbereich" xml:space="preserve">
    <value>Search in workspace</value>
  </data>
  <data name="SuchenOrtNameInAktuellemTopic" xml:space="preserve">
    <value>selected topic</value>
  </data>
  <data name="BitteNamenFuerAIMLTopic" xml:space="preserve">
    <value>Please enter a name for this topic.</value>
  </data>
  <data name="PubliziereDatei" xml:space="preserve">
    <value>Publishing '{0}'</value>
  </data>
  <data name="AIMLDateiWirklichLoeschen" xml:space="preserve">
    <value>Really delete AIML file "{0}"?</value>
  </data>
  <data name="KeineGaitoBotIDEingegeben" xml:space="preserve">
    <value>You must enter a GaitoBot-ID</value>
  </data>
  <data name="KannStandardTopicNichtUmbenennen" xml:space="preserve">
    <value>The root topic cannot be renamed.</value>
  </data>
  <data name="Warnung" xml:space="preserve">
    <value>Warning!</value>
  </data>
  <data name="toolStripButtonSyncronisieren" xml:space="preserve">
    <value>refresh</value>
  </data>
  <data name="That" xml:space="preserve">
    <value>before</value>
  </data>
  <data name="toolStripButtonNewFile" xml:space="preserve">
    <value>new AIML file</value>
  </data>
  <data name="FehlerBeimRemoteLoeschen" xml:space="preserve">
    <value>Error deleting outdated remote files: {0}</value>
  </data>
  <data name="ExportVerzeichnisWirklichLeeren" xml:space="preserve">
    <value>Really clear export directory \n'{0}'\n and all its content?</value>
  </data>
  <data name="BestSRAIAnzahl" xml:space="preserve">
    <value>count</value>
  </data>
</root>