<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
  <data name="treeViewDateien.Size" type="System.Drawing.Size, System.Drawing">
    <value>201, 196</value>
  </data>
  <assembly alias="mscorlib" name="mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="treeViewDateien.SelectedImageIndex" type="System.Int32, mscorlib">
    <value>0</value>
  </data>
  <data name="toolStripButtonNewFile.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="$this.Size" type="System.Drawing.Size, System.Drawing">
    <value>312, 336</value>
  </data>
  <data name="toolStripButtonHinzugelinkteDateienWaehlen.Size" type="System.Drawing.Size, System.Drawing">
    <value>23, 22</value>
  </data>
  <data name="toolStripButtonHinzugelinkteDateienWaehlen.Text" xml:space="preserve">
    <value>toolStripButton1</value>
  </data>
  <data name="toolStripButtonHinzugelinkteDateienWaehlen.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="&gt;&gt;toolStripButtonOpenFile.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripButtonOpenFile.Name" xml:space="preserve">
    <value>toolStripButtonOpenFile</value>
  </data>
  <data name="&gt;&gt;treeViewDateien.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="&gt;&gt;toolStripSeparator2.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripSeparator, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripSeparator2.Name" xml:space="preserve">
    <value>toolStripSeparator2</value>
  </data>
  <data name="&gt;&gt;treeViewDateien.ZOrder" xml:space="preserve">
    <value>0</value>
  </data>
  <data name="&gt;&gt;toolStripSeparator1.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripSeparator, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripSeparator1.Name" xml:space="preserve">
    <value>toolStripSeparator1</value>
  </data>
  <data name="treeViewDateien.TabIndex" type="System.Int32, mscorlib">
    <value>4</value>
  </data>
  <data name="toolStripButtonDelete.ToolTipText" xml:space="preserve">
    <value>delete</value>
  </data>
  <data name="&gt;&gt;treeViewDateien.Type" xml:space="preserve">
    <value>System.Windows.Forms.TreeView, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;treeViewDateien.Name" xml:space="preserve">
    <value>treeViewDateien</value>
  </data>
  <data name="newAimlFileToolStripMenuItem.Size" type="System.Drawing.Size, System.Drawing">
    <value>155, 22</value>
  </data>
  <data name="newAimlFileToolStripMenuItem.Text" xml:space="preserve">
    <value>new aiml file</value>
  </data>
  <data name="toolStripButtonAIMLDateiUmbenennen.ToolTipText" xml:space="preserve">
    <value>rename</value>
  </data>
  <data name="toolStripButtonDelete.Text" xml:space="preserve">
    <value>delete</value>
  </data>
  <data name="toolStripButtonDelete.Size" type="System.Drawing.Size, System.Drawing">
    <value>23, 22</value>
  </data>
  <data name="toolStripButtonFehlerZeigen.ToolTipText" xml:space="preserve">
    <value>toolStripButton1</value>
  </data>
  <data name="newReplaceConfigFileToolStripMenuItem.Text" xml:space="preserve">
    <value>new startup file</value>
  </data>
  <data name="newReplaceConfigFileToolStripMenuItem.Size" type="System.Drawing.Size, System.Drawing">
    <value>155, 22</value>
  </data>
  <data name="toolStrip1.Location" type="System.Drawing.Point, System.Drawing">
    <value>0, 0</value>
  </data>
  <data name="toolStripButtonAIMLDateiUmbenennen.Size" type="System.Drawing.Size, System.Drawing">
    <value>23, 22</value>
  </data>
  <data name="toolStripButtonAIMLDateiUmbenennen.Text" xml:space="preserve">
    <value>rename</value>
  </data>
  <data name="toolStripButtonFehlerZeigen.Size" type="System.Drawing.Size, System.Drawing">
    <value>23, 22</value>
  </data>
  <data name="toolStripButtonFehlerZeigen.Text" xml:space="preserve">
    <value>toolStripButton1</value>
  </data>
  <data name="&gt;&gt;toolStripButtonAIMLDateiUmbenennen.Name" xml:space="preserve">
    <value>toolStripButtonAIMLDateiUmbenennen</value>
  </data>
  <data name="&gt;&gt;toolStripButtonAIMLDateiUmbenennen.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="treeViewDateien.ImageIndex" type="System.Int32, mscorlib">
    <value>0</value>
  </data>
  <data name="toolStripButtonFehlerZeigen.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="imageListDateien.ImageStream" mimetype="application/x-microsoft.net.object.binary.base64">
    <value>
        AAEAAAD/////AQAAAAAAAAAMAgAAAFdTeXN0ZW0uV2luZG93cy5Gb3JtcywgVmVyc2lvbj00LjAuMC4w
        LCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkFAQAAACZTeXN0
        ZW0uV2luZG93cy5Gb3Jtcy5JbWFnZUxpc3RTdHJlYW1lcgEAAAAERGF0YQcCAgAAAAkDAAAADwMAAAAM
        CwAAAk1TRnQBSQFMAgEBAwEAARABAAEQAQABEAEAARABAAT/AQkBEAj/AUIBTQE2AQQGAAE2AQQCAAEo
        AwABQAMAARADAAEBAQABCAYAAQQYAAGAAgABgAMAAoABAAGAAwABgAEAAYABAAKAAgADwAEAAcAB3AHA
        AQAB8AHKAaYBAAEzBQABMwEAATMBAAEzAQACMwIAAxYBAAMcAQADIgEAAykBAANVAQADTQEAA0IBAAM5
        AQABgAF8Af8BAAJQAf8BAAGTAQAB1gEAAf8B7AHMAQABxgHWAe8BAAHWAucBAAGQAakBrQIAAf8BMwMA
        AWYDAAGZAwABzAIAATMDAAIzAgABMwFmAgABMwGZAgABMwHMAgABMwH/AgABZgMAAWYBMwIAAmYCAAFm
        AZkCAAFmAcwCAAFmAf8CAAGZAwABmQEzAgABmQFmAgACmQIAAZkBzAIAAZkB/wIAAcwDAAHMATMCAAHM
        AWYCAAHMAZkCAALMAgABzAH/AgAB/wFmAgAB/wGZAgAB/wHMAQABMwH/AgAB/wEAATMBAAEzAQABZgEA
        ATMBAAGZAQABMwEAAcwBAAEzAQAB/wEAAf8BMwIAAzMBAAIzAWYBAAIzAZkBAAIzAcwBAAIzAf8BAAEz
        AWYCAAEzAWYBMwEAATMCZgEAATMBZgGZAQABMwFmAcwBAAEzAWYB/wEAATMBmQIAATMBmQEzAQABMwGZ
        AWYBAAEzApkBAAEzAZkBzAEAATMBmQH/AQABMwHMAgABMwHMATMBAAEzAcwBZgEAATMBzAGZAQABMwLM
        AQABMwHMAf8BAAEzAf8BMwEAATMB/wFmAQABMwH/AZkBAAEzAf8BzAEAATMC/wEAAWYDAAFmAQABMwEA
        AWYBAAFmAQABZgEAAZkBAAFmAQABzAEAAWYBAAH/AQABZgEzAgABZgIzAQABZgEzAWYBAAFmATMBmQEA
        AWYBMwHMAQABZgEzAf8BAAJmAgACZgEzAQADZgEAAmYBmQEAAmYBzAEAAWYBmQIAAWYBmQEzAQABZgGZ
        AWYBAAFmApkBAAFmAZkBzAEAAWYBmQH/AQABZgHMAgABZgHMATMBAAFmAcwBmQEAAWYCzAEAAWYBzAH/
        AQABZgH/AgABZgH/ATMBAAFmAf8BmQEAAWYB/wHMAQABzAEAAf8BAAH/AQABzAEAApkCAAGZATMBmQEA
        AZkBAAGZAQABmQEAAcwBAAGZAwABmQIzAQABmQEAAWYBAAGZATMBzAEAAZkBAAH/AQABmQFmAgABmQFm
        ATMBAAGZATMBZgEAAZkBZgGZAQABmQFmAcwBAAGZATMB/wEAApkBMwEAApkBZgEAA5kBAAKZAcwBAAKZ
        Af8BAAGZAcwCAAGZAcwBMwEAAWYBzAFmAQABmQHMAZkBAAGZAswBAAGZAcwB/wEAAZkB/wIAAZkB/wEz
        AQABmQHMAWYBAAGZAf8BmQEAAZkB/wHMAQABmQL/AQABzAMAAZkBAAEzAQABzAEAAWYBAAHMAQABmQEA
        AcwBAAHMAQABmQEzAgABzAIzAQABzAEzAWYBAAHMATMBmQEAAcwBMwHMAQABzAEzAf8BAAHMAWYCAAHM
        AWYBMwEAAZkCZgEAAcwBZgGZAQABzAFmAcwBAAGZAWYB/wEAAcwBmQIAAcwBmQEzAQABzAGZAWYBAAHM
        ApkBAAHMAZkBzAEAAcwBmQH/AQACzAIAAswBMwEAAswBZgEAAswBmQEAA8wBAALMAf8BAAHMAf8CAAHM
        Af8BMwEAAZkB/wFmAQABzAH/AZkBAAHMAf8BzAEAAcwC/wEAAcwBAAEzAQAB/wEAAWYBAAH/AQABmQEA
        AcwBMwIAAf8CMwEAAf8BMwFmAQAB/wEzAZkBAAH/ATMBzAEAAf8BMwH/AQAB/wFmAgAB/wFmATMBAAHM
        AmYBAAH/AWYBmQEAAf8BZgHMAQABzAFmAf8BAAH/AZkCAAH/AZkBMwEAAf8BmQFmAQAB/wKZAQAB/wGZ
        AcwBAAH/AZkB/wEAAf8BzAIAAf8BzAEzAQAB/wHMAWYBAAH/AcwBmQEAAf8CzAEAAf8BzAH/AQAC/wEz
        AQABzAH/AWYBAAL/AZkBAAL/AcwBAAJmAf8BAAFmAf8BZgEAAWYC/wEAAf8CZgEAAf8BZgH/AQAC/wFm
        AQABIQEAAaUBAANfAQADdwEAA4YBAAOWAQADywEAA7IBAAPXAQAD3QEAA+MBAAPqAQAD8QEAA/gBAAHw
        AfsB/wEAAaQCoAEAA4ADAAH/AgAB/wMAAv8BAAH/AwAB/wEAAf8BAAL/AgAD/wIAAf8CtQEJAf8OAAP/
        Aa4B6gHwA/8EAAG1B7QBzwG0Aa4B9BUAAfQBtQEJArUDtAEJAfEB/wYAAbwBrgHqAewBzwGuAW0BrgFs
        AewB/wMAA7UEtAHPAq4BtAG8AfQUAAH0AbUDGQP0Ad0BCQG0AfEB/wQAAZEBtQG0A64BiwGuAYsBbAH/
        AwABtQHcArUCtAG1AQcB7gLwAbQBvBMAAfQBtAEJBBkB9AMZAd0BtQG8AgAB8gFtAesBtQKRAq4DiwHq
        Aa4B7AH/AQAECQG8A/IC8QHwAbQBzxIAAf8BtAG1AgkHGQIJAbQB9AEAAewBCQO1AbQBkQKuA4sBrgFs
        AfIBAAHdA/MB8gTzAfIB8AHvAbQSAAG8AbQBtQMJBRkDCQG1AQkBAAEHAd0B9wG7AbUB9wKuAe0BrgKL
        Aq4B/wEAAfMB9AHzAfQB8wP0AfMB8gHxAe8B9xIAAbUBzwG0AbUJCQG1ArQB/wH3AbUCuwH3AbwC/wEH
        AZICiwGuAeoB8gEAAfMH9AHzAfIB8QLvEgABtAHPArQBtQcJAbUCtAHPAewBuwHvAQkBvAGuAf8CAAH/
        Aq4BiwKuAeoBAAHzA/8D9APzAfIC7xIAAbUDzwG0B7UBtALPAbQBuwEZAbsBvAHwAa4B/wIAAf8ErgG0
        AYsBAAH0A/8D9APzAfIC7xIAAQkEzwe0As8BtAEJAfMBvAEHAQkB8QG1AbwC/wEHAfcBkQGuAZEBrgHy
        AQAB9AT/BPQB8wHyAu8SAAH/AbQBzwGtCc8BtQHPAf8BAAHsAbsBBwLwAbUCrgH3AbUBtAGRAbUB6gHz
        AQAB8wT/AfQCGQEJArUBrgG1EwAB8gHPAQkBzwKtAs8CrQG0AbUBzwHxAgAB7wEZAgcD8AEJArUBtAH3
        AQkBkQHzAQAB8wH0ARkBCQHcAdYB3AEJAdwB1gG1As8UAAH0ArUCCQG1AwkCzwHzAwABvAH3AewBBwHv
        AgkCuwG1AfcB7AHtAewB/wEAAQkJ3AG1As8WAAHzAQcBtQLPAbUBBwHyAf8GAAHsAt0DtQH3AQkB3QFt
        Af8DAAG1ArQBrQeLAc8BtCUAAfABCQGuAe0BCQHdAesB9wG7AewEAAH0AtwB1gLVArQDrQGLAc8mAAL/
        AfQBtQH3AfIBAAH/BQAB/wHzA9UCtAOtAYsBtAH0EgABQgFNAT4HAAE+AwABKAMAAUADAAEQAwABAQEA
        AQEFAAGAFwAD/wEAAYMB/wHwAQcBgAEHAgABwAEHAeABAwGAAQMCAAHAAQEB4AEDAYABAwIAAYABAQGA
        AQABgAEDBAABgAEAAYABAwQAAYABAAGAAQMGAAGAAQMEAAEBAoABAwQAAQECgAEDBgABgAEDBAABgAEA
        AYABAwIAAYABAQGAAQABgAEDAgABwAEDAYABAAGAAQMCAAHwAQcB4AEDAYABAwIAAv8B4AEHAYABAwIA
        Av8B8AEvAYABAxgACw==
</value>
  </data>
  <data name="&gt;&gt;toolStripButtonFehlerZeigen.Name" xml:space="preserve">
    <value>toolStripButtonFehlerZeigen</value>
  </data>
  <data name="&gt;&gt;toolStripButtonFehlerZeigen.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;newReplaceConfigFileToolStripMenuItem.Name" xml:space="preserve">
    <value>newReplaceConfigFileToolStripMenuItem</value>
  </data>
  <data name="&gt;&gt;newReplaceConfigFileToolStripMenuItem.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripMenuItem, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripButtonDelete.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripButtonDelete.Name" xml:space="preserve">
    <value>toolStripButtonDelete</value>
  </data>
  <data name="toolStripButtonOpenFile.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="toolStripButtonAIMLDateiUmbenennen.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="&gt;&gt;mnuSave.Type" xml:space="preserve">
    <value>System.Windows.Forms.MenuItem, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;mnuSave.Name" xml:space="preserve">
    <value>mnuSave</value>
  </data>
  <data name="&gt;&gt;toolStripButtonNewFile.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripDropDownButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripButtonNewFile.Name" xml:space="preserve">
    <value>toolStripButtonNewFile</value>
  </data>
  <data name="toolStripButtonNewFile.ToolTipText" xml:space="preserve">
    <value>new file</value>
  </data>
  <data name="toolStripButtonDelete.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="toolStripButtonNewFile.Size" type="System.Drawing.Size, System.Drawing">
    <value>29, 22</value>
  </data>
  <data name="toolStripButtonNewFile.Text" xml:space="preserve">
    <value>new file</value>
  </data>
  <data name="toolStripButtonSave.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="toolStripSeparator2.Size" type="System.Drawing.Size, System.Drawing">
    <value>6, 25</value>
  </data>
  <data name="toolStripSeparator1.Size" type="System.Drawing.Size, System.Drawing">
    <value>6, 25</value>
  </data>
  <data name="toolStrip1.TabIndex" type="System.Int32, mscorlib">
    <value>3</value>
  </data>
  <data name="toolStripButtonOpenFile.Size" type="System.Drawing.Size, System.Drawing">
    <value>23, 22</value>
  </data>
  <data name="toolStripButtonOpenFile.Text" xml:space="preserve">
    <value>open file</value>
  </data>
  <data name="&gt;&gt;toolStrip1.ZOrder" xml:space="preserve">
    <value>1</value>
  </data>
  <data name="&gt;&gt;$this.Name" xml:space="preserve">
    <value>ucAIMLDateiListe</value>
  </data>
  <data name="&gt;&gt;$this.Type" xml:space="preserve">
    <value>System.Windows.Forms.UserControl, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;imageListDateien.Type" xml:space="preserve">
    <value>System.Windows.Forms.ImageList, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;imageListDateien.Name" xml:space="preserve">
    <value>imageListDateien</value>
  </data>
  <data name="toolStrip1.Text" xml:space="preserve">
    <value>toolStrip</value>
  </data>
  <data name="toolStrip1.Size" type="System.Drawing.Size, System.Drawing">
    <value>312, 25</value>
  </data>
  <data name="treeViewDateien.Location" type="System.Drawing.Point, System.Drawing">
    <value>32, 44</value>
  </data>
  <data name="&gt;&gt;openFileDialog.Type" xml:space="preserve">
    <value>System.Windows.Forms.OpenFileDialog, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;openFileDialog.Name" xml:space="preserve">
    <value>openFileDialog</value>
  </data>
  <data name="&gt;&gt;toolStrip1.Name" xml:space="preserve">
    <value>toolStrip1</value>
  </data>
  <data name="&gt;&gt;toolStrip1.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStrip, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="toolStripButtonOpenFile.ToolTipText" xml:space="preserve">
    <value>open file</value>
  </data>
  <data name="&gt;&gt;newAimlFileToolStripMenuItem.Name" xml:space="preserve">
    <value>newAimlFileToolStripMenuItem</value>
  </data>
  <data name="&gt;&gt;newAimlFileToolStripMenuItem.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripMenuItem, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;tmrRefresh.Type" xml:space="preserve">
    <value>System.Windows.Forms.Timer, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;tmrRefresh.Name" xml:space="preserve">
    <value>tmrRefresh</value>
  </data>
  <data name="toolStripButtonSave.ToolTipText" xml:space="preserve">
    <value>toolStripButtonSave</value>
  </data>
  <data name="&gt;&gt;toolStrip1.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="toolStripButtonSave.Size" type="System.Drawing.Size, System.Drawing">
    <value>23, 22</value>
  </data>
  <data name="toolStripButtonSave.Text" xml:space="preserve">
    <value>toolStripButtonSave</value>
  </data>
  <data name="&gt;&gt;toolStripButtonSave.Name" xml:space="preserve">
    <value>toolStripButtonSave</value>
  </data>
  <data name="&gt;&gt;toolStripButtonSave.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripButtonHinzugelinkteDateienWaehlen.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripButtonHinzugelinkteDateienWaehlen.Name" xml:space="preserve">
    <value>toolStripButtonHinzugelinkteDateienWaehlen</value>
  </data>
</root>