<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="toolStripButtonDeleteKategory.Text" xml:space="preserve">
    <value>delete category</value>
  </data>
  <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
  <data name="toolStripButtonDeleteKategory.Size" type="System.Drawing.Size, System.Drawing">
    <value>108, 22</value>
  </data>
  <data name="imgListToolbar.ImageStream" mimetype="application/x-microsoft.net.object.binary.base64">
    <value>
        AAEAAAD/////AQAAAAAAAAAMAgAAAFdTeXN0ZW0uV2luZG93cy5Gb3JtcywgVmVyc2lvbj00LjAuMC4w
        LCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkFAQAAACZTeXN0
        ZW0uV2luZG93cy5Gb3Jtcy5JbWFnZUxpc3RTdHJlYW1lcgEAAAAERGF0YQcCAgAAAAkDAAAADwMAAACC
        CAAAAk1TRnQBSQFMAgEBAgEAAQQBAAEEAQABEAEAARABAAT/AQkBEAj/AUIBTQE2AQQGAAE2AQQCAAEo
        AwABQAMAARADAAEBAQABCAYAAQQYAAGAAgABgAMAAoABAAGAAwABgAEAAYABAAKAAgADwAEAAcAB3AHA
        AQAB8AHKAaYBAAEzBQABMwEAATMBAAEzAQACMwIAAxYBAAMcAQADIgEAAykBAANVAQADTQEAA0IBAAM5
        AQABgAF8Af8BAAJQAf8BAAGTAQAB1gEAAf8B7AHMAQABxgHWAe8BAAHWAucBAAGQAakBrQIAAf8BMwMA
        AWYDAAGZAwABzAIAATMDAAIzAgABMwFmAgABMwGZAgABMwHMAgABMwH/AgABZgMAAWYBMwIAAmYCAAFm
        AZkCAAFmAcwCAAFmAf8CAAGZAwABmQEzAgABmQFmAgACmQIAAZkBzAIAAZkB/wIAAcwDAAHMATMCAAHM
        AWYCAAHMAZkCAALMAgABzAH/AgAB/wFmAgAB/wGZAgAB/wHMAQABMwH/AgAB/wEAATMBAAEzAQABZgEA
        ATMBAAGZAQABMwEAAcwBAAEzAQAB/wEAAf8BMwIAAzMBAAIzAWYBAAIzAZkBAAIzAcwBAAIzAf8BAAEz
        AWYCAAEzAWYBMwEAATMCZgEAATMBZgGZAQABMwFmAcwBAAEzAWYB/wEAATMBmQIAATMBmQEzAQABMwGZ
        AWYBAAEzApkBAAEzAZkBzAEAATMBmQH/AQABMwHMAgABMwHMATMBAAEzAcwBZgEAATMBzAGZAQABMwLM
        AQABMwHMAf8BAAEzAf8BMwEAATMB/wFmAQABMwH/AZkBAAEzAf8BzAEAATMC/wEAAWYDAAFmAQABMwEA
        AWYBAAFmAQABZgEAAZkBAAFmAQABzAEAAWYBAAH/AQABZgEzAgABZgIzAQABZgEzAWYBAAFmATMBmQEA
        AWYBMwHMAQABZgEzAf8BAAJmAgACZgEzAQADZgEAAmYBmQEAAmYBzAEAAWYBmQIAAWYBmQEzAQABZgGZ
        AWYBAAFmApkBAAFmAZkBzAEAAWYBmQH/AQABZgHMAgABZgHMATMBAAFmAcwBmQEAAWYCzAEAAWYBzAH/
        AQABZgH/AgABZgH/ATMBAAFmAf8BmQEAAWYB/wHMAQABzAEAAf8BAAH/AQABzAEAApkCAAGZATMBmQEA
        AZkBAAGZAQABmQEAAcwBAAGZAwABmQIzAQABmQEAAWYBAAGZATMBzAEAAZkBAAH/AQABmQFmAgABmQFm
        ATMBAAGZATMBZgEAAZkBZgGZAQABmQFmAcwBAAGZATMB/wEAApkBMwEAApkBZgEAA5kBAAKZAcwBAAKZ
        Af8BAAGZAcwCAAGZAcwBMwEAAWYBzAFmAQABmQHMAZkBAAGZAswBAAGZAcwB/wEAAZkB/wIAAZkB/wEz
        AQABmQHMAWYBAAGZAf8BmQEAAZkB/wHMAQABmQL/AQABzAMAAZkBAAEzAQABzAEAAWYBAAHMAQABmQEA
        AcwBAAHMAQABmQEzAgABzAIzAQABzAEzAWYBAAHMATMBmQEAAcwBMwHMAQABzAEzAf8BAAHMAWYCAAHM
        AWYBMwEAAZkCZgEAAcwBZgGZAQABzAFmAcwBAAGZAWYB/wEAAcwBmQIAAcwBmQEzAQABzAGZAWYBAAHM
        ApkBAAHMAZkBzAEAAcwBmQH/AQACzAIAAswBMwEAAswBZgEAAswBmQEAA8wBAALMAf8BAAHMAf8CAAHM
        Af8BMwEAAZkB/wFmAQABzAH/AZkBAAHMAf8BzAEAAcwC/wEAAcwBAAEzAQAB/wEAAWYBAAH/AQABmQEA
        AcwBMwIAAf8CMwEAAf8BMwFmAQAB/wEzAZkBAAH/ATMBzAEAAf8BMwH/AQAB/wFmAgAB/wFmATMBAAHM
        AmYBAAH/AWYBmQEAAf8BZgHMAQABzAFmAf8BAAH/AZkCAAH/AZkBMwEAAf8BmQFmAQAB/wKZAQAB/wGZ
        AcwBAAH/AZkB/wEAAf8BzAIAAf8BzAEzAQAB/wHMAWYBAAH/AcwBmQEAAf8CzAEAAf8BzAH/AQAC/wEz
        AQABzAH/AWYBAAL/AZkBAAL/AcwBAAJmAf8BAAFmAf8BZgEAAWYC/wEAAf8CZgEAAf8BZgH/AQAC/wFm
        AQABIQEAAaUBAANfAQADdwEAA4YBAAOWAQADywEAA7IBAAPXAQAD3QEAA+MBAAPqAQAD8QEAA/gBAAHw
        AfsB/wEAAaQCoAEAA4ADAAH/AgAB/wMAAv8BAAH/AwAB/wEAAf8BAAL/AgAD/0IADuwyAAH/DAcB7AYA
        AgcD7CcAAf8EBwQABAcB7AUAAQcBAAEHAuwBAAHsJgAB/wQHAQACBwEABAcB7AUAAQcBAAEHAuwBAAHs
        JgAB/wQHAQACBwEABAcB7AUAAgcBAALsAQAB7CYAAf8BBwQAAgcEAAEHAewFAAIHAQABBwHsAQAB7CYA
        Af8BBwEACAcBAAEHAewEAAEHAQABBwEAAewBAAHsAQAB7CUAAf8BBwEACAcBAAEHAewEAAEHBwAB7CUA
        Af8BBwQAAgcEAAEHAewEAAHsAQACBwTsJgAB/wQHAQACBwEABAcB7AQAAgcGAAHsJQAB/wQHAQACBwEA
        BAcB7AYABQcnAAH/BAcEAAQHAewEAAIHAuwBBwLsAQcmAAH/DAcB7AQAAwcDAAIHJgAO/wYABQdmAAFC
        AU0BPgcAAT4DAAEoAwABQAMAARADAAEBAQABAQUAAYAXAAP/AQABgAEBAf4BAwYAAfABAQYAAeABAQYA
        AeABAQYAAeABBwYAAeABDwYAAcABBwYAAcABBwYAAcABBwYAAcABBwYAAcABBwYAAcABBwYAAYABAwYA
        AcABBwYAAeABDwQAAYABAQH4AT8aAAs=
</value>
  </data>
  <data name="&gt;&gt;dataGridViewCategories.Type" xml:space="preserve">
    <value>System.Windows.Forms.DataGridView, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;dataGridViewCategories.Name" xml:space="preserve">
    <value>dataGridViewCategories</value>
  </data>
  <data name="&gt;&gt;cloneToolStripMenuItem.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripMenuItem, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;cloneToolStripMenuItem.Name" xml:space="preserve">
    <value>cloneToolStripMenuItem</value>
  </data>
  <data name="&gt;&gt;dataGridViewCategories.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="&gt;&gt;toolStripButtonPassendesSRAI.Name" xml:space="preserve">
    <value>toolStripButtonPassendesSRAI</value>
  </data>
  <data name="&gt;&gt;toolStripButtonPassendesSRAI.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripMenuItem, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="dataGridViewCategories.Location" type="System.Drawing.Point, System.Drawing">
    <value>31, 61</value>
  </data>
  <data name="$this.Size" type="System.Drawing.Size, System.Drawing">
    <value>713, 392</value>
  </data>
  <assembly alias="mscorlib" name="mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="dataGridViewCategories.RowHeadersWidth" type="System.Int32, mscorlib">
    <value>30</value>
  </data>
  <data name="cloneToolStripMenuItem.Size" type="System.Drawing.Size, System.Drawing">
    <value>165, 22</value>
  </data>
  <data name="cloneToolStripMenuItem.Text" xml:space="preserve">
    <value>clone</value>
  </data>
  <data name="toolStripButtonSortieren.ToolTipText" xml:space="preserve">
    <value>sort</value>
  </data>
  <data name="toolStripButtonDeleteKategory.Image" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6
        JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAACqUlEQVQ4T2WQW0gUARiFJx9UBMvCbUsz
        N0sKhOZBRDTLC+ZKIrlpamEtKmFUQm0XrRAh08paH8ouhBkqqIWSqOSFbKUN1tTcSstCk4JKKXK8ZqZx
        mjO7D5oHDvvz/983w6zwf2av+uhnjZtM80W+WFjueLNjSzOap/Eez/exzpTvxfzbOuDP1KJyxxsZsnbN
        lm/nNd7DWRpppu0i8P0l0F8GdOUBL3Js5cydfCNDlo5dF4TPBi/rZMNp4OMj4Nk5TMlvGs7Zgi+n1ivl
        PFG6W7mRIUtHkQePeui/FoQAvSVAiwEjl4IxeMzTOpS5LpT3DxmeYv/JzdLvjlKgNVuuQWHp0BX6Utea
        xisPA01nMHp9F16nqW1PltObqhLfZfhKM53V8ic8xq+yA/hh3KmwdOgK3fvVQGMWUJ2GN+ka9KSoRMod
        iSrRku4jTVsqgb4GTN9NhiVJLZEhS4eu8FznDlTIi9J94EzZHCPLSRppylwBvKrD5I14WBLVklmnEhVe
        Zuko/JOYVZi7FQ/c3gPOzTFuYnuCWpowyf96Ty0mjLFoj1sttcl7PpwMWTrmBA8IjVo3jBXF4q/8/W06
        NZp0amn86X2g+yHGrkSjSesuNUfZ5Ppot1AyZOnQFWoiXU29JwIwXRiJgUw/SA1GoLMKUkEE6rUrpVq7
        zNREuFo/GbYqLB26QkWYi74+bg2GcsMwf3kbUByLnxdCUBXlJFWHuyhyWZhzaHm4k9WS4qUwZOnQVZ5c
        st3J2nLQF+/PBmEuzx99hzR4oF2OezuclXIeOLJRuZEhS0eRmeIgZ++bgY5SXbIGXcf9MZItYi7HD8i1
        lTN3vJEhS8eu28LFtUAH653IFahJ3oDWDHFRueONzBJ5YQoCHPT5ActMclEY7Aj+2mvizY7ZIwj/AKNu
        CrrAg/7/AAAAAElFTkSuQmCC
</value>
  </data>
  <data name="toolStripButtonCloneTemplate.Size" type="System.Drawing.Size, System.Drawing">
    <value>165, 22</value>
  </data>
  <data name="toolStripButtonCloneTemplate.Text" xml:space="preserve">
    <value>clone TEMPLATE</value>
  </data>
  <data name="toolStripButtonTHATKlonen.Text" xml:space="preserve">
    <value>clone THAT</value>
  </data>
  <data name="toolStripButtonTHATKlonen.Size" type="System.Drawing.Size, System.Drawing">
    <value>165, 22</value>
  </data>
  <data name="toolStripButtonDeleteKategory.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="&gt;&gt;toolStripButtonCloneTemplate.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripMenuItem, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripButtonCloneTemplate.Name" xml:space="preserve">
    <value>toolStripButtonCloneTemplate</value>
  </data>
  <data name="&gt;&gt;toolStripButtonDeleteKategory.Name" xml:space="preserve">
    <value>toolStripButtonDeleteKategory</value>
  </data>
  <data name="&gt;&gt;toolStripButtonDeleteKategory.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="toolStrip1.Location" type="System.Drawing.Point, System.Drawing">
    <value>0, 0</value>
  </data>
  <data name="toolStripButtonNeueKategorie.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="&gt;&gt;imgListToolbar.Name" xml:space="preserve">
    <value>imgListToolbar</value>
  </data>
  <data name="&gt;&gt;imgListToolbar.Type" xml:space="preserve">
    <value>System.Windows.Forms.ImageList, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="toolStripButtonDeleteKategory.ToolTipText" xml:space="preserve">
    <value>delete category</value>
  </data>
  <data name="toolStripButtonSortieren.ImageTransparentColor" type="System.Drawing.Color, System.Drawing">
    <value>Magenta</value>
  </data>
  <data name="toolStripButtonNeueKategorie.ToolTipText" xml:space="preserve">
    <value>add new category</value>
  </data>
  <data name="toolStripButtonPassendesSRAI.Text" xml:space="preserve">
    <value>new fitting SRAI</value>
  </data>
  <data name="toolStripButtonPassendesSRAI.Size" type="System.Drawing.Size, System.Drawing">
    <value>165, 22</value>
  </data>
  <data name="toolStripButtonCreateTHATReference.Size" type="System.Drawing.Size, System.Drawing">
    <value>165, 22</value>
  </data>
  <data name="toolStripButtonCreateTHATReference.Text" xml:space="preserve">
    <value>new fitting THAT</value>
  </data>
  <data name="&gt;&gt;toolStripButtonTHATKlonen.Name" xml:space="preserve">
    <value>toolStripButtonTHATKlonen</value>
  </data>
  <data name="&gt;&gt;toolStripButtonTHATKlonen.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripMenuItem, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripButtonCreateTHATReference.Name" xml:space="preserve">
    <value>toolStripButtonCreateTHATReference</value>
  </data>
  <data name="&gt;&gt;toolStripButtonCreateTHATReference.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripMenuItem, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="toolStrip1.TabIndex" type="System.Int32, mscorlib">
    <value>1</value>
  </data>
  <data name="&gt;&gt;toolStripButtonNeueKategorie.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripSplitButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStripButtonNeueKategorie.Name" xml:space="preserve">
    <value>toolStripButtonNeueKategorie</value>
  </data>
  <data name="&gt;&gt;toolStrip1.ZOrder" xml:space="preserve">
    <value>1</value>
  </data>
  <data name="&gt;&gt;$this.Name" xml:space="preserve">
    <value>ucCategoryListe</value>
  </data>
  <data name="&gt;&gt;$this.Type" xml:space="preserve">
    <value>System.Windows.Forms.UserControl, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="toolStrip1.Text" xml:space="preserve">
    <value>toolStrip</value>
  </data>
  <data name="toolStrip1.Size" type="System.Drawing.Size, System.Drawing">
    <value>713, 25</value>
  </data>
  <data name="toolStripButtonSortieren.Text" xml:space="preserve">
    <value>sort</value>
  </data>
  <data name="toolStripButtonSortieren.Size" type="System.Drawing.Size, System.Drawing">
    <value>47, 22</value>
  </data>
  <data name="dataGridViewCategories.Size" type="System.Drawing.Size, System.Drawing">
    <value>503, 261</value>
  </data>
  <data name="&gt;&gt;toolStripButtonSortieren.Name" xml:space="preserve">
    <value>toolStripButtonSortieren</value>
  </data>
  <data name="&gt;&gt;toolStripButtonSortieren.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStripButton, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;toolStrip1.Name" xml:space="preserve">
    <value>toolStrip1</value>
  </data>
  <data name="&gt;&gt;toolStrip1.Type" xml:space="preserve">
    <value>System.Windows.Forms.ToolStrip, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="dataGridViewCategories.TabIndex" type="System.Int32, mscorlib">
    <value>2</value>
  </data>
  <data name="toolStripButtonNeueKategorie.Text" xml:space="preserve">
    <value>add new category</value>
  </data>
  <data name="toolStripButtonNeueKategorie.Size" type="System.Drawing.Size, System.Drawing">
    <value>133, 22</value>
  </data>
  <data name="&gt;&gt;toolStrip1.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="toolStrip1.Items[3].Text" xml:space="preserve">
    <value>miniToolStrip</value>
  </data>
  <data name="&gt;&gt;dataGridViewCategories.ZOrder" xml:space="preserve">
    <value>0</value>
  </data>
</root>