<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
  <data name="delete_161" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANbY1E9YMgAAABl0RVh0U29m
        dHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAKzSURBVDhPZZBpSFRhFIavURZKbkwuTTaTKQVC94cM
        5EIuaJpmaVqZLRNJtFhR2mKLCJla0ki0GVGGWmplJSrGSDqW0eTWrbQNS4KKRKnPNasx3u755v7IPHC4
        5573eb67CP/Xr9PeeovB2zRe4IN/m3aUKdjkGsz20gzneEljJasx/qoK+D0yoWlHGTHEKpq1+o5qNP3H
        tGys4QTQ1wG8KQbasoGWTGvTTDs5I4ZYchRdED6le0rDNQeAD/eAR0cwIj/pa+ZCfN4/lzfNQ0UreUYM
        seRwuTtVrf+SGwR0XgGMaejNC8D7XWqpZ8+cYMrf7VCLPekL2M+nRUB9htxpnCWHXKErxcM0WLYduH8Q
        389GQ763nizXi83u4utUHzbWWiF/Qh1+FG9EvyGCs+SQK7QnuwG1h4CKLXiZokXHejeR5Ja1rqKU4sVG
        zWVAVw1GLydB0qsZMcSSQ67wOF4FlMqLonWgmeSHK1SiOVnLRppLgedVGD6XAPMaD/YkcZbIeZklh/MP
        YlxguZgAFK4CzcZoZ7Ep0ZMNmeS//uwOhgyxaIpzZY0xLvzNiCGWnObE2RBqI50wUBCLP/L3N8S7wRiv
        ZoON14D2Wxg4FQXjchWri3LicnWkYzAxxJJDrlAZPtPUuU+H0fxwdO/2BasxAK3lYLlhqF7mzO5GOHCZ
        Smalj2mLOEsOucKNUHt9dZw7erJCMH4yEDgfi2/Hg3B7qQMrD7PnckmIXfD1UDvJvMGTM8SSQy4/+eqS
        GZJxkw/eHvaHJdsPXVu1uBnpAHnPm+bunfN5Rgyx5HCZqjBouuZCoC2rStKiba8fejNEWDJ9gSxr00w7
        yoghlhxFt9YZ/2kaw+Kp0qVwR1QmzUP9NnFC044yYohVtMmVp5uiz9XZmHJ0NsgPsAVdqWlHmYIpJQh/
        AV+WC3uCIvKNAAAAAElFTkSuQmCC
</value>
  </data>
  <data name="undo_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAACQElE
        QVQ4T41SXUhTYRj+WFldaBxZP6hF0g+xi9KKLrqoVhFGRIyiC7tp1BqC3RQVWViHFfhTUor91wxiELOC
        WoQ3MZNIsbE1NcWDy1qQLKKtsLIon75n57h+TpQPfJyPw/c87/M+7yv+xJIrcefiiy+DtsbnmFc3gNlV
        /cjz9MF6pCc49WCX03hmhiQWyhNxNCdQ3fkR9+L47ait77FcCk4sD0eEO1Ro0HQY5GRF2wfceTEKn/YN
        l3q+oD7yGQ1PR9Ac+54Rct1KwOJqT05yBn+KsLKnfRi3B0dxtfcrTsj7eu8rFJ0egK1GwzL5re4Yzois
        O6she3sgMkZ20jYreyW57P5b5Hv6ktMrn6nKoW579v6oPWtPWM0qD6f2Bt6kBWpDnzDT3YJpW647BQNj
        z7TNynOr+lOSXJxW/wUWV0extaw11RTV8ymofIL8TReCgmnzB3umbVY2OCbklN5VN9d26gL1McwpqYPg
        qPijMTqS7pm2jfcmWLf67KsOtMAvQ1VOapi/9jgE50wBps3A2HP6tTukTNj1WA/KgBRQ8hyXMcXTDcux
        LthWHobgklCAoyqSbhjYGHnyjgcwuBlI2york7xoxT5VcMO4JBThqJg2yQUVIeSUBkwCxMLVRxXjKgTX
        kxtGAR6OasOZXmz0DyF3m/+vAiZwPXffTGREeEpuDGGG49r4BLjbcj1R8/BdRmCN77Wc8/lxOtj5qIk9
        L/XGseDcIGY1xJB7StPn/D+QzLQZGHumbVYmOT3nf0KIHxUVqfSJLHVxAAAAAElFTkSuQmCC
</value>
  </data>
  <data name="copy_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAABt0lE
        QVQ4T4WTUUhTURjHT/jUQy8JUiGIPVQPPSTDl0BZKJnBilUQoYE+TCFdBDJkKEgPSx9igyDWfLkEK6Ug
        SI3AURIoiqmYSFDhkmQzUnGwSGPgz+14bx3PXesPH/fj++7//zsP5wjAVg+nd7g39pvOV2naX6RojK7h
        iiSoCi5T0btkCFX5Ap7MZ7IfuypDs1yNJinuWPgbUojWM/LDtO7pTGAC/xyUB5Y54Hm/F/I/WvvgijmB
        U51vqR7YRvi+UOSZ5ODNUUP0T22Z6/1Sac3GVzkrbX7KSe9Ljl43KHWHOXRjCPFg/Kdc6tJpLf2Lcp7Z
        gXT20OvbcPjaIKI3lpILXfloqjn5C0rcjxFdw+umxS6dFpnhT8XTcMz1CHH7+Xfz9/3KR7P6nPnjJpTV
        BRGtA0lpUNP1smjqbH4Djtf2IRqMbzLAkk5WaVafM09lr8gJZw/icjgujWq6XhZNnb1bhdNnfYia0GcZ
        8C+ySrP6nDmWgIrKNoTz/idpVtP1smgub5RLtwzcnjBXmkI4HC2Ic30fCpJVWla2hyeOtI5x/u4EF7rf
        UO9/zUXfEK47z/LSdDMgdgFg1Scgquk9vgAAAABJRU5ErkJggg==
</value>
  </data>
  <data name="home_161" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANbY1E9YMgAAABl0RVh0U29m
        dHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAIfSURBVDhPfZPfS9NRAMUv9J70F0RP1dN8yG2QOI3V
        EstVD/MlrSiLWiuLfiCN1RhRRKyIUZkrSBqZkRmLWMQMNegHY1v70WqmEdY0m15d9pAvp85tjG2NLnzg
        cM/53C8MJnjOX3SjHLM9rNnqiEjCrIaVzgX35ap9+60IhUIFdtscsDjDcizzE4TZdPx15Uf+fK1qg6kR
        BbbsQvPJISTGc+jyTyqYmztfSYNtpPIjZ1xn8WtxEclxiW2nXiI2No9zvk+oOzikYOad6eiI1O0d/PeR
        TrsDsdEsmo4NIzo6B+ftjzBYg+jzv1Aw846dwTooNTsCpY+0d7hgPBRE+IOE3ZuGfk8Adx8NI55IKJh5
        x44bfftTubLF//eR5eYHmjVtAwilZnDiegrV2/240/8ciWQSPxYWFMy8Y8cNt9WtjyVdsbrloXzzLosO
        TxKrLP3ouR9EPJ7AfC5XAu/YccMtHbqieyCNA5diWGG+h1u9zxB9G8OsnKsIO264pUNXLK3vkcvqb8Lr
        CyASiSI7M/tfuOGWDl2xRNut0TVYEApHMP09W8BzrQvuKx4Fc3HHLR266oc0rjdh6tt0CQ6nC/4nAQVz
        eU9HyTwbG5uQmZwqwXb4CHy9fQrm8p5OXheiYZ0RE18zJbS27cTVG14Fc3lPJ68Lsba2Dqn3aXye+FJg
        02Zz4Z/JXNxxSyevC6HV6k/X1OhQDAe1eZjLezpCCPEbVQB2fVYSGnIAAAAASUVORK5CYII=
</value>
  </data>
  <data name="delete_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAACA0lE
        QVQ4T3WTzUsbURTFbxqNVgKmlARM/EiptEapmSSliBJEzKbYlTu7MV0Wuuiuf4tFcCFoF4LiRkEkGwnS
        akdEcSmKghZx/MBWa5LTdyYz6WTSHnjMQOZ377vnnohbSEm2kJTcbVxw9UJw3iM47RIcP5Pc/lPJWp/V
        SoFRdfRS5jGK2STwcQh43w+8U+9jMfwcDuGox4e9DtG32yRqYWVZsIG33cCn1zUwRp/gLhNEcSiAc82H
        zYgYG2FHEXbGeBz4kAYGHuIu5cWvTKgC/3jpx346it0OD27iHpw8F6wFRbfhLK9tdlZwKTeP0pWBi1EN
        xiu/CR+OaChcGrjZ0fG1RXCfEOgRwcoj5QkNs2dmZ8JUUQHHb7QKTN1fGFhPRE1zaexys+SEbtsz89rs
        TJji0wl/G9Sw266+T5XPol8g14m6KsN4bXa2i1D/gnnmmlSBy2RDldvOmW2xQD6tYau1usCXRlWAs/wP
        JshD/VbP1T4N38N/C0zXqwJMGEPCPXNV7pnZmTDF50xDGT7oFEx5lYmMJxPGkJh7VqtyzsxrszPhg4V5
        zFoFlpoFkw+saDOeZ731Zki4Z67KaRivzc6Ez2Ji/vbZYwWJUtkOqHjqTBhDwj3bsPtYsDEhrv9DPiQB
        xpMJM411gZyZ12bnGtgpxpMJY0i4Z66KbtOwyswVifwB5qsTVJRVplUAAAAASUVORK5CYII=
</value>
  </data>
  <data name="trash_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAACTklE
        QVQ4T4WTW0hUURSGl6JpWaNhRUUXyzLFJrRMsJe0hAR7CAqCHmqegm5SMElRERgFUYSBVEY5VkJZyYCR
        MCHoVCSh+eCQUpLXVNJkKiWZ8fK1tkHZONKBn5+z9/6/c9Za5wjwV5vENpYqziGrePuThM8JQusqwbNM
        qF8iXvcCcbpixDY1MzXsmNgojGZYmMhNhP074JiePXcGrhQxWlRGj72A2vVJlEeKYxpgXMO9SeE0xltw
        Lwrl/UrBm6xb6WGQHQv7NsDFk/jLa7kfbiIBgGGrDH6IE1p2Z+Lv9ujSK9UtlV2VzcTACvpOxeFaHcvt
        EBk0GaM/gAGt+ac9j770GJrjQk3NvFwovJgvVM4VKuYIzyxCVbRQPBkLALTFq90shb0JkLsUsqIhLQR/
        qtC3TiZLqluskHkzAJqWqxXe+G+4JHQGQF2mDNanJtCRk4EvZy3+tFkzhh2JQXpQVyR0luXj3mPFER0x
        eXCq7kYJT3RSrgNCeb6JBABeXzf2CMYKwXsY2reAJ5axtzrOaqG9Qj+oUqGhWHhoDwJwXzNW9C+gWQH1
        0wFlJ4IAaq6q+Y5ChxU+RUCP3n9T+c12GOO+FL537qS9Jpt7eWYtAFB9WW1kF3QnQ38WdKm3Whj3CEPv
        IvnasIYfXcf1aAslR4IAXJeMbYPxrTC8HTo3T+tB8wPhS00Kdw4FAVRdEMeb0tl0NUbhH9ElI1NCr6pN
        8DUJHx8Lzwt0KgeD/EzmqjwvNudZcT49LV4zKtNt0zBTs762V5/s1LDNnP2dQ34BZ1aGSv139vQAAAAA
        SUVORK5CYII=
</value>
  </data>
  <data name="add_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANbY1E9YMgAAABl0RVh0U29m
        dHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAJvSURBVDhPhZLfS1NhGMfPf7K/IKEI6sKbbroJoaKL
        LGhElBKK29o8bi0y26p5dG5ObQnqpm5nP1qbOrcY5VEiJTYdi0rUWa0yVolKDAwlvp3n9XCovPCBLy88
        38/nPRfv4f4fk2jWNofMEh8y4+/QjjoF2z+60RaNfrQl78n0IV9awM7vX/+EdtQRQ6yi7U2Dj9c0+vnN
        yUIS3yufsLyeQ7nyAV9/FuWsIPclg6UfWdYRQyw5is5xdQN8PpaL4v1GAXOlDGY/prGzu6smMjMIaWmM
        dcQQSw6Trzxq1rY+ceDNtxeYLqYhraQwtTKJyva2GsFnx/h8hO2JIZYccrlLfSYpnBuBVEwh/S65l7dJ
        bFQqamz9bYjOhdieemLJIZer7TbJN09gvlRAeWvrwMwt5xDNxjC1PAFyuXNOI8Zfx/GyuIDP6+sHJjGT
        hjvuRTwfA7ncacGIwKsIpMUsVsvlAxN4moB91I3hWREXPBZwp+7fgHc6AK8UhT0ov3PnbTQJt7C4tqbm
        WqsRjQ8sbE+9PdiLvucjIJc7aTNIzWI3XBkRzpSI9oQfjrgPhVJJTb3dgjuBh2xPvZAchinoBrnciVaD
        9kyHVX6WQQjpiJrs6qqaq7abaIsOsX17KsxYcshl/0K1VZ+/6Lkn39qPu2Mh2MbD8E8/Q0/8MVzhIC63
        WWEVB+VOZAyx5DCZ5rhZrznWots822FD/UAvjMEh8EE/GnpcqHMKuO7pgs7XzzpiiCVH0ffmKK/THDHp
        8tVWHjUOO2rdnTjf1SFHYGeNwyZ/lQcxxCra/qky6LRVhibpkL4Jh40G0EmhHXUKpgzH/QHD/4saXUdX
        MAAAAABJRU5ErkJggg==
</value>
  </data>
  <data name="redo_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAACV0lE
        QVQ4T32TX0hTYRjGD2RksHRZSf9bUBBZNvJCq10cuggKkSwjEqqRtRtRQfqzMOrkomEqOMGUQkfQIBGV
        xCBkcKBcWawdGelqpHNeBF7kljazqD1977eztaX2wAM7h+/5ve/7vWfCv9rfPmlklpmR2zaBXc3j2NH4
        CVusH+XsW6NG9dhCsYCOWTnZM4V69xz6J5Fiy+AMDPcDyLjqVVZUKjo1FpMaDtUOfcPTiSgc/l948P4H
        bMp3NA/Po2vsdwJ0oXsKaeWekGBy/4VQZQsL9wSiaB/9ibtDERQ6PiO/NQg9G+FAawB1byIJiNgWxLKy
        V0o8bKS2qXIHC1cMTCPHNh7eVueXNt75IK67OSJmXvNKqy57w9XPvnDAPTaitsIFTWm/kQAyzUxtU2V2
        YSFmPacnaXm5R6+pVMId3nkO2SANY/WpLpkA/AXNTG1TZTWzQGllLulo0wg/v8k2huzjdgi0qr5gFA3v
        5vjM1LZ6XgCg/opp5dkBsaDGxQHaej82H2uBQHu2vJ6F+cVXrL/tS0lwgMltVx+FzNO94iGzzAGCxQfd
        kQYIbF5pq9XPw+zCUtonALttpJ9zcsjaE4+lYutL3Bic5YCdh2tjBVlQS+YPSSJA+nknChsVZJU86d1e
        6gg/Umaw92EQmiondhuuy+rRxUWAjDN9vGWqXNPpw6Xn07H2i5qw5+CVpT9tEgGySjo5gGx9G+HhNRe7
        kVtQHfuQ/icC0KriAHJRiwf78quQl2dK/T8sJgLwVbGqydYV2wiQ2M6SIgCtim47x2COV06yyf4HGye9
        hG0JYXEAAAAASUVORK5CYII=
</value>
  </data>
  <data name="cut_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAACrUlE
        QVQ4T42QXUiTcRTGD0SSZbgu8qOyBlkZUUwrSLrZRUQXXYyupIuQQhIKMqjLxu6KVg2UjF3IkNwEW66y
        9sF0m6kzp7RYoSbq8mvqNn3d1Mwynv5nTl1F0IEDL+f//J7znJd8Ph+8Xq/kdrtV9J/FWmaYJfGBeDwO
        MYTdbi9Nav5ZrGFtLBbjxSCPxyMtLX1FPDaHVo8HjY2NFUntX8VvDM/OzoilMTBLTqfTMjQ4iG9Li8JV
        gt1mg9FoNCSZ9eKZzWpFNBLG3Nws+vv7wCw5HA6FiCUFg0NYmI+JJBJcLhdqamrWTfi7paUZM9Fwoj8L
        2GazScwSADKbzYqGhoZgp7gpEp6GNBOFSwBVVVWBysrKgNX6BtOTExgfG0Hb21awlpmEOxtwm0wmWW1t
        ra6+3oSPgQ8i6hTedXaguvoxhgcH0NPdxaeBNaxNwFxrBtxcer1eITZ3G411GB4aQHtbK3S6R6J13fyW
        EKVWqsF4sVwTKbscjz0woOdKObRaLV43vcK8+jZWHj7BwtVL8cmTOZokuloMThwkRex0rn/07CmMXjiP
        5YpriN7RQq1Wa+7funFv5a4OqHMiVFaOyLkTmFJk+n25tJomuJ/kX/JJeplBcO4gCDP8LCJEL6oSN00V
        kGz55nUES0rwLJ3QlSPeDhPGDpAk9HLy7yb3082EF9tIE8gj5Y9CqsBxwkhxvgi3elr8TAH6iuRozyJ/
        7z5SfVeQaqWQpI4scpMtk2BOF1BSLGAVG7zfRZa1WehohiV0ZAsYTtGVBvYQqFnE5s0pD+6wiGhK25h5
        s0kZOkRYPPabgVIYghwykkQkAw9EG8IFhKbtG9vXum0nWaYLSOLNrF1WkFvoJOJN4n6pdy/xjTCmkU5P
        JPvTQGhk4kfrOrMJn/IIz7eSZNhEyl/fshnMhHDyTQAAAABJRU5ErkJggg==
</value>
  </data>
  <data name="paste_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAACYklE
        QVQ4T32SW0gUARSGT9BTFBHUQyGVXQwiKJAIfXFVMkRLFFHMQITsQdRIWnFVzAuWiRcsFi8RKxkmbZoi
        SilkIpqJmVigIbaKWlmmluYt82tm3DVdtQP/w8B83z9zONJRJLq3JqGnSoiIKCQs7A4hIdkEBt7Czy8N
        b+8kPD3jaL0nPM8UatNEB4gtosKL89v4s+hEYmIlLS1zlJf3kZvbhMHwhNDQXNzcYpnsc2SkQ6hJUblV
        ArVZhVkqJCrKtA52d7+Oi0sUjKZrgupkO8H7CvULFMFvI40NeQQEZBAUdBsfn2Q8PPQa7BFbh5dxCNds
        C5dSMtcKus3CwvRRmL8Ls/kwlUNp54L60ro5nfeGCyUj7LjaZVIelwVd5cLchCKwwkxmUdw2qwH2cyqj
        BUMnHEi3sCXitSaRzjJhZuzICsx4Jjkvfy4TdnPc8AJP8xy70ofYermV7RdrTdJRKvz6fHgFZuwmqc8m
        rMjacQgv41h0NXuDTTj4F7AzuBJpLxGmhhSBFVa3ra/6ZkXWzpKSmUWlS1nRqPKXuwMeIm33hR+WQysw
        n1KJfvxFA4o6Ns/gNOw7X4yoF6YeiQ1m+AbhD4Y1gW3sm1W4dxL2e+cjzQXCeI8isMIMJhJYPKCBGzXb
        0v0dHM9mIU1GYezdwRWYj/H4Gvs1wWbNKtz+FZx0KUhdhjDQLAwqsTQK/fWCLvuDBm/UbEuzsqYTrnpE
        uW3d0yShIkEwxwvlesEtu/e/zSrcMAInz8T8u+nV2RPZjFfaK84lN+GdUI9PXA2+18z4xjzCL9KEf0QB
        /uH5ODtf4S/oyguMIWUSlgAAAABJRU5ErkJggg==
</value>
  </data>
  <data name="sync" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAO
        wgAADsIBFShKgAAAABp0RVh0QXV0aG9yAFVsZWFkIFN5c3RlbXMsIEluYy7JHT52AAAB10lEQVQ4T6WT
        z0sbQRzFF3LIjz8h/8fca9UK2ho1GpvagpKqiEiRVMR6aCUtUgWpVaGIV7VRCDaKmFboYStBi6OCpYfq
        LTGJB3fX7OaSrOO8GIcVcoj08GHevHnvy7KzKzHG/ouy5n2Q3r2pF7hcLlugu4dE1qJ0eGT0560PDS/w
        socgY+0IATq7AiS6sSlnMudmcGhYDHjNNbzo+qaMjLUjhLfV515ZjdBUOm3mcjkWej+uvxoMnnOUicmp
        PLyzVOoqzDPe1ja3GOB0Om3POl6QxeUwVTWNGUaOKarG8oVCkUJpVbmHM6zI+jueE3QlX7ufLH1dkRPJ
        M1M3DKZpWc6lhbt7XTcYskvLYRld6cv8Ak0kkmY2qzOVByoBWXTQlaZn5ujB4ZGZSmeKj1cJyKIzPTNL
        JU9TM/n0eVb+tRMvDrlQtBtUlVPSHKW0RwZZdNCVHA6HreFJIxn/OEn3fu/zN51m/05O2fGfv3eAhzNk
        kEUHXXGND6oeusdCH2js+7YZ391jff0DSpvvaZKj9Pb15+FtxX5cIYOsuMZbAWof1ZG3YyE5svbNbGrx
        ig8JGh7OkLF2hAB2u91WVV1D+FdIHzd6xABoeDhDxtop+4Pch7Jm5TDpGhrRoDGNhQVZAAAAAElFTkSu
        QmCC
</value>
  </data>
</root>