<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="&gt;&gt;buttonAblehnen.Type" xml:space="preserve">
    <value>System.Windows.Forms.Button, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;buttonAblehnen.Name" xml:space="preserve">
    <value>buttonAblehnen</value>
  </data>
  <data name="&gt;&gt;webBrowserEULA.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
  <data name="$this.Icon" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        AAABAAIAEBAAAAEACABoBQAAJgAAABAQAAABACAAaAQAAI4FAAAoAAAAEAAAACAAAAABAAgAAAAAAAAA
        AAATCwAAEwsAAAABAAAAAAAAVbmsALOzswDr6+sA9vb2AODg4ADv7u4A////AOnp6QDc3NwA8PDwAO3t
        7QD7+/sA2NjYAMPDwgDm5uYAyMjIAOTk5ADT09MAzs7OANrl5AD4+PgAvLy8APPz8wBsbGwAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAABgYGBgYGBgYGBgYFxcXGBgYGBgYGBgYGBcXFxcXFxgYGBgYGBcX
        FxcXFxcBAQEXGBgYFxcXFxcXAQEBDwQEFxgYGBcXAQEBFREQCwsLCxIYGBgBAQ0MCgMDAwMDAwMOGBgY
        CAUWFhYWFhYWFhYWFhgYGAUTAAUFBQUFAgQICA0YGBgCAgICAgQIDAgHFhQIGBgYGA4EDBEEBwMDBA8N
        EhgYGBgYGAUWFhYWARAGBhgYGBgYGBgJCQkJCQ8GBgYYGBgYGBgYGAoKCgoQBAYYGBgYGBgYGBgCAgIC
        AgwGGBgYGBgYGBgYGAcHBwcYGBgYGBgYGBgYGBgOGBgYGBgYGBj/4wAA/wMAAPABAADAAQAAwAEAAMAB
        AADAAQAAwAECAcABNXvgAQAA+AMAAPgDAAD8BwAA/AcAAP4fAAD+/wAAKAAAABAAAAAgAAAAAQAgAAAA
        AAAAAAAAEwsAABMLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAADAAAABgAA
        AAoAAAAQAAAAGAAAAB0AAAAaAAAADgAAAAQAAAAAAAAAAAAAAAEAAAACAAAABAAAAAgAAAANAAAAFAAA
        AB8AAAAsAAAAOQAAAEgAAABQAAAARgAAACkAAAAOAAAAAQAAAAQAAAAJAAAAEAAAABkAAAAlAAAAMgAA
        AEEAAABTGhoabGlpaaKUlJTTra2t9q6urvQiIiJTAAAAHQAAAAUAAAASAAAAJQAAADgAAABKAAAAW0BA
        QIR9fX22oaGh5rOzs/+zs7P/ysrK/+Hh4f/h4eH/hoaGqQAAAC0AAAAMAAAAKR8fH1peXl6XjIyMyq2t
        rfazs7P/u7u7/9HR0f/j4+P/+vr6//r6+v/6+vr/+vr6/8vLy/QAAAA6AAAAEl1dXVuzs7P/s7Oz/8PD
        w//Y2Nj/7e3t//b29v/29vb/9vb2//b29v/29vb/9vb2//b29v/l5eX/AAAAPwAAABN/f39o3t7e/+7u
        7v/y8vL/8vLy//Ly8v/y8vL/8vLy//Ly8v/y8vL/8vLy//Ly8v/y8vL/7Ozs9AAAAD4AAAAQYWFhTu/v
        7//S5eL/Vbuq/+/v7//v7+//7+/v/+/v7//v7+//6+vr/+Li4v/a2tr/29vb/7i4uOoAAAA+AAAACgAA
        ACfZ2dnP6+vr/+vr6//r6+v/6+vr/+Li4v/d3d3/1tbW/97e3v/o6Oj/8/Pz//f39//a2tr/AAAAPAAA
        AAQAAAATm5ubX+fn5//f39//2NjY/9XV1f/h4eH/6urq//X19f/19fX/4eHh/8jIyP/CwsL/y8vL8wAA
        AC8AAAABAAAABQAAABFFRUU1oKCgiu7u7v/y8vL/8vLy//Ly8v/y8vL/tbW1/+Pj4////////////9DQ
        0JwAAAAbAAAAAAAAAAEAAAAEAAAAEAAAADLn5+fn8PDw//Dw8P/w8PD/8PDw/8rKyv////////////b2
        9uZHR0c4AAAADQAAAAAAAAAAAAAAAQAAAAcAAAAfsbGxle3t7f/t7e3/7e3t/+3t7f/k5OT/4ODg////
        //+qqqp3AAAAGAAAAAUAAAAAAAAAAAAAAAAAAAADAAAAETk5OUHm5ubz6+vr/+vr6//r6+v/6+vr/9bW
        1v/u7u7MAAAAJAAAAAoAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAcAAAAev7+/mujo6P/o6Oj/6Ojo/9PT
        08C2traGjo6OOQAAAAwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAC4iIiDXW1taqrKysagAA
        ACQAAAAYAAAADwAAAAcAAAACAAAAAAAAAAD//0gA//8AAP/DAAD8AQAA4AEAAMABAADAAQAAwAEAAMAB
        KADgAQAA8AEAAPgDAAD4BwAA/AcAAPwPAAD+/wAA
</value>
  </data>
  <data name="$this.Text" xml:space="preserve">
    <value>EULA</value>
  </data>
  <data name="buttonAblehnen.Size" type="System.Drawing.Size, System.Drawing">
    <value>165, 23</value>
  </data>
  <data name="buttonAblehnen.Text" xml:space="preserve">
    <value>Ablehnen</value>
  </data>
  <data name="$this.ClientSize" type="System.Drawing.Size, System.Drawing">
    <value>556, 473</value>
  </data>
  <data name="&gt;&gt;webBrowserEULA.Name" xml:space="preserve">
    <value>webBrowserEULA</value>
  </data>
  <data name="&gt;&gt;webBrowserEULA.Type" xml:space="preserve">
    <value>System.Windows.Forms.WebBrowser, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;buttonDrucken.ZOrder" xml:space="preserve">
    <value>2</value>
  </data>
  <assembly alias="System.Windows.Forms" name="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="buttonAblehnen.Anchor" type="System.Windows.Forms.AnchorStyles, System.Windows.Forms">
    <value>Bottom, Right</value>
  </data>
  <data name="&gt;&gt;buttonDrucken.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="buttonAkzeptieren.Location" type="System.Drawing.Point, System.Drawing">
    <value>379, 438</value>
  </data>
  <data name="webBrowserEULA.Size" type="System.Drawing.Size, System.Drawing">
    <value>532, 420</value>
  </data>
  <data name="buttonDrucken.Text" xml:space="preserve">
    <value>Drucken</value>
  </data>
  <data name="buttonDrucken.Size" type="System.Drawing.Size, System.Drawing">
    <value>90, 23</value>
  </data>
  <data name="&gt;&gt;buttonDrucken.Type" xml:space="preserve">
    <value>System.Windows.Forms.Button, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;buttonDrucken.Name" xml:space="preserve">
    <value>buttonDrucken</value>
  </data>
  <data name="buttonAkzeptieren.Size" type="System.Drawing.Size, System.Drawing">
    <value>165, 23</value>
  </data>
  <data name="buttonAkzeptieren.Text" xml:space="preserve">
    <value>Akzeptieren</value>
  </data>
  <data name="buttonAblehnen.Location" type="System.Drawing.Point, System.Drawing">
    <value>208, 438</value>
  </data>
  <data name="&gt;&gt;buttonAblehnen.ZOrder" xml:space="preserve">
    <value>0</value>
  </data>
  <data name="&gt;&gt;buttonAblehnen.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="buttonDrucken.Location" type="System.Drawing.Point, System.Drawing">
    <value>12, 438</value>
  </data>
  <assembly alias="mscorlib" name="mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="webBrowserEULA.TabIndex" type="System.Int32, mscorlib">
    <value>0</value>
  </data>
  <data name="buttonDrucken.Anchor" type="System.Windows.Forms.AnchorStyles, System.Windows.Forms">
    <value>Bottom, Left</value>
  </data>
  <data name="webBrowserEULA.Anchor" type="System.Windows.Forms.AnchorStyles, System.Windows.Forms">
    <value>Top, Bottom, Left, Right</value>
  </data>
  <data name="buttonAblehnen.TabIndex" type="System.Int32, mscorlib">
    <value>3</value>
  </data>
  <data name="buttonAkzeptieren.Anchor" type="System.Windows.Forms.AnchorStyles, System.Windows.Forms">
    <value>Bottom, Right</value>
  </data>
  <data name="&gt;&gt;buttonAkzeptieren.Type" xml:space="preserve">
    <value>System.Windows.Forms.Button, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;buttonAkzeptieren.Name" xml:space="preserve">
    <value>buttonAkzeptieren</value>
  </data>
  <data name="&gt;&gt;$this.Name" xml:space="preserve">
    <value>EULA</value>
  </data>
  <data name="&gt;&gt;$this.Type" xml:space="preserve">
    <value>System.Windows.Forms.Form, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="$this.MinimumSize" type="System.Drawing.Size, System.Drawing">
    <value>550, 500</value>
  </data>
  <data name="buttonDrucken.TabIndex" type="System.Int32, mscorlib">
    <value>1</value>
  </data>
  <data name="&gt;&gt;buttonAkzeptieren.ZOrder" xml:space="preserve">
    <value>1</value>
  </data>
  <data name="$this.StartPosition" type="System.Windows.Forms.FormStartPosition, System.Windows.Forms">
    <value>CenterScreen</value>
  </data>
  <data name="&gt;&gt;buttonAkzeptieren.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="webBrowserEULA.Location" type="System.Drawing.Point, System.Drawing">
    <value>12, 12</value>
  </data>
  <data name="&gt;&gt;webBrowserEULA.ZOrder" xml:space="preserve">
    <value>3</value>
  </data>
  <data name="$this.AutoScaleDimensions" type="System.Drawing.SizeF, System.Drawing">
    <value>6, 13</value>
  </data>
  <data name="buttonAkzeptieren.TabIndex" type="System.Int32, mscorlib">
    <value>2</value>
  </data>
</root>