<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <assembly alias="System.Windows.Forms" name="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="buttonOk.Anchor" type="System.Windows.Forms.AnchorStyles, System.Windows.Forms">
    <value>Bottom, Right</value>
  </data>
  <assembly alias="mscorlib" name="mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="textBoxInhalt.Multiline" type="System.Boolean, mscorlib">
    <value>True</value>
  </data>
  <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
  <data name="$this.Icon" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        AAABAAEAQEAAAAAAAAAoMgAAFgAAACgAAABAAAAAgAAAAAEAGAAAAAAAADIAAAAAAAAAAAAAAAAAAAAA
        AADWnnjWmprTkpLTkpLTkpLTkpLTkpLTkpLTkpLLg4O2WFi1V1e4Xl68ZmbBcnKUa21bXmNkYmFPTElM
        S0lZT0qTYl+6YWG0VVWzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG0U1PRj4/TkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLFdnazUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVHeoWXXnp7Tk5PTkpLTkpLTkpLTkpLTkpLTkpLTkpLPioq6YGC5YmKYY2V1X2Fd
        WVtaWlxhX2BlYmJlYF9fWVdsU1G4XFyzUlKzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVHGeXnTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpK/aWmz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHrq1vWn5vUlJTTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        lJR+YmVVV11ZWmBZWl9YWF1cW15qXWCMZWeZYGK1YGG1VlazUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVG7YmLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpK5XV2zUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVH4umXUnYfVmJjTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLVl5d8aGtOTlJJSU1KSk1lZ2xlYWCFY2G/bm64Xl61VVWzUlKzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUlLPi4vTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLSkZG0U1OzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVH9wW7QmmnTnZvU
        lpbTkpLTkpLTkpLTkpLTkpLTkpLTkpLUlJTSmpuLc3ZXVVlOUFVnaW5iX11dUlCCX16kY2K4Xl60VFSz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHEc3PTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLNhoazUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVHksmjao1izhl3XnZ3Tk5PTkpLTkpLTkpLTkpLTkpLTkpLTlJTWmprapaXHoaFhXWBeXmBbWFZTUU5T
        UEtQSkOLWFW3WlqzUlKzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG4XFzT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLHenqzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVHuumrrtmreoFjKmJfUlJTTkpLTkpLTkpLTkpLTkpLUlZXWm5unhYZlX2JTVlpZ
        W15bXF9aWlxZV1hbVVFcU0ukbmm7ZGS0VVWzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVHMhYXTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLBbm6zUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHquW7crm3bo2nYn5/TlJTTkpLTkpLTkpLTkpLUlZXTnJm9
        k3mHcEyRd02YfE6cfk+jgk6siE22jk26kk69lE+7kEuzd1S6YWG0U1OzUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHBbW3TkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpK7YmKzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGvi2Guk3WafXXYnp7Tk5PTkpLTkpLT
        kpLTkpLWm5u1kmrLo17RpFvTp1zVp1zWqFzXqV3Yql3Yql3ZrF7brF7bql3Pm1O3bWK1V1ezUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG2V1fSkZHTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpK1VlazUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGWfH6Fgol8b23Y
        oaHUlJTTkpLTkpLTkpLTk5PQm5e+nWDZrmTdr2LesGPer2PfsGLesGDWq17TqV3dsGDgsWLgsGHdqVu3
        eVe4XV2zUlKzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHJf3/TkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLPi4uzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVHBk5NrbHKIf4C6j47UlpbTkpLTkpLTkpLUlZXHmIrGo2Hcr2TfsGWskWWFeml3c25xcXNyc3ZxcnVu
        bGqhiF/isWLfrV6+hk+7ZGS0VFSzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVG+Z2fTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLJf3+zUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVHXnZ1vZ2uTjJGUeXfWmZnTkpLTkpLTkpLVl5fCloHKpmPdr2S1l2hycXNeXp5d
        W6arqp24tqWlpJSZmIttbG3LoV7frl/Klk+6bGa2V1ezUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVG0U1PRjo7TkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLDcnKzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHWmZmTenyGg4p9b23Yn5/UlJTTkpLTkpLWmpq+lnnPqWTd
        r2SWhWlRTlNgXaxnZKFyb4WBfJ+RjX6trJVqa2yuj17hsGDYo1e6e2W3XFyzUVGzUVGzUlKzUlKzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHGenrTk5PTk5PTk5PTkpLTkpLTkpLTkpLTkpLTkpLT
        kpK9ZmazUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHUlpa9kpJsbXOFfH3AlZTWmprTk5PT
        k5PXnJy6lnHRq2TesWWQgWhgW1ff3b7U0bJGQ59PS76Sj4KurJpqa22hh1/isWLeqlzDkWbLhIS1V1e2
        WVm4Xl63XFy1VVWzUlKzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUlK0VFS/bGzIlJXNmZjXnJzUlZXTkpLT
        kpLTkpLTkpLTkpLTkpK3WlqzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHUlJTYoKBrZWmQ
        io6BbFfNmpDVl5fTlJTYnp63lmnVrGTfsWWUg2hva2eRcamberqoppbn48KUe6y1j+NtZ3+ag2DhsWLf
        rF7EkFLZoqLLjY2gaWWVal2YZVm6Z2W4XV22WFi1Vla0U1O0U1O1Vla2WVm3XFy5X1+8ZmahZmZwZVKc
        fEvCkGXWm5vTk5PTkpLTkpLTkpLTkpLRj4+zUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG3
        WlrTlJTWnZx+a02binbCmV7KlnHZoaHWmZnZoqK1lV/ZrmXhsmabh2haYmWGe4KfkpVucXKRmKGAfnO3
        tZt8fXeTf2DisWXfrWDSm1PRopaTeWSYf1OqhUexhUSqeUO6cmm5bme2amC6Y2O7ZGS2Z2ekZGSRYF9/
        W1tuWFdoXVGxlFmwiUrRmVDQmojVlpbTkpLTkpLTkpLTkpLLg4OzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVG1VlbOiIjTk5PWm5u7lmbesGX3vm69i0upflXJmI7ZqKa3l1vfsmfmtWimjWdgX12emoS0
        rpdxc3qdobZ+f3yjqaVucXOVgGDismXhsGLdp1uvhlufhFDFpGLSpVrjrVzjp1e5iEW4kU26kVRsV1dc
        U1NXVlZgX2Bqamx1dXh7fIF7fIGEcEiEbD+VcDvLmYHWm5vTk5PTkpLTkpLTkpLFd3ezUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVG0U1PLgoLTkpLTk5PXnJywjWzFnlnXqmLHmFLBj0yNakKjhny/nl7jtWjt
        umvCnmVyb29rNTByHxpwT26Qcql6epF7g5JxcXOzkmLmtWfksmXjrV+9i0q1lFjRqmTouWvYq2XMnWDZ
        pVv1wW34xG+GhIaDg4l+foV3d314cHZ+aW6GZGaSZ2eCaEZ6Zj2PcT6XcUHOmpTVmJjTk5PTkpLTkpK/
        a2uzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHHenrTkpLTkpLUlZXIlpShh07Lp2DBllPjr2Hdplqp
        hFOGa0bGomHmtmjvvGvwvGyQf2hwb3JxcXRxcXRwcHRwb3N+d3KqkGzuu2vuumvruGnpsmLWnFOrjWOk
        il7JpGzks2j2u2bsrV3wvXDruGmYc2mXZ2mnaGm3amq8Z2e6YWG4XV26YWGfa1x2ZD2FbT2TczuYckTS
        nJjVl5fTkpLTkpK6X1+zUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHCcXHTkpLTkpLTkpLUlpa5j4uvklHO
        qF3ElVHtuWrapVrAkVN/bVHLpWHotmnxvW3zv270wG7hsmrUqmjZrWnktGvxvm75xHD6xHD5xHD5xG/2
        wW7zu2jprFu5kFLZrGbvvnP7xHL6wmvepGTVo4fCfW26ZGK3W1u2WFi1Vla0VFS0U1OzUlK1V1eraWF1
        Yzx9aT6Rcj6YczyddUzVnpzUlZXSkZG0VFSzUVGzUVGzUVGzUVGzUVGzUVGzUVG+aGjTkpLTkpLTkpLT
        kpLUlZXHlpaliU/RqmDDllPfsmzbqGHBklCUelTPqGLpuWzwvm7xvm7yv27zwW/3xHL7xnX9yHf+yXj+
        yXf+ynb9yXX7yXT7yXP5xG3xuWOqg1K6kVTVpF7dqGDKml/Un5PWm5vSkZG7Y2OzUVGzUVGzUVGzUVGz
        UVGzUVG0VVW5aml1YTx/a0C1kVXTpF/Tn1jCj2XXnZ3OioqzUVGzUVGzUVGzUVGzUVGzUVGzUVG6YGDS
        kJDTkpLTkpLTkpLTkpLTk5PWmpqtiHC3k1G9k1Gyi0+6kVSmgFTGnovIoF/YrWjar2rVq2bQqWLPpmLQ
        pmPSpmPVp2PYqGPWpmDRolzLnljHm1XEmFO+klGsg0nLmoe7kIqsiX2+lYbNmZnVmJjTk5PTkpLSkJC/
        amqzUVGzUVGzUVGzUVGzUVG0VFS8Z2eBZUS6l1zQpmSujFGzik2vh1LZoobKg4OzUVGzUVGzUVGzUVGz
        UVGzUVG3WlrQjY3TkpLTkpLTkpLTkpLTkpLTkpLUlJTXnJy/kYCximGqgVyzinDSnZrZoaGffGGRckST
        dESQcUOMb0GRc0KWdkKRc0aMdVV5Z1GffE6qhFauhVuxiGG1ime8j3HJl4fWm5vVl5fVmJjVl5fUlJTT
        kpLTkpLTkpLTkpLTkpLFdnazUlKzUVGzUVGzUVGzU1O5YGCgdFXLpGScfke0kVLLnla3jlnFlWTHfHyz
        UlKzUVGzUVGzUVGzUVG1VVXOiIjTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTk5PUlpbWmZnWmprVl5fU
        lJTUlZXWm5vDlIq8lIWbgGGbgU2+nGDFnlvNn1fVoVfHlVHGmXrcq6rZoqLXnZ3WmprVmJjUlZXTk5PT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLKgIC1VVWzUVGzUVGzUVG2WVmydmCzklqxk1a7klLh
        smbep1qvh1rEd3e0VVWzUVGzUVGzUVG0UlLKgYHTkpLTkpLTkpLTkpLTkpLTkpLTkpK/amrEdHTJf3/P
        iorTkpLTk5PTkpLTkpLTkpLTlJTWm5vDmI2Yfkyzll3Mq2zWrGTir2Dss2D3uWXtrl3HkV3WoJzWmprU
        lZXTk5PTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLOiYm4W1uzUVGzUVG1Vla7
        bWmZfVajhU6cfUiqh02phUq4jVO7eW67ZGS2WVmzU1OzUVHGeXnTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpKzUVGzUVGzUVGzUVG0VFS5X1+/aWnEdHTJf3/Pi4vXnJyegFujh1C0l13HpWfMolzcqVzutGH4u2X3
        tmHlpVbJkFnOnZPXnp3Vl5fTk5PTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLR
        jo68ZGS0U1O3XFy8cW6he1SefUOviUzEoGPFo2e9ml2wjFGqe1G3bWW4Xl7Dc3PTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpKzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG1Vla2a2aQd0eUe0mjhVCyj1K1
        jk3Fl0/cpVjws2D1tGHrqlndnVC2g0SgglHElYXVl5fTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLFeXmxbmObekmphkqzjlG7k1jKqG7StX/Qs3vHp265llyogUq2fGjXnZ3U
        lZXTkpLTkpLTkpLTkpLTkpLTkpLTkpLRj4+zUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG3WlqpbF+G
        b0OVfEu2l13NpWLYqV7fqlzmrFznrFvkp1fgoVHhoVDRlEmnfUSkf1XXnJzTk5PTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTk5PVmZm+koSkiVXEomPMp2fTrnLWtIC+nHS8m3y7nHvMtIrH
        rHuzlGGkgUu9j23WnpzUlpbTkpLTkpLTkpLSkZHKgIC+aGi0VFSzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUlK5X1+dbligg06+mVrFn2PKqXvbuYvmvYDst2b3vGXqrFjanE3am0zWmEuyfkGieELLh4XKgoLP
        iorTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLUlJTWm5vImZlaUkqSfVbLqmzevYPXt4utemef
        YFWodWymdm2mgHefh3HHroOxlGq0jlncp27YnZzTk5PNhobBbm62V1ezUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUlK6Y2Oje1WfhFmlm5Cuopa+qpLOtpbTvZ7VwKTTt47gt3nts13dn03Ulkm3
        gUGtfUG7bmK2WFizUVG0VFS5X1+/aWnEdHTJf3/PiorTkpLTk5PUlpbWmprVnp6WeXlNSUdfWFF2bGHB
        pXPTt42kZVWQTUOFS0OQYluac2yri4J1Zlt+dW2AgoVVU1CriFTTkn26YWGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG0VVW+amqcekyLb0iVcUGddj+/kkzEmE+8k0y1jkyyi020
        j1K4lVjap1ncnk69hUK0gEG7dV64XV2zUlKzUVGzUVGzUVGzUVGzUVGzUVG1Vla9aGizeHiKcHBUTk1Q
        TUp3bmRoYVpXU1Ofj3K2h26UUEWWZF2GXVlrQT5mPTd7XlaEe3FWSj+OkZZ0dnpZVE2ob2a5X1+0VFSz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUlK4X1+ibGKYdEKIaj6ZdUC1iUawiESn
        gkKif0KhfkOge0OffEOffkWef0e7j03Dj0u3gUGebVS6Y2OzU1OzUVGzUVGzUVGzUVGzUVGzUVG1V1ea
        XF1WWF5WV1hmYVx0bGVdWFdnVVaVemixnHazgnOLTkV+T0qSf4BkamhTT0hmS0VXNC1ePzdrZGR3en9m
        aGxVTkqdYmG5X1+0VFSzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG0VFSvZ2iIbUmfbzeN
        fWuYlZKsppu1rZ2xpZG9rpfKu6HGsZm1oo2ql4KcglyRdEKFbD6yf0RoaGuoYF+0U1OzUVGzUVGzUVGz
        UVGzUVGzUVG1V1eSWltRU1d0dnxxbW9dVleOX2C+bW3Cenm3mn2SU0Wkd2+9paKqpqhqh5JcaWJOQDZN
        KCJAHhiPdWB0bnFjZmtfYWRWUE2ZYV+6YWG1VVWzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG0
        VVWwamWMbz+YeESZhmaqpJq6uLXQysPk1sHky6njwJDhtXfir2fkrV/bpVrIlEq7h0LEiEOTdV2zZma0
        VFSzUVGzUVGzUVGzUVGzUVGzUVG0VFS4YGBqT1JNTlJhUlWrZma4Xl62WFi8ZmbFjYiWY1ShdW21m5Z2
        fYBGZWpEYlSRk4tnSkQ3GRS5l5XNn59pYWRcXmNZXGFCPz6LXFu6Zma2WFizUlKzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVG0VVWybWOjhU+ujVKzlFe9nF3Uq2Xtu237xnP9xG39xGv+xmz/yW3/x2z+wWb3uF7q
        qlTPk0i9g0e9aWm0U1OzUVGzUVGzUVGzUVGzUVGzUVGzUVG0VVW4Xl6vX2C5YWG2WFizUlK1VVXCcnLX
        oKC1j4GQXFKoh4CakouBjIdZXVNfX1VFJx5DLSncuLjbpqbOnJ1iWl09QERbX2VVUlB2Xli9eHi9aGi2
        WFizUVGzUVGzUVGzUVGzUVGzUVGzUVG0VVWzbWSjhE6vjlSyklXFn13esWnwvnL+y3n/yHP/yXH/zHL/
        zXL/zXH/yG38vWLurlfYmkzDiEW8ami0U1OzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUlK0VFS0VFS7
        Y2PHenrRj4/UlZXZoaHgubOvjX+ihXyYjYaHfXhyXVZbSEJHMy15c2+rkY/YoKDVmZnLmZlUT1JfY2lw
        b3GDe3SNeHDWnp7TlJSzUVGzUVGzUVGzUVGzUVGzUVGzUVG0VVW2bWahg02vjlOykVXAm1vRpmHdr2fr
        unDyvm/1vmz4wGz9x2//zHL/zG/9v2TwsVnfoVDIjUa7bGS0VFSzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVG4XV3EdHTPi4vTkpLTkpLTkpLTk5PVmZnbqamgi415cGyBb2p7aWRrVlJrW1l/foBtbGtjW1bUoJ/U
        lpbVmJilgoRgYGV8foN6eHpxamash4XUlpazUVGzUVGzUVGzUVGzUVGzUVGzUVG1VVW3bWiVe02Id1t/
        cFaliVjLpGHQp2LXrmnhtGzXq2a7l2DFnWD1wWz/ym78v2Pyslnjo1HOkUm6bmC1VlazUVGzUVGzUVGz
        UVGzUVG2V1fBbm7NhobTkpLTkpLTkpLTkpLTkpLTkpLTkpLTlJTGfHx0YWNjYWBva2a+pKLhtra2lZVX
        WVxUVFVNSUWOaWbUl5fUlZXXnZ19bW99f4eRk5yIgIKYfXvVl5ezUVGzUVGzUVGzUVGzUVGzUVGzUlK3
        XFyjbW1ydHeUlZidm5mCgICgi2jPp2TUrWuxl210c3WCg4d+fX51bmfHnl/9vmTys1rmp1PSlEq7cl62
        WVmzUVGzUVG0VFS+aGjKgIDSkZHTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLBb2+lYWJfZGphYWJf
        WVKsjIrZo6PVnp5ZV1xvcXZ4dXN1Z1+1cG/QjY3UlZXTm5uEcXRydHuCfIG1jY3UlZWzUVGzUVGzUVGz
        UVGzUVGzUVG0VVW3Z2d4dX27wsze4OKhk4Gji3CTiYKqkWi4m2l4e4S4vsaDdmVgRyhrWER5cmzXpFz0
        s1rpqVTWl028d1u4XFy7Y2PHenrRj4/TkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLEdHS2
        WFiVXV5UV11oaW1+eHKYfHjWnJzXnp5oY2d9f4aOkJh8eHmBZGG8ZmbKgYHUlJTWmprGlJTHlJXVmJjT
        k5OzUVGzUVGzUVGzUVGzUVGzUVG2WFieam2fp7Pr8vmuoY52USObbjmIZUCGfneBeW+ttsTS09J2WjVP
        ORyMZDaHblWUfGL0s1rqqlXZmk7EiWXTlJTTk5PTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLIfX2zUlK1VlalYGFaW2BsbHF9fH+Gc3DWm5vVmZmOeHp7fYWaoKyWlp6Ifn+xZmW0VVXEdXXT
        k5PUlJTUlJTTk5PTkpKzUVGzUVGzUVGzUVGzUVGzUVG2WVmRbHDDzNvr9P5/ZUJfSS04LSJ2TiOPgnl2
        eoHM1ue/v7p8XDIsJR9lTTCHYzykmJDusFrsq1XcnU/HkGPXnZ3Tk5PTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLMhIS0VFSzUVG0U1O6YWFqWVx0c3iLjpeQgIDWmprUlZXMl5hmXmJ7foiLjJWR
        iIuyZma0VFSzUVG/aWnSkJDTkpLTkpLTkpKzUVGzUVGzUVGzUVGzUVGzUVG2WVmTbXDK0uHx+P+ReVp9
        Y0BVQjB7VCqypp57fYTW3+/g5Oh7XTZ6Xjp0UCmMcFLMxsDhqFrtrVbgn0/Ij1vYn5/Tk5PTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLPioq2V1ezUVGzUVGzUVG1V1etY2RoW19vcHipi4zVl5fTk5PV
        l5e2dHR4XWBqX2OOZGa5X1+zUlKzUVGzUVG6YGDQjIzTkpLTkpKzUVGzUVGzUVGzUVGzUVGzUVG1V1ej
        a22wtcL3+v7k39mmjnGielbGs6K+ubltbnLK0d/7/f/c1cynkHWjh2zm39rNycjtsFzurlfiolHIjlLZ
        oKDTlJTTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLRjo64XFyzUVGzUVGzUVGzUVGzUlK1V1fFe3vC
        kZLWmprTlJTTkpLTkpLJf3+4XFy5YGC3Wlq0VFSzUVGzUVGzUVGzUVG2WFjMhYXTkpKzUVGzUVGzUVGz
        UVGzUVGzUVG0VFS6ZmaHf4be4ev+/v/+/v77+vn49veUj5Cah22SlqDs7/f//////////////v+9rZz3
        t1zxsFjkpFLKjk3ZoqLUlJTTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLSkZG8Y2OzUVGzUVGzUVGzUVGz
        UVGzUVGzUVHIfHzUlJTTk5PTkpLTkpLTkpLRj4+1VVW0U1OzUlKzUVGzUVGzUVGzUVGzUVGzUVG0VFTI
        fHyzUVGzUVGzUVGzUVGzUVGzUVGzUlK3XFygb2eGhYrNy9Xy8PXe2+GbmJ+2nHLhtWyBe3Wdnqjr6fH+
        /f/7+fy/u8HXqmr0tV3ysVnmplTMkE3ZoqLUlJTTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLAbGyzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVHNh4fTkpLTkpLTkpLTkpLTkpLTkpK+aWmzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG2WFiga1uYf1KGe2x9eHaKgne3m2zds2nq
        vG7lunKWinZ9foWSkpqOiYrMpnD9wWbToFvzslrpp1bNkU7ZoqLUlJTTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLEdXWzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG0U1PSkZHTkpLTkpLTkpLTkpLTkpLTkpLKgYGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUlK7YmLIfn6ZeHOfg06ykla7
        mVrJpWHYr2ffs2jou23Rq2r8y3XqvHDarmrvuWf/ym/DnmHeqV/0s1rqqVfRllnYoKDTlJTTkpLTkpLT
        kpLTkpLTkpLTkpLJfn6zUlKzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG5Xl7TkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkZG2WFizUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG4XFzEc3PPi4vTkpLU
        lZWviYlzYUSxkVa7mVrLpWLasGnBn2fou2zYsW2rjmH3xXH5xG3+yW/GpGOIdlz9vmP1s1zpqFnRl2XX
        nZ3Tk5PTkpLTkpLTkpLTkpLTkpLMhYW0VFSzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG/amrTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLBb2+zUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG2V1fBbW3MhYXT
        kpLTkpLTkpLTkpLTlJTVnp5XUUx4ZkW4llnNpmKehmHLpWjqu271xXTLqG5yZlZ+blZpYVSAdF/wwG39
        v2X0s13kpVfTnILVmJjTkpLTkpLTkpLTkpLTkpLPi4u2WFizUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVHFdnbTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLNh4ezUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVHSkZHTkpLTkpLTkpLTkpLTkpLTkpLTk5PWmpqlhHBaVk1ST0tlXlSli2LhtGroumzzw3P8ynj7yXXe
        s2znvG//z3P/yG35u2PsrlvVnF3XnpzUlJTTkpLTkpLTkpLTkpLRj4+5XV2zUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVHLgoLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpK5XV2zUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVHTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLUlZXTnJqggVOpiVPFnlzWq2HdsGTi
        tWboumvvv271wm76xG39x23+xWv6vmbtsV7YoVvVn5HVmJjTkpLTkpLTkpLTkpLSkZG8ZGSzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHRjo7TkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLE
        dXWzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLVl5fLmZKo
        hVi6k1XKoFvUqF3Zq17drmDgsmPmtGPsuWPvumPttmDkrVzQnlzRnY3WmZnTk5PTkpLTkpLTkpLTkpLA
        bW2zUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG3WVnTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLQjIyzUlKzUVGzUVGzUVGzUVGzUVGzUVGzUVHTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTk5PVl5fTnZq4jnCzjFPBl1XMn1jUpVraqlvbq1zaqlzXplrNnlnLm3XVn5rVmJjTk5PTkpLT
        kpLTkpLTkpLFdnazUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG9ZWXTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpK8Y2OzUVGzUVGzUVGzUVGzUVGzUVGzUVHTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLUlZXWmZnVnpvKmYbGmXbIm27KnWy7lWjBmHTRn4rWnpvWmprU
        lZXTkpLTkpLTkpLTkpLTkpLJf3+zUlKzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVHDcXHTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLHe3uzUVGzUVGzUVGzUVGzUVGzUVGz
        UVHTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLUlJTVl5fWmprXnJzYn5+ujY+y
        kpLYnp7UlZXTk5PTkpLTkpLTkpLTkpLTkpLNhoa0VFSzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVHJfn7TkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLSj4+0VFSzUVGz
        UVGzUVGzUVGzUVGzUVHTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTk5PVmZm2kJGojY/Yn5/UlJTTkpLTkpLTkpLTkpLTkpLPi4u2WFizUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHOiorTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpK/aWmzUVGzUVGzUVGzUVGzUVGzUVHTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLUlJTEkpNbV1pZVVOSdHDWmZnTkpLTkpLTkpLTkpLRj4+5Xl6zUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG1VVXTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLKgYGzUVGzUVGzUVGzUVGzUVGzUVHTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLUlZWYenxkaG54dXVvZF7XnZ3Tk5PTkpLTkpLTkZG8ZWWz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG6YWHTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkZG2WFizUVGzUVGzUVGzUVGzUVHTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLUlJS7jo9mZWp/foWRe3zWm5vTkpLT
        kpLTkpLBbm6zUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHA
        bW3TkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLCb2+zUVGzUVGzUVGzUVGz
        UVHTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTk5PVl5fGk5S3
        i43UmprUlZXTkpLTkpLFd3ezUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVHGeXnTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLNh4ez
        UVGzUVGzUVGzUVGzUVHTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTk5PUlJTTk5PTkpLTkpLJgICzUlKzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVHMhYXTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpK5Xl6zUVGzUVGzUVGzUVHTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLNhoa1VVWzUVGzUVGzUVGzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUlLSkJDTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLFdXWzUVGzUVGzUVGzUVHTkpLTkpLTkpLTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLQjIy2WVmzUVGzUVGzUVGzUVGz
        UVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVGzUVG4XFzTkpLTkpLTkpLTkpLT
        kpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLTkpLQjIyzUlKzUVGzUVGzUVEAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
</value>
  </data>
  <data name="$this.Text" xml:space="preserve">
    <value>frmAbout</value>
  </data>
  <data name="labelUeberschrift.Size" type="System.Drawing.Size, System.Drawing">
    <value>455, 31</value>
  </data>
  <data name="labelUeberschrift.Text" xml:space="preserve">
    <value>labelUeberschrift</value>
  </data>
  <data name="labelUeberschrift.Font" type="System.Drawing.Font, System.Drawing">
    <value>Arial, 12pt, style=Bold</value>
  </data>
  <data name="textBoxInhalt.TabIndex" type="System.Int32, mscorlib">
    <value>3</value>
  </data>
  <data name="$this.ClientSize" type="System.Drawing.Size, System.Drawing">
    <value>507, 348</value>
  </data>
  <data name="&gt;&gt;buttonOk.ZOrder" xml:space="preserve">
    <value>1</value>
  </data>
  <data name="&gt;&gt;labelUeberschrift.Type" xml:space="preserve">
    <value>System.Windows.Forms.Label, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;labelUeberschrift.Name" xml:space="preserve">
    <value>labelUeberschrift</value>
  </data>
  <data name="labelUeberschrift.Location" type="System.Drawing.Point, System.Drawing">
    <value>12, 9</value>
  </data>
  <data name="&gt;&gt;buttonOk.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="labelUeberschrift.TextAlign" type="System.Drawing.ContentAlignment, System.Drawing">
    <value>MiddleCenter</value>
  </data>
  <data name="&gt;&gt;textBoxInhalt.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="&gt;&gt;labelUeberschrift.ZOrder" xml:space="preserve">
    <value>2</value>
  </data>
  <data name="&gt;&gt;labelUeberschrift.Parent" xml:space="preserve">
    <value>$this</value>
  </data>
  <data name="&gt;&gt;textBoxInhalt.ZOrder" xml:space="preserve">
    <value>0</value>
  </data>
  <data name="buttonOk.Text" xml:space="preserve">
    <value>ok</value>
  </data>
  <data name="buttonOk.Size" type="System.Drawing.Size, System.Drawing">
    <value>106, 29</value>
  </data>
  <data name="&gt;&gt;textBoxInhalt.Type" xml:space="preserve">
    <value>System.Windows.Forms.TextBox, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;textBoxInhalt.Name" xml:space="preserve">
    <value>textBoxInhalt</value>
  </data>
  <data name="textBoxInhalt.Anchor" type="System.Windows.Forms.AnchorStyles, System.Windows.Forms">
    <value>Top, Bottom, Left, Right</value>
  </data>
  <data name="&gt;&gt;$this.Name" xml:space="preserve">
    <value>frmAbout</value>
  </data>
  <data name="&gt;&gt;$this.Type" xml:space="preserve">
    <value>System.Windows.Forms.Form, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="textBoxInhalt.TextAlign" type="System.Windows.Forms.HorizontalAlignment, System.Windows.Forms">
    <value>Center</value>
  </data>
  <data name="$this.StartPosition" type="System.Windows.Forms.FormStartPosition, System.Windows.Forms">
    <value>CenterScreen</value>
  </data>
  <data name="buttonOk.Location" type="System.Drawing.Point, System.Drawing">
    <value>389, 305</value>
  </data>
  <data name="&gt;&gt;buttonOk.Type" xml:space="preserve">
    <value>System.Windows.Forms.Button, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
  <data name="&gt;&gt;buttonOk.Name" xml:space="preserve">
    <value>buttonOk</value>
  </data>
  <data name="buttonOk.TabIndex" type="System.Int32, mscorlib">
    <value>2</value>
  </data>
  <data name="textBoxInhalt.Location" type="System.Drawing.Point, System.Drawing">
    <value>12, 43</value>
  </data>
  <data name="labelUeberschrift.TabIndex" type="System.Int32, mscorlib">
    <value>0</value>
  </data>
  <data name="$this.AutoScaleDimensions" type="System.Drawing.SizeF, System.Drawing">
    <value>6, 13</value>
  </data>
  <data name="textBoxInhalt.ScrollBars" type="System.Windows.Forms.ScrollBars, System.Windows.Forms">
    <value>Vertical</value>
  </data>
  <data name="textBoxInhalt.Size" type="System.Drawing.Size, System.Drawing">
    <value>483, 256</value>
  </data>
</root>