<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="KannAktuelleNewsNichtLaden" xml:space="preserve">
    <value>Unable to load news. Please check the connection to the internet.</value>
  </data>
  <data name="AttributeBearbeiten" xml:space="preserve">
    <value>edit attributes</value>
  </data>
  <data name="NewsWerdenGeladen" xml:space="preserve">
    <value>loading news...</value>
  </data>
  <data name="CheckeNodeX" xml:space="preserve">
    <value>checking node {0}</value>
  </data>
  <data name="AIMLDateiLadeFehler" xml:space="preserve">
    <value>File \"{0}\" is not valid and has not been loaded.\n\nDetails:\n{1}</value>
  </data>
  <data name="about" xml:space="preserve">
    <value>© 2016 Springwald Software und Lizenzgeber
Alle Rechte vorbehalten

Dies ist ein Produkt von:
Springwald Software GmbH
Alter Eistreff 36
44789 Bochum, Germany

phone: 0700 / 777 464 925 *
email: info@springwald.de
website: http://www.gaitobot.de

Dank an:
Dr.Richard S.Wallace (der Erfinder von AIML)
Thomas Smits
Dirk Starke
Manuel Loof
Dietmar Smolle
Thorsten Dolczewski
Christian Bartsch
Robert Beyer
          
GAITO® ist ein beim Deutschen Patent- und Markenamt eingetragener Markenname.
Alle Rechte vorbehalten.

Diese Software verwendet "Jint - Javascript Interpreter for .NET"
Copyright (C)2011 Sebatien Ros, lizenziert unter MIT Licence (MIT)

*max. 12,4 Cent pro Minute aus dem Festnetz der Deutschen Telekom (Stand Juni 2008)
            

           
</value>
  </data>
  <data name="ueber" xml:space="preserve">
    <value>about</value>
  </data>
  <data name="NewsFehlerSeiteInhalt" xml:space="preserve">
    <value>Unable to load news.</value>
  </data>
  <data name="AnwendungLaeuftBereits" xml:space="preserve">
    <value>Program is already running.</value>
  </data>
  <data name="KannErsteSchritteNichtLaden" xml:space="preserve">
    <value>Can´t load first steps.</value>
  </data>
  <data name="ArbeitsbereichName" xml:space="preserve">
    <value>Workspace "{0}"</value>
  </data>
  <data name="OeffneDatei" xml:space="preserve">
    <value>opening file {0}</value>
  </data>
  <data name="laed" xml:space="preserve">
    <value>loading</value>
  </data>
  <data name="EULA" xml:space="preserve">
    <value>&lt;!DOCTYPE HTML PUBLIC "-//SoftQuad Software//DTD HoTMetaL PRO 6.0::19990601::extensions to HTML 4.0//EN" "hmpro6.dtd"&gt;
&lt;HTML&gt; 
  &lt;HEAD&gt;
	 &lt;META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=windows-1252"&gt;
	 &lt;META NAME="Generator" CONTENT="Microsoft Word 97"&gt; 
	 &lt;TITLE&gt;EULA &lt;/TITLE&gt; 
  &lt;/HEAD&gt; 
  &lt;BODY&gt; 
	 &lt;P&gt;IN THE FOLLOWING YOU ARE GIVEN THE CONTRACT TERMS FOR YOUR USE AND
		PURCHASE OF SPRINGWALD SOFTWARE &amp;#150; THE END USER (LICENSEE OR RATHER
		CUSTOMER). YOU HAVE TO AGREE TO THESE TERMS BEFORE THE USE OF PRODUCTS. PLEASE
		USE THE DOWN-BUTTON OR THE SCROLL-BAR ON THE RIGHT SIDE FOR READING THE WHOLE
		TEXT! &lt;/P&gt; 
	 &lt;H2&gt;END USER LICENCE AGREEMENT (EULA) &lt;/H2&gt; 
	 &lt;H3&gt;1. SUBJECT OF THE CONTRACT&lt;/H3&gt; 
	 &lt;P&gt;Subject of the contract are the software program, the instruction manual
		and other written or digital material which are located on the data medium
		without any different marking (named in the following as "SOFTWARE PRODUCT").
		Through the purchase of the product you only get the ownership of the physical
		data medium on which the SOFTWARE PRODUCT is recorded if such a data medium has
		been given to you. A purchase of rights of the SOFTWARE PRODUCT for itself is
		not connected with it. This is also valid for the case if you have purchased
		the SOFTWARE PRODUCT without data medium via the Internet (ESD- or rather
		Instant-Download-Version) or if you have received the SOFTWARE PRODUCT in
		bundle with another product (OEM-Version). The SOFTWARE PRODUCT is protected in
		the scope of copyright, trademark and title protection. If on the data medium
		furthermore is located software of other manufacturers which is not immediately
		integrated in the SOFTWARE PRODUCT (for example Shareware, Freeware and Demos)
		it is subject to special terms of licence which are shown you during the
		installation of this software.&lt;/P&gt; 
	 &lt;H3&gt;2. COMMERCIAL USE &lt;/H3&gt; 
	 &lt;P&gt;Special versions of the SOFTWARE PRODUCT (for example Lite- and
		Private-Version) exclusively permit the use by private persons and for
		non-commercial purpose. For all other use, especially in connection with the
		offer, purchase or sale, the extolling or sales promotion of goods or services
		and for all events with a commercial purpose or during use by tradesmen has to
		be purchased a licence for commercial use of the SOFTWARE PRODUCT (for example
		Pro- or Enterprise-Version).&lt;/P&gt; 
	 &lt;H3&gt;3. EXTENT OF USE&lt;/H3&gt; 
	 &lt;P&gt;SPRINGWALD SOFTWARE guarantees you for the period of this contract the
		simple, not exclusive and personal right (in the following also called as
		"licence") to use the enclosed copy of the SOFTWARE PRODUCT on each computer.
		If you use in your work a Desktop- and a Notebook-Computer and the SOFTWARE
		PRODUCTS are used on both tools exclusively in change and not at the same time
		both tools are valid in the sense of the licence as a separate computer.&lt;/P&gt; 
	 &lt;P&gt;Special versions of the SOFTWARE PRODUCT (for example
		Enterprise-Version) guarantee you an extended licence for the use on several
		work places on each business location. The number of these work places is
		particularly identified in the SOFTWARE PRODUCT. &lt;/P&gt; 
	 &lt;P&gt;You are allowed to produce one copy of the data medium on each medium
		which is exclusively determined for the purpose of data backup. A further use
		and handover to third parties is not admissible. The original data medium and
		the backup copy have to be kept on a safe place. It is particularly forbidden
		to give, to rent out or to lend SOFTWARE PRODUCTS. You are entitled to handover
		permanently your rights for the SOFTWARE PRODUCT from this contract &amp;#150;
		under the condition that you do not keep any copies and for the case that you
		handover the SOFTWARE PRODUCT with all its components, media and all updates
		and the receiver agrees to the terms of this contract. If the SOFTWARE PRODUCT
		is an update each handover has to contain all earlier versions of the SOFTWARE
		PRODUCT.&lt;/P&gt; 
	 &lt;P&gt;If you have purchased several licences of the SOFTWARE PRODUCT you were
		handed over a corresponding number of data media or you have received a licence
		document which shows the number of the allowed installations. In each case the
		additional licences are to be handled just as a normal licence of the SOFTWARE
		PRODUCT. Any extended rights of use are not valid.&lt;/P&gt; 
	 &lt;P&gt;Concerning SOFTWARE PRODUCTS with components which are particularly
		provided for handover to third parties (run time-licences or so called
		"redistributables") you find in a special document or in an online-help an
		exact description of the extent and the kind of the allowed handovers of these
		program components of the SOFTWARE PRODUCT. This description is an additional
		part of the contract.&lt;/P&gt; 
	 &lt;H3&gt;4. WARRANTY, UNDERTAKING&lt;/H3&gt; 
	 &lt;P&gt;The SOFTWARE PRODUCT is delivered according to the state of current
		development and before the delivery it undergoes extended tests and quality
		assurance measures of SPRINGWALD SOFTWARE. Within 30 days after the date of
		purchase SPRINGWALD SOFTWARE free of charge reimburses a) for defect data media
		if here is responsible a sales partner b) for the case that the SOFTWARE
		PRODUCT is generally not usable in the sense pf the delivered description. If
		SPRINGWALD SOFTWARE is not able to produce the warranty both parties have the
		right to rescind the contract by reimbursement of the purchase price to the
		licensee. Details in brochures, adverts, documentations and similar papers are
		only descriptions and do not contain an undertaking of properties. The
		undertaking of properties demands for an expressive written agreement. This is
		also valid for price quotations or details for the release of supplements and
		extensions.&lt;/P&gt; 
	 &lt;H3&gt;5. LIABILITY &lt;/H3&gt; 
	 &lt;P&gt;The responsibility for choice and the consequences of use of the
		SOFTWARE PRODUCT and for the intended or achieved results lies with the
		licensee. A liability for damage of any kind (unreservedly included are damage
		from missed profit, loss of business information or from other financial loss),
		which comes into being because of the use of this product or because of the
		incompetence to use this product is particularly excluded. This exclusion is
		not valid for any kind of damage which has been caused if done intentionally or
		by gross negligence on the pages of SPRINGWALD SOFTWARE. Claims which are
		caused by inalienable statutory regulations for product liability are also not
		affected.&lt;/P&gt; 
	 &lt;H3&gt;6. AMOUNT OF THE LIABILITY&lt;/H3&gt; 
	 &lt;P&gt;The amount of the liability is in each case restricted to the amount of
		the actually paid purchase price.&lt;/P&gt; 
	 &lt;H3&gt;7. DATA PROTECTION &lt;/H3&gt; 
	 &lt;P&gt;Reference to &amp;sect; 33 BDSG: The customer data are saved but they are
		not handed over to third parties and are not used for any other purpose.&lt;/P&gt; 
	 &lt;H3&gt;8. SPECIAL RESTRICTIONS &lt;/H3&gt; 
	 &lt;P&gt;The licensee is forbidden&lt;/P&gt; 
	 &lt;UL&gt;
		&lt;LI&gt;to hand over or to disclose the SOFTWARE PRODUCT and written material
		  or to third parties (except a so called Test-, Shareware-, or LITE-Version of
		  the SOFTWARE PRODUCT with a corresponding marking which is allowed to be
		  transmitted. That also includes the passing on to magazine CD-ROMs or to
		  Download-Archives on the Internet), &lt;/LI&gt; 
		&lt;LI&gt;to change the SOFTWARE PRODUCT, to translate, to redevelop, to
		  decompile or to disassemble it or to create works which are modified from the
		  SOFTWARE PRODUCT (except for the own use in the scope of chances of the
		  SOFTWARE PRODUCT) and to change or to delete copyright notes or brands and
		  trademarks, &lt;/LI&gt;
		&lt;LI&gt;to translate, to change or to duplicate the accompanying material or
		  to create other works which are derived from the written material and to change
		  or to delete copyright notes or brands.&lt;/LI&gt;
	 &lt;/UL&gt; 
	 &lt;H3&gt;9. PAYMENT&lt;/H3&gt; 
	 &lt;P&gt;If the SOFTWARE PRODUCT was purchased directly from SPRINGWALD SOFTWARE
		the right of use of the SOFTWARE PRODUCT begins only by the complete payment of
		the invoice amount. Invoices are due on at the latest within 30 calendar days
		after date of invoice (in case of no other agreements). When the time limit has
		expired the customer gets into default in payment and he has to pay an interest
		on 7% over the basic interest rate of Deutsche Bundesbank according to &amp;sect; 1
		Diskontsatz-&amp;Uuml;berleitungsgesetz (D&amp;Uuml;G).&lt;/P&gt; 
	 &lt;H3&gt;10. DEALERS&lt;/H3&gt; 
	 &lt;P&gt;We deliver the SOFTWARE PRODUCT to dealers exclusively for the purpose
		of resale on behalf of our own and for our own account to the ultimate
		customer. In this respect we grant the dealer the right to leave to the
		ultimate customer the SOFTWARE PRODUCT in accordance to the extent of use which
		is described above. For this a special agreement between SPRINGWALD SOFTWARE
		and the dealer is necessary.&lt;/P&gt; 
	 &lt;H3&gt;11. RIGHT OF REDEMPTION AND PLACE OF JURISDICTION&lt;/H3&gt; 
	 &lt;P&gt;On principle is in force the chance of return of the SOFTWARE PRODUCT
		with reimbursement of the purchase price up to 14 days after the order (date as
		postmarked or rather invoice). After opening of the sealed data medium or
		rather the installation or use at the computer a right to exchange and return
		is excluded because there is no chance anymore for the licensee to prove not to
		have a copy of the SOFTWARE PRODUCT. The same is also valid for the purchase of
		software without data medium (ESD- or rather Instant-Download-Version). The
		place of jurisdiction is Bochum. The right of Federal Republic of Germany and of
		the European Union is valid.&lt;/P&gt; 
	 &lt;H3&gt;12. MISCELLANEOUS&lt;/H3&gt; 
	 &lt;P&gt;If one or several terms of this contract or one term in the scope of
		other agreements should be or become ineffective the effectiveness of all other
		terms or agreements is not affected. Ineffective or missing clauses are to be
		replaced by effective clauses which are nearest to the desired purpose with the
		help of corresponding statutory regulations.&lt;/P&gt; 
	 &lt;P&gt;Bochum, in July 2008&lt;/P&gt; &lt;/BODY&gt;
&lt;/HTML&gt;
</value>
  </data>
</root>