<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- 
    Microsoft ResX Schema 
    
    Version 2.0
    
    The primary goals of this format is to allow a simple XML format 
    that is mostly human readable. The generation and parsing of the 
    various data types are done through the TypeConverter classes 
    associated with the data types.
    
    Example:
    
    ... ado.net/XML headers & schema ...
    <resheader name="resmimetype">text/microsoft-resx</resheader>
    <resheader name="version">2.0</resheader>
    <resheader name="reader">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>
    <resheader name="writer">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>
    <data name="Name1"><value>this is my long string</value><comment>this is a comment</comment></data>
    <data name="Color1" type="System.Drawing.Color, System.Drawing">Blue</data>
    <data name="Bitmap1" mimetype="application/x-microsoft.net.object.binary.base64">
        <value>[base64 mime encoded serialized .NET Framework object]</value>
    </data>
    <data name="Icon1" type="System.Drawing.Icon, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>
        <comment>This is a comment</comment>
    </data>
                
    There are any number of "resheader" rows that contain simple 
    name/value pairs.
    
    Each data row contains a name, and value. The row also contains a 
    type or mimetype. Type corresponds to a .NET class that support 
    text/value conversion through the TypeConverter architecture. 
    Classes that don't support this are serialized and stored with the 
    mimetype set.
    
    The mimetype is used for serialized objects, and tells the 
    ResXResourceReader how to depersist the object. This is currently not 
    extensible. For a given mimetype the value must be set accordingly:
    
    Note - application/x-microsoft.net.object.binary.base64 is the format 
    that the ResXResourceWriter will generate, however the reader can 
    read any of the formats listed below.
    
    mimetype: application/x-microsoft.net.object.binary.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
            : and then encoded with base64 encoding.
    
    mimetype: application/x-microsoft.net.object.soap.base64
    value   : The object must be serialized with 
            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter
            : and then encoded with base64 encoding.

    mimetype: application/x-microsoft.net.object.bytearray.base64
    value   : The object must be serialized into a byte array 
            : using a System.ComponentModel.TypeConverter
            : and then encoded with base64 encoding.
    -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
  <data name="save_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAACcUlE
        QVQ4T42TXUjTYRTG/9ddGV11012XXan4/TG/0MZ0Y1sim3Pq/AoVi5ZaQyYmqSg6Y9ZMMRotSSLLaoTZ
        JDWNjG7qJrrxpgZB0ofQQvr1vu8QJEZ24HDgz3me57znPH9NRmPjplckDQ0vGR3dobV1U1WXK6Kq2Xxb
        VYNhCr3eT0XFNEbjjFeBZUjw2toutbUreDxbNDWtqVpdHVbVaLyhqgSXlo4yORkTZNfZA2+7XBusr4PD
        sYTT+YyqqvvY7WEsllkqK+8qZYvllgKXlAwJAgTZBGVlV7Y1Cfb7Y6yucmD83IWvMQgEoKZmVhCOodXV
        rTA+/oPl5XhTYPPf+XEHfL7vYsKgmGYYzelcZmTkC4uLcYJEsacswR++wdBQVDxtmqKiATSH4ymDg58I
        h+PNiVT357tt6O19Ly4zQUHBJTS7/Qn9/VssLMQJ9sffyhL86jN0db0WpxwjP78XzWZ7rBjn5wWisww6
        CqAlE1ypUH0CTh2HimNw8igUHoacQ7S3R8QVBsnN9aDJk3k8b5mbg99d5QeCf+mOCMM9EAvsIyenG03e
        ubv7DaEQor6grW2J5uZH1NffU6eS25YLk2+WY0tlmy1IYWEPWVnn0azWO7jdGwSD/BdYKlut18jL6yQj
        4yya2Ryio+M5MzMI5llMpmnRHBDu8wuAT5hlmOLiy0KxD52uRyzuovg+QGbmGdLS2tBMpptKec+esVgs
        YXq9DwWxT42t010gNbVF5Gk08VdFpLK0p/A20Wg0YbrdITGJV42dnt5OSkozycmNEa28fCpJr78aMRgC
        ytth4ahE6XQOk519To0tlSU4Obkx6Q/BkLqmATkyiQAAAABJRU5ErkJggg==
</value>
  </data>
  <data name="arrow-back_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAABf0lE
        QVQ4T6WRTSjDcRjHn6ODeW3U2ixWO+xEkkYIzUVRdnCQaEp5mUyzJjUhkiLM1qb4UyQHjjuRg5sUIYS4
        KIqDg0TU157fXloas/nWc/j//s/n+7wRgH9FVIkfXjokD/2Q8YtCsH5XC3LFaRAJe9EOcvJT9NZDEZb4
        CMLuzzY431uh2chC7poc6uUM5CylQ7mQCoVbBsW8DNmzyaDBYIff4d6zMow/GTF8XwfHXS0GbmvQf1WF
        vosKmE9KYD4thXFPB7L7DaLBnUfFItFyXg7bdbUwYKORh3phPPncCMO2BmTjDhKAp1+aoPepQFY28PgN
        drSYeW0W0F/gubcW6LbkIEtoBCcdFvnyMPbYAOtlZUzY9WGCcj0F1BO5xCmS8jdVArTfGNB9rEf7QSFM
        +wViYTwzt82VGU5bSQJ1BQ1YwmSCJN1qdhimIX8Cn4q3zQvjmbltrsxwhz8iJUxGSdIuZorK4TvHI2Hi
        IEntTg1UTkTCxE5S4M4xxMmJB+gLRS282Bo1UgEAAAAASUVORK5CYII=
</value>
  </data>
  <data name="delete_161" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANbY1E9YMgAAABl0RVh0U29m
        dHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAKzSURBVDhPZZBpSFRhFIavURZKbkwuTTaTKQVC94cM
        5EIuaJpmaVqZLRNJtFhR2mKLCJla0ki0GVGGWmplJSrGSDqW0eTWrbQNS4KKRKnPNasx3u755v7IPHC4
        5573eb67CP/Xr9PeeovB2zRe4IN/m3aUKdjkGsz20gzneEljJasx/qoK+D0yoWlHGTHEKpq1+o5qNP3H
        tGys4QTQ1wG8KQbasoGWTGvTTDs5I4ZYchRdED6le0rDNQeAD/eAR0cwIj/pa+ZCfN4/lzfNQ0UreUYM
        seRwuTtVrf+SGwR0XgGMaejNC8D7XWqpZ8+cYMrf7VCLPekL2M+nRUB9htxpnCWHXKErxcM0WLYduH8Q
        389GQ763nizXi83u4utUHzbWWiF/Qh1+FG9EvyGCs+SQK7QnuwG1h4CKLXiZokXHejeR5Ja1rqKU4sVG
        zWVAVw1GLydB0qsZMcSSQ67wOF4FlMqLonWgmeSHK1SiOVnLRppLgedVGD6XAPMaD/YkcZbIeZklh/MP
        YlxguZgAFK4CzcZoZ7Ep0ZMNmeS//uwOhgyxaIpzZY0xLvzNiCGWnObE2RBqI50wUBCLP/L3N8S7wRiv
        ZoON14D2Wxg4FQXjchWri3LicnWkYzAxxJJDrlAZPtPUuU+H0fxwdO/2BasxAK3lYLlhqF7mzO5GOHCZ
        Smalj2mLOEsOucKNUHt9dZw7erJCMH4yEDgfi2/Hg3B7qQMrD7PnckmIXfD1UDvJvMGTM8SSQy4/+eqS
        GZJxkw/eHvaHJdsPXVu1uBnpAHnPm+bunfN5Rgyx5HCZqjBouuZCoC2rStKiba8fejNEWDJ9gSxr00w7
        yoghlhxFt9YZ/2kaw+Kp0qVwR1QmzUP9NnFC044yYohVtMmVp5uiz9XZmHJ0NsgPsAVdqWlHmYIpJQh/
        AV+WC3uCIvKNAAAAAElFTkSuQmCC
</value>
  </data>
  <data name="W95MBX03" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAO
        wgAADsIBFShKgAAAAIFJREFUOE+dkAEOwCAIA3m6T/Nnzi6pqQwNzKzRVXqw2WUNqLWGvb7GmM8UjmUI
        w1DvvQ5RAAQrDWCInbGXptCuVHoKhiNAaoobgN4RoGFI/4H3QoiGqdcOvA/AF1HaXT1ENogv0sIIAn8B
        /CV1A2xT+MuMNgAOf4Tw+gy+VGVm9gAos5jHA3Xd9gAAAABJRU5ErkJggg==
</value>
  </data>
  <data name="undo_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANbY1E9YMgAAABl0RVh0U29m
        dHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAIHSURBVDhPldNPSJNhHAfwtz9UWEEkBXVKwkNkZLQK
        M4od7OCtg11kBGVTk+XMDoOwMjGdreYGyxqbutwgmSWT/qCEplOzkSDaP/QghHSKLkrXX9/vw9PbNqPo
        hQ/83uf5fn/b5TXwrNHWwjrYADmwBbZqnHnGO+aYN5/0wnarzV7kCMW9zkhiytmtYa4OxLxWW2URMtt0
        h4vUk+vsejppKT1z+qI3HL0aey5/Y/d1Pyo4WbIPPf6oWpJ/JZKQ/+EI9n5Gb49eYhyq7eyTbHWRfnHF
        hxTO2fflt+4G0d3FBRZH8DG2/lYbjosntSDe6UWFc310ICNT0xFdRreAC47U3O+RbPU9CXFPfJQ7U/NK
        06t3qzLoHlcLXPFB/NXVbr58I63JD8r1Z+NS7e/MgO4ptaA1+V6ah2dM1/pHpGFgzHznXOULi/1e0OR4
        GOOCE1xg8c8uSeNgSqnr6pOKtoBS1R5Sfr2naxmd4YKjXHCwcejt67aJT3IpEJHzLe3/5Op9IeiMolvI
        BXsLS0orHyx8+3F7ZFouuP1yrsnzR7xjhll22OWCXDhWXFZ+wz+39D38ZUXcyVlpSAxn4BnvmGGWHd01
        NsJuKAZbhS/0xJOa/8pwOp7xjhmdZYdd9WVtgp2wH6xwFuxwWePMM94xwyw75lfJYT1shh2QBwfgsMaZ
        Z7xjhll0DOMnm3HKev8Sw0UAAAAASUVORK5CYII=
</value>
  </data>
  <data name="documents_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANbY1E9YMgAAABl0RVh0U29m
        dHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAEwSURBVDhPlYzfK0NhGMfPP7VRpMgFKVKSJCVJkiT5
        sVqOhSm22OTH3dRyI5FcaJbV/BHIjTTmbGbYOdu5O1+et87jqOO0963PW0/P8/koAJTY7r4a3ztAHSQU
        xyNXfDs/S9M0YVnWv0S347hMpRHZinGEA7S8fax6sr4Zha4bODu/QHgjIiIcWF5Zc5WchFbDyGsFwWHy
        iOYEBwLBJVfJyfHJKYJq6A8cmJ1fRLVWk2JuIfAbmJqegW4YUpDDgfGJSXxVKoJs9sYT+44cDoyMjqH8
        8SkFORwYHBpG6b0suM5kPLHvyOFAX/8Aim8lKcjhQHdPL7RCUZC6Srti723I4UBHZxfyr5oU5HCgta0d
        uZe8FORwoKm5BXf3D3jKPdcF3ZLDAb+/UfX5GiADOQCUb0DoJJXygZ4BAAAAAElFTkSuQmCC
</value>
  </data>
  <data name="arrow-forward_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAABiElE
        QVQ4T6WRWyjDYRjGX5lDC82pmZpTGokiaYWQQwqRwgXlghIKOS/aZk2GC3KBJFbURClulDtSroRCyCGF
        SOFGuaAe3/tPLjQb89Rz8/X+nu89EIB/2aGkgmECDZLVabE9MaSc8kW8TQUy/xDCj46snlag5SgdmplA
        kMFOiNzqCc1KKDTLKkQvKRFlC0bkXBDCZwPAcOJCKBr3tajfTUHkpD9I9y2E4Yn3Wlgey9D/UArjbRF6
        rvLRfZGL9tMsNB+moe0kE/qbQpRuxUE56gNqp72vEP6ZYf6h6SAVrccZ6DzLhu4yD/rrApjuiqXgoecK
        GO5LoF1Tw8/iBWr+DOG2ucAZPPJShbHXapjEZ2GLCrgb3EANtEc8M7f9G3j8rQZ9T+VQzMtBveK8dWQl
        XhjP7BLM4m13nedIp+I91O0ko3I7AcUbMchYj0DSaghyNmPtw5IGxINZ2CRsEOYCnXCXcAfB2yiTZrYP
        OxFv2aPXHd4zsr/DLOlMoguXYJYU0OAE5iLXDfoA7v2ztR39i7AAAAAASUVORK5CYII=
</value>
  </data>
  <data name="copy_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAABt0lE
        QVQ4T4WTUUhTURjHT/jUQy8JUiGIPVQPPSTDl0BZKJnBilUQoYE+TCFdBDJkKEgPSx9igyDWfLkEK6Ug
        SI3AURIoiqmYSFDhkmQzUnGwSGPgz+14bx3PXesPH/fj++7//zsP5wjAVg+nd7g39pvOV2naX6RojK7h
        iiSoCi5T0btkCFX5Ap7MZ7IfuypDs1yNJinuWPgbUojWM/LDtO7pTGAC/xyUB5Y54Hm/F/I/WvvgijmB
        U51vqR7YRvi+UOSZ5ODNUUP0T22Z6/1Sac3GVzkrbX7KSe9Ljl43KHWHOXRjCPFg/Kdc6tJpLf2Lcp7Z
        gXT20OvbcPjaIKI3lpILXfloqjn5C0rcjxFdw+umxS6dFpnhT8XTcMz1CHH7+Xfz9/3KR7P6nPnjJpTV
        BRGtA0lpUNP1smjqbH4Djtf2IRqMbzLAkk5WaVafM09lr8gJZw/icjgujWq6XhZNnb1bhdNnfYia0GcZ
        8C+ySrP6nDmWgIrKNoTz/idpVtP1smgub5RLtwzcnjBXmkI4HC2Ic30fCpJVWla2hyeOtI5x/u4EF7rf
        UO9/zUXfEK47z/LSdDMgdgFg1Scgquk9vgAAAABJRU5ErkJggg==
</value>
  </data>
  <data name="documents_161" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANbY1E9YMgAAABl0RVh0U29m
        dHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAEwSURBVDhPlYzfK0NhGMfPP7VRpMgFKVKSJCVJkiT5
        sVqOhSm22OTH3dRyI5FcaJbV/BHIjTTmbGbYOdu5O1+et87jqOO0963PW0/P8/koAJTY7r4a3ztAHSQU
        xyNXfDs/S9M0YVnWv0S347hMpRHZinGEA7S8fax6sr4Zha4bODu/QHgjIiIcWF5Zc5WchFbDyGsFwWHy
        iOYEBwLBJVfJyfHJKYJq6A8cmJ1fRLVWk2JuIfAbmJqegW4YUpDDgfGJSXxVKoJs9sYT+44cDoyMjqH8
        8SkFORwYHBpG6b0suM5kPLHvyOFAX/8Aim8lKcjhQHdPL7RCUZC6Srti723I4UBHZxfyr5oU5HCgta0d
        uZe8FORwoKm5BXf3D3jKPdcF3ZLDAb+/UfX5GiADOQCUb0DoJJXygZ4BAAAAAElFTkSuQmCC
</value>
  </data>
  <data name="add_161" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANbY1E9YMgAAABl0RVh0U29m
        dHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAJvSURBVDhPhZLfS1NhGMfPf7K/IKEI6sKbbroJoaKL
        LGhElBKK29o8bi0y26p5dG5ObQnqpm5nP1qbOrcY5VEiJTYdi0rUWa0yVolKDAwlvp3n9XCovPCBLy88
        38/nPRfv4f4fk2jWNofMEh8y4+/QjjoF2z+60RaNfrQl78n0IV9awM7vX/+EdtQRQ6yi7U2Dj9c0+vnN
        yUIS3yufsLyeQ7nyAV9/FuWsIPclg6UfWdYRQyw5is5xdQN8PpaL4v1GAXOlDGY/prGzu6smMjMIaWmM
        dcQQSw6Trzxq1rY+ceDNtxeYLqYhraQwtTKJyva2GsFnx/h8hO2JIZYccrlLfSYpnBuBVEwh/S65l7dJ
        bFQqamz9bYjOhdieemLJIZer7TbJN09gvlRAeWvrwMwt5xDNxjC1PAFyuXNOI8Zfx/GyuIDP6+sHJjGT
        hjvuRTwfA7ncacGIwKsIpMUsVsvlAxN4moB91I3hWREXPBZwp+7fgHc6AK8UhT0ov3PnbTQJt7C4tqbm
        WqsRjQ8sbE+9PdiLvucjIJc7aTNIzWI3XBkRzpSI9oQfjrgPhVJJTb3dgjuBh2xPvZAchinoBrnciVaD
        9kyHVX6WQQjpiJrs6qqaq7abaIsOsX17KsxYcshl/0K1VZ+/6Lkn39qPu2Mh2MbD8E8/Q0/8MVzhIC63
        WWEVB+VOZAyx5DCZ5rhZrznWots822FD/UAvjMEh8EE/GnpcqHMKuO7pgs7XzzpiiCVH0ffmKK/THDHp
        8tVWHjUOO2rdnTjf1SFHYGeNwyZ/lQcxxCra/qky6LRVhibpkL4Jh40G0EmhHXUKpgzH/QHD/4saXUdX
        MAAAAABJRU5ErkJggg==
</value>
  </data>
  <data name="App" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAO
        wgAADsIBFShKgAAAGltJREFUeF61W/dzXedxxR+RH5JMxpmJJ5M4E814ktiOE6uxSGJB73i94vWH3nsv
        RHmoDx0geiUBEJ0ACRaABEixgr1KtCyJoqplqpEnuxcCjXLRREWjMwAB3L3f7rd79ux373MpKbmCnxsH
        DlxEYOAwPD0HfzZIpaOi99oOeF1eXivt/r8EgJGVdR6+vkMrbvYy4IUXF18WvddWERl5eo3dny0ApaVX
        UFZ2Vfi69LOUlLNrIv4yyMw8t+Ke24VcPrbG5ksHgB2urFxAWekMCvJHUF19FeXlV1/8Pjp6bdR/KmJj
        Z1bcezvIzj4vavOlA8C7XlQ4AZNOj8ykZCTEO1BTc23F39hs06I33y6s1uMr7G4HdvsJUZsvHQDe7YQ4
        J2wGLdVYDORaO+rqrq8oBYfjCnS6o6IL2A5UqvEV994q+P4BAeKk/LNkQGnJKQT5S+DtG4iQiBJUVa3M
        AEZR0SXRGtwOmFRX290KUlPnRO0xfhYOqKpagKN4GEUFHWhouCEERexv8/MvrLsTW0Ve3ruitjeC0XhM
        1BbjJwWAHWTiq66+htra64LTRQV99LsB1NffEMpieQksB7dHH58joovZCpKSzoraXQ9FRZc3vN+2AsCO
        cXrX1C8gq2oOUVUzsNWcgaVuDobyCUQ4p5HXcIl+f00IzvJusBzJyT+9PYaGnhS1uR7i42dF7SxhSwFY
        anXVdVcQUjgK7wNUj5XTCGg4h6DWq5B03YK0+zak9DWo7ToC688jsmYe1Q0LcDoXRLMhKuqntUedbnKN
        rY2g0WxMvlsKADtfUjWPgMwO+JaOQ9I4B1nHVci7b0LZdxeagQfQHPkAmrFPoBn/DMrhJ5D2PoK0/iIK
        6i4JWSMWBG5rYovaCIGBI2vsrAcx6bsamwaA07i69gq8UxvhndtJTp2GqvsatIfvQj/0HszjH8J27DPY
        TnwN66nvYJ19BvPp59BPfQd5/xNImm7A8WMmrLbtcFyGVrv99lhYeGmNLTFERp4SvX45XHgRYhczeNe4
        lkMyWuHqF4R97l7wkeugzm+F6chDWMj58JNfIWbuB0Se/R6WwXuwH/0Twi8A1jOAZuJbSPo+gax2AbX1
        10W7A7dHmWx77TEtbX6NHTFsxa6Lv/8wpeK0qM4uK7tCrL6A/Z7+2K2PQWDFKNRt56HKqoehdR62iY8R
        cfpr2Drm4acPg58tCT4qIxQRKbAe/xy6Y88gG/wz/FsfIY2ySCwLGNttj8wfYnaWYz3puxouy//BI2d4
        +ClhQWyE0z839xB2qcLh5+hHUNUE1OS48fAtBDdMwzLxIaz9N6Aq7Ebo6adUAt/CfvY5NC0zkEblQDP1
        DNLBrxHY8RF0lZfWKMTl4A3Yans0mY6J2lgOu31r8ntFAJbAxKFWT1DPPYPwmCq4pTfAj3o8B0DVehbB
        h27AMHgfVgqAqfsSIud/QMjRj2Hqo8CMfQb7HKCqPwlF5z0EcQZ0fkzZcwmNjSySxBfM4B6/lfbIilLs
        +iVsJH1XQzQAS2AjEnMjvJKdsMRnISomEdFpebDUjMA4eBc2cjps/I+IyqugQSgR1SUlyMstREjbOein
        n1G3uIKgga/g1/4R3BzncfDgzXVV4hK2Qlze3kcEAhW7nrGR9F2NdQPAOyGVjiDY3oi8zCwszJ/H159/
        iYe376HBWYOw2mFYhh4iMj4VHfV1+OKjx8Cz5/jh2+8xPXEMpq7rkA39GYH9X8Kn7QO4Fp/bUgAYFsvm
        7ZFrXOxahtE4JXqNGNYNANejXj+OrORsPH54D3j+nP5/jm+/+x5P//INiovKYM2uRmNFCZ5+9glW/Pcc
        qO2dhHTkKQIOfwGvlkdwLZzbcgB4dzcTMAkJZwRbqzmFuwoPTZwlG5UT+8c21g2Av/8QrOZmnBg6jOff
        PcXN+48QWtgGv7iDODg4g7GxKYTZrLh/iQr+2fc4t3AHkcXtsGQ349b9D3Dm7HlIDz+Bf9+n8Dz4HrwK
        zxAHcABWLng9cK9nUl69LnaK1xYfT53AcUJo08ttsszm65TKMQQFjYgSK5f2UtdbNwB8qBliLcXDy+Tg
        N18gKNaBNzSJ+PUOX/ybTzzq2waQkRiPz+5fw4ePHuC3snj8jzwOv/KIgFfIARyfIZnc8RB+vU/g3vAA
        kqIzwtC0XhcQQ17eBXJ2JZmx81pNLxQSA2JC7DiQ3ykoVbbLXyMihqGUxUCjMEGvLYRCMbYiE5TKcUEh
        Lt1j4wBYHLh97iSe//kxduiS8coeBf7plf/GL92iEJtWhNS4KPzp2jmMHzuG/5Am4B//+d/xa1cd/qDJ
        RrGzBUGHP4Vv9ydwr7sDTfHshm1wPWRk/LU9clrzoYg00ISY8AhUFuYjJaX4xeDlrDwHtVyPnKR4lB/I
        R36Og8p44MX1PBavPlhdNwCcJlZTPQbbG/Dtl49R2NSHX3pG4fe2Gryhy0F0Uhbssak4NdyLy1cu4zdB
        UfiH37vjt9oD8LVlQ51QJrRA366P4VZ9E7rcU0KqbjcAjMTEM8Iu+vkNQaVshVIShFCLBckJiQgJzxKO
        4PhMIi6mEJmUlT2N1aivqEByUg50+n7ihCNCd+F7M28s5451A8AXBQePIDEyBudOTOC9B/eQWtqEkPxm
        pOWWwuDogrFmFBnxMZiZGoUuKh3/+rYSuwLMsITFQtpyXQiAT+dHcK28Bkn0UaE2NZoJxMXNCmS12tGN
        EBFxStgUuawcMn8fWI0GhMUkISbBidraa6RYryNYYyDSToSzuBCxMQlQaVMpA44KbZGdXuSLGZSXzb6Y
        UtcNwFIbtFqbER0RBmd5Gapq6ijl0mDIb4S2/QLMvVdhrexHJKVjdnoakhKTEGyLhKJ+FlpSgUGDX8K7
        /QPsLbsMedjEioclnJYGwxTZm9uwpy8Hqzu1iuYQrYK+quAVqEDegR40N98UJLvUPxBRoXaE06YpgiNh
        DxlCQcFFoTxqaiiIoRmIJ19SE9Lo50PCz9cNAIPbicE6Atf4ctrBHPiFJCMgtxWqlnmo2y/C2HcdFhqK
        9N3XoaycgLLuNCzTNBsQb2qO/YDAgS/h2fw+9jjehdI2LqSw2H2Y6PjkmE+LxBxfApdQQsIMNKoIKFUa
        6M12HGyZwvDwQ3JmmLjBH74+Pti9xxV6YyGR4uIRPXOP3ZqIbMqO2lIH0lJyEJ/oFEhzkwCQFrAOwzW9
        Cd6Fh+DrGICk5jhUbZdIDt9FyPhj2Ke+hGXqa1iOfwM7jcJh5wA7QUuDUGD/5/Bouo+3Cs5Aa5kQbUmr
        IZONCum+NI8sgdOV67yz8zYKKAMtIbEw2VOhNcbDy8+MQIkZKUnJMFus8JNo0NB4FRUVRIyU6hlprdAp
        lUhPSiCeiIPeFIrM7B7h95sGQGsdhFtGM3w4ADQPyBpOw9h/D2FTnyN2/jnCaewNPQvB8bDz9D2BR2H1
        5A+CBthffQO7c07CYDoqsLjYfZaDS48DxVjOF7yTTU03MTj2AMkFh5CQeRBZBU7EJGbDTxaGHe9I8Mp/
        vg17eCyKHN3C3MEBq6qah5e7D4waBULtIYiIT0dITAGVzKJ+2DQAGusA3DOb4VXQB/8y2qHaSei6qfYn
        niB85nuaAJ/BTLDMPIeVAmGZBc0BzyEffQof6gDvlF7A2+mT1IImNw0A308uJxGjOETtbkwgPQ4Il2JY
        2Aly6jpSi4bgJS1GSnYH8kuqkX0gFd6yQPgqFPjFv+zGr17ZidHRO2hru4262nchC1Jj1xuvQqeQwMPL
        FwHyKMTETBL/TAr2Nw2AznQYr9sPYFeME/qsKlS3dGFodBwn5y5i+tojdM4/QvHx9xFNc0Hwofeg6H2E
        oNbbRHxnsCN7AjtzTkEWWUpsvLizYvdh8O+UylHaLRO83Fzh66Wia7qFgPBCmc1zCk7DR1MBa2QTKmqG
        kJIYBZPuLfiodyGfanvX3mD8zd/9DuWVYyS6zkOrMkIjl0IlDcRrr++ARJpPdsZfBJbvu2EAeFGG4EPY
        Y83B7+wNMCcWoKTciZq2HtT1DsHR2o/Kvkk0Tcyhqn8GBQeHkFbZBWlaLXZEOPCaJRO7kgdgNhigUHZs
        mAGs8CRBJfD39kRCVASRVij8/WSUDYXUiaYQG3cCidUj2O1dAnt0Cw62TqKjrQsl2SaojVL89g03/NO/
        uuJvf/EGlJFFCLVFwKzXUBAUcPXwg0JVJYgozqbl990wABwlhWIUastBcsiJ10w5eCOyCm/lDmFXzmHs
        SGvHjuSD2JnUhJ3xjdiZ0IDdSQ14O7kerkUT2Fd0Em+mkh631lM9j1MAxO/D4ADIpNWQB/ghwN8PUpUe
        OksE/ANk8PMNhiGuHFG1/QhPG8Rut3zsdU9CSnIJcYsW77h7Y/c+PV75L3/87nU5tFozkuOiYTHosdfN
        Fyp1nSCJxTJwwwAwuAxMpinsj6vFO/Z8vBlajtej6rC/5Bjcnaewv/Qo9hcOwTV/AF5FRxBQPorA9ltw
        q7+DHZmTeDOF6jpyQmD3pbQTA7dIrsuYmEGEhOTB1c0He109oLVFI0hloOD5I6yoAbbsYez2KINMW4FA
        WRZee9OM372qh588HqHxGXh9rx8qHIWIoyxy9QmE3t6xrvOMTQPAi+bd841vRmBGA4prWlFxsA8lXVOo
        GH4X9ZNX0HJ8AYUjVxA78gCywSdwbbiLPdRiePffTOyF2jYh1B3b44XwgliXc7vj6Y2HnqVWx62JFRsL
        m9jYCrxNPd0zQAGVJQrhrdMooPv46lqw07UYO/dlQqIuhiW8Gmn53ZDoI4kfkpCZlgIPb1/45HQjkexy
        6q/2awlbCgAvOMBWB7f0RgRVTUFDrTC+cw75Y7eRMvkB9COfQHeUZv+ej+Faewv7a25hn/Ma3kwawI6Y
        g9Rz55GWNvfC0a2Apeuixj+DvV5B8EssgaVrHumT95A/QrI3rhe+ygZYIjtgjWpDdEobQrMbkN43C1NZ
        PwILj8DWfge1dYsTKIssFlurp8tNA8DguVph6cROexb2JZAWrxyGuvU85J03IO26D2nPB5D0/An+7Y/g
        2fSAxM9D7Cm7hF2J7fBNbhGeHy4NH9vBkvjJKJmCb24LNAdPIbj9HML6riDlyDVE1E4hoeYo4msnkHfk
        HOJ7ZqGiVr0vtQXWoknUUq/njFpuk2U3y2+W4ZyNWwoA16fePIy3o4uxJ74MHqwLigbgSrXvXnkaAa13
        oBz8HKojXyOw6zE86u5iVzpFOq0RmeWnFp8sLVvEdhEbexoaWz/2xNVgb1YnPAtpWi2dgK1jDslDlxE/
        eJF2exbSijHsTe2AIWFYkL8snsTsLYEF1poAiNUoy1LeRUlKPTyymykDaFJspRsePAdp5x1y/FPoJr6B
        avgp/Fr/iMDisyitexd1NKEtHVaILWAz8KkQPzni9smDmS30KHziqeMk1mN/7iFoGikjmk9DVj0JzwOH
        4RnfBR3NLqwdwsO39hDVhc/Yxcho+R+xZOR6LHCexP4kJ2QVg7B0n4O25xqUJH6Ug8QBY08h63sCmWMW
        tY1/fTr8U53PzX0XEslfj8Q4C43WCeKCKrhRBr6TWAvX7C7szeyEd8EobLETFKzFiXOp3W7lnaIXzwZ5
        oVwv/CCTF887x0TETrDzeWUnkVl2FKqUGrim1kBJ9SepPw1/Ulz+TQvwLJ9FXNUMurrvCIefnIJsh4eR
        7QaCa3S1YGHHlFEDCCqhYJT2w6tkAvqBhwhqv4eg7EOIjj4ltOzl13h5HRHOAsTusQQhAOwop3iK4xhU
        ef2QpnYhJG8Q1XWXhQFERQJnVxhJzYhS7AwtxpskjXeEO7AjqgJv0VffyAPwDI6FG/2dX0YXJJl9UOX0
        IzhvCKFFR5FdeVYIIgeVA7IU3NWLYfBjr9V6gXeUDzl9IxqhpVH87aRaeDmOwK9+nth+BNry0zQmz4rq
        DA5kTs76b5W48M7wToXk9MKzdIQwCXcSNT6OcfhQa8mvn4Gi8QwMvTdgOnSLZv8FqDsvQt12AZq2i4TL
        0LQvQNNxA8q2a8QLlxBAC/OtmYU3CSVPYvA96T3Irp5HXvEEEnN7kFU+RZl2/sWpDC+Ez+q4HFc7wGBe
        Cg4+il26VEgrx6Gl+3oe6IMrbZIX7X4WZVx6+voPQ7iL8cHIaucZLpyeFRWzcM9thbLrErwrTsIycB+q
        jtvwKJmGT1wZ1B0XYBn7CDYagW1TX8B27EvYp79C2KmniKSJMPrMM8ScfY5oQtTcc0SefYaIs98jnMDP
        CzVjX8ArvUsIqrxlAcqOu1BUz6G0YbG8Fp8DTIgunsGpbTSN4Q+qSLxhToavYwiKlisIaLgCXdEJodz4
        3SGxa5fAp8Fib5q6cN3nF43RTh2CrIOMUNsyjT2hie4WvB3H4WlNhoofiA5/COskO/8VbMf/DBPVn6Hr
        Koy9N2E+8kgITAg5G3LqO+GrnWCb/gsME1+RRvgIXsVj0PfcRPjUZxS472E+8R2l8z1kNy/AmngCau04
        kd6IoBiZ8HjXmf05rXlOUBm78QdNJF4zJuI1Ksc/hDuxP7KOev0ix3AQ+Rox55fAvX9NAPjisoozcMtu
        grJ9njJgGqpD7yOo7S68MzrxljkLqoMzMAx/APPRz2A5+jkMycUI48OF0NBFhIQgnP4dFp0ES3EXzBOf
        wjz+KYyjj6Ee+AjetdegKaDRNq8FlpazMAw+gn7iL5D1foKQyc+FvzOSQ8bgShgN7VQKI0LKs4TlGUI4
        Cjc34FVtFF61ZuJ/w0uJk5xw1l5eoTEUivUl7xJCQ0+sDADXIBOgpeAwAonV1V3X4eWcxf6iaewwFSAh
        qxny+mMwDL1PTj2Brv4E7PYw/Po3Zvz9P4bB5h6CzrBiOOLiUJIej3AKiJqYOnjoA+gGHkHR+z725k8i
        oGwIWiox89iH0HUTX9Sdg6T1JqzTX1O2fIOsjCzkpqcjMykJidHRiAqJgc2YBL02i4JRgrcMaXhVH4fX
        QotoIKtEWfW7KziEYTav/zrccvAp04oAcB3qKyagO3yPUvkp9tGCfZM6Ueg8i7aOm5BU0o4QLxjIqeCC
        NsgUSmRU16Oy7wjiwkMx3FSHhOQktHY2UwBsUKaUk/PvQX34ISTtdyHJOgQPGqTULaeptC5DSkHxb38f
        u3PG4OoYFbjB399CKS+l9PeHkuxbTCbEREYiNSFewDshNOlZMvC/IeVIrZoX1rzcecZW30vm0lp6y8SF
        RU5t3TW4mpMQlVcDedUJhFbMCe2PNQH3dEX5EHR9N4W+a8iugU4dhLT4LJSXNCCMHG5yOhCelIKaoRFE
        JyZAmVwKXT8JpN778K65TNMjKbrYUngnO/F2Zhd2ZfZjZ2wXjGHjCLaNQWkaFiZOFjLBwcP0tQUKpYM4
        IRn+ATZ4ygwIpAFnb+5heFRdQk71RSLutfI6PX1e1GExMM9we6QAXBUOEI06MwrziuFvSUVx9fkfezW/
        IkO/q6Be27NATlEWpJch2GxHZ6gD46TNK9o6cOL9P6GHZoT3i4aQHGyFMr0a6v6HkPfcJ/I7JQSxoGAe
        OmMjZKZyBOqc0AUv1vcS6fGuMPh7Fj0sfVmS81GYXt8EL10IDWK10BWfEN19Bmt7MWfXA7dHoQuUlEwi
        3GpBYkImysqPC7qAb8BgfgitoN3pvkQBuAdDKgVJosTU3fsYuHQVDTvfwtQ+d6QVlaC6pw9WswkKIlQ1
        ZYC06x70jpPIyJgXmJwdY53OzrFAERMuy8G/Z2a3WI6hvOwMnKQdeD1M3KudXwI7JWZrPbhwmifElSIv
        PQtWe+Kad305GLEVU9B2XoD20F0YMyvg7eaJHpkSTdpgZBIhNiSkIqnAgfKeXlgoAPKiPiip/v2bb0AX
        TwxODi/dkJ3azPHViIubebEhYju/HHo9DUYiNtaDC4sIc7AdjgOliI4tE+p+uUEuhdSKE6T45oQAGCqH
        iOjCUC+Xo00iQ11XN1qHR1HW0op8ZxWsFivkTfNQ9N2HO3GJ3sIEt/IQYjvgstjqe4GMsLCTonbWA3WB
        aYRZzEhJzkFh0fiaAwROtzxqi6rmGQrAHeoU96Fz9MAYlwlbeLTQ9qLCwxAZFgqTxQZFzmL6y4kA3bMo
        c4jYNhMoGyE4eK142Qg81YrZWQ8uSQkVyE3LpPRPIOZf+6o7p1xlzUXq2+QMdQI1ZYGG2qXm0D1qc/cp
        1e9B3n0Nss4r9P1dcv4BVIcfQNJ5F/6xI5sehm4Gdmj5ejYDn12I2VkPLqr8Q4gs7UNkYrXA+GI1xqxr
        KhmCvHkekpZLkLZfISxA2sGOX4es64YAOUldec9t+v42tb8LUFtHBPITu/FWwKWz1SfHy8GdRMyeGFxs
        Yx/D2ncHxubbPxLgWoNcBlW1VxBLk+L+kGy4Rjto9HXCncZSt7RmuOb0wLVwGG4l43Avm8Q+mvp8ohc/
        4sI1LHbjrYDfYF29lq2A33EUsycGFxNpdtPwYwQ03kOlc/FFAjGjHATOhKzMdqgVOgT5eUMuCYRCKoE0
        KAgB/oHw9JVgH6k5o61FqP3VBxTbxU/9mNx2PqTlYiC9HtB8C7KswU3f4eHs4LbYSpNiU9MslDIVlNQN
        /AIkcPP0xj4Pb+zc6wHfgHyhH79M7b/MJ0VZ64vZFIOLbfoZjCQta+oWj8TEDC6Bs6Om+jKxfj4Cff3h
        6+FGA0swzQZqeHjJIFekQa1pEcTOyzA/g99ZFlvDVsDPAMRsisFFN/4NsusWXyQQM7YcrAnMhgR4ubnB
        dc8euO7dC0uwDkqVDioNtUXbMcH5rai8jcDXrn5BYjtg4twq97hIuh+jpoFfFth49xlcAjp1EmT+vlAG
        Uf0TZAEBxAVSKgcTgnUHoFZWQaUc2hYTrwaTmNj9t4OtfgbBRdd0j9rf5k9u+Micj5XU6jHoNE6oFJGQ
        BMoEAlQqVPRzHU1wOvgHKuDpbRFq+Kdmwct8RHYJG31UbjlcYn78hJeYkSXwmMlTG/d0TnGe0MLCpmnw
        KYNGLoFKrcWe/e7Ys28/9rpTZqhLf3wWv30e4NTd7it0Ytjah7IG8X8DgGxqHMKeMgAAAABJRU5ErkJg
        gg==
</value>
  </data>
  <data name="Globe" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29m
        dHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAANrSURBVDhPXZJbTBtUGICbmJCYqEsWlukWEmBhKBZX
        RrnfCkKbKURgjJtAuTjHRWAgZSsCpcUCwrpSEBwMBIIXYMhcKpdtsLlxKSzEiYSFTJxRo6LE+QAPI5F8
        Hkhchg9fzsM535f8f44E2EW5xSYTNAuWBWzzXuPMctn56eazpknZ/98/KT4t6NB23KB65DJtd4ZpmbvC
        Wdv7FI7WEzVURJL5IgX6a615lWN2uwJCtNOap2xnhvq583Ce5b/vc39tjfnVVaZ+f8jw4neYxjtJtSUR
        0J2KuvjSVFrB4E5kJ6D54GZb6SdCXl1g8a97zP72DTM/P+D2+iOsf2xwbvpHNG23SGusIPwLJc6WEGIz
        ult3AoWGcVlBe8vW+E+TzK3NM/RghNbFXrq+vUH/vRVqF1Y52b/ISdM02RVWXtMV4likICyuaksZ2+Iu
        eUvb19n36wAf/3mRCwsdWGa7MH5fje6WmcrRr8m8vIT6QxspugnSNVdJyBrAO8jM0cAaglSmZklyQfMv
        ams26StJGFa0mO4aqV4u48RQFmmWL4U8S3LVBInFo7z5jpXIhD6O+DXi5mnAO6R2SRKT+tFmYEUGfjN+
        ZC2nUDpXwKnrasLPZ5BVdxW1/iZJJWMk5FqJUw8SeqwdqbxSRPLxUdSsS8KjmzY9kwo5MOyI55QclU1J
        xGQEivYTqDU9pBSPkZg9xHF1L6rEWjxez+O5M4dxig/HP9SwKQlQnlvyCqtib5MLDmPOeFz3QdFynMjS
        MmJyG4gV4qt57yK9oMD5Uxn7TC48az3A4fww/MP0P0jEHPVHfI28rMxnn86N57uccS05hswQSUBeNvLT
        ybiOeOByW8r+CUfshx3Yf8mFkKJ0fEMMDRKv4Bo3wT8vyvS4B5zmhZQg9mqk2Bd54JATwsHcQOwHhdjn
        hH2voMMVH1Msb6QbtryCja47H0kETO7eeg5Jy8V2tbzirUUqeOmoFjd5Lnt0rjzz2UH2tB9CXh9DTnUj
        QRE1zY9/ogjYiVGu+CiMyIP0ePhXilOHX5hBLEpPsLIEv/i3SS02ou/uQhVXNyGcpx4H/sM3tO5URJR5
        QxVtJiq+ifi0FjJzOtGUD9DUeg1jw1ePhKx50tkV2EaUnQLD62uiE1vvZuT0rOcVfb6RmdOzqIq21G/f
        7X6P5F9YzV8PcHzvzgAAAABJRU5ErkJggg==
</value>
  </data>
  <data name="KEY06" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAO
        wgAADsIBFShKgAAAAFJJREFUOE+tjgEKABAQBO//n6YrW9eSDKYkuhniJ23s13ggzyiqYYlITqp4siZ0
        uR3a4QKO4BcdEsA/cwH/VhGJy0AdOlkIF1GgigIFVjwHBhEd/1Y4yA5tzEIAAAAASUVORK5CYII=
</value>
  </data>
  <data name="delete_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAACA0lE
        QVQ4T3WTzUsbURTFbxqNVgKmlARM/EiptEapmSSliBJEzKbYlTu7MV0Wuuiuf4tFcCFoF4LiRkEkGwnS
        akdEcSmKghZx/MBWa5LTdyYz6WTSHnjMQOZ377vnnohbSEm2kJTcbVxw9UJw3iM47RIcP5Pc/lPJWp/V
        SoFRdfRS5jGK2STwcQh43w+8U+9jMfwcDuGox4e9DtG32yRqYWVZsIG33cCn1zUwRp/gLhNEcSiAc82H
        zYgYG2FHEXbGeBz4kAYGHuIu5cWvTKgC/3jpx346it0OD27iHpw8F6wFRbfhLK9tdlZwKTeP0pWBi1EN
        xiu/CR+OaChcGrjZ0fG1RXCfEOgRwcoj5QkNs2dmZ8JUUQHHb7QKTN1fGFhPRE1zaexys+SEbtsz89rs
        TJji0wl/G9Sw266+T5XPol8g14m6KsN4bXa2i1D/gnnmmlSBy2RDldvOmW2xQD6tYau1usCXRlWAs/wP
        JshD/VbP1T4N38N/C0zXqwJMGEPCPXNV7pnZmTDF50xDGT7oFEx5lYmMJxPGkJh7VqtyzsxrszPhg4V5
        zFoFlpoFkw+saDOeZ731Zki4Z67KaRivzc6Ez2Ji/vbZYwWJUtkOqHjqTBhDwj3bsPtYsDEhrv9DPiQB
        xpMJM411gZyZ12bnGtgpxpMJY0i4Z66KbtOwyswVifwB5qsTVJRVplUAAAAASUVORK5CYII=
</value>
  </data>
  <data name="trash_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAACTklE
        QVQ4T4WTW0hUURSGl6JpWaNhRUUXyzLFJrRMsJe0hAR7CAqCHmqegm5SMElRERgFUYSBVEY5VkJZyYCR
        MCHoVCSh+eCQUpLXVNJkKiWZ8fK1tkHZONKBn5+z9/6/c9Za5wjwV5vENpYqziGrePuThM8JQusqwbNM
        qF8iXvcCcbpixDY1MzXsmNgojGZYmMhNhP074JiePXcGrhQxWlRGj72A2vVJlEeKYxpgXMO9SeE0xltw
        Lwrl/UrBm6xb6WGQHQv7NsDFk/jLa7kfbiIBgGGrDH6IE1p2Z+Lv9ujSK9UtlV2VzcTACvpOxeFaHcvt
        EBk0GaM/gAGt+ac9j770GJrjQk3NvFwovJgvVM4VKuYIzyxCVbRQPBkLALTFq90shb0JkLsUsqIhLQR/
        qtC3TiZLqluskHkzAJqWqxXe+G+4JHQGQF2mDNanJtCRk4EvZy3+tFkzhh2JQXpQVyR0luXj3mPFER0x
        eXCq7kYJT3RSrgNCeb6JBABeXzf2CMYKwXsY2reAJ5axtzrOaqG9Qj+oUqGhWHhoDwJwXzNW9C+gWQH1
        0wFlJ4IAaq6q+Y5ChxU+RUCP3n9T+c12GOO+FL537qS9Jpt7eWYtAFB9WW1kF3QnQ38WdKm3Whj3CEPv
        IvnasIYfXcf1aAslR4IAXJeMbYPxrTC8HTo3T+tB8wPhS00Kdw4FAVRdEMeb0tl0NUbhH9ElI1NCr6pN
        8DUJHx8Lzwt0KgeD/EzmqjwvNudZcT49LV4zKtNt0zBTs762V5/s1LDNnP2dQ34BZ1aGSv139vQAAAAA
        SUVORK5CYII=
</value>
  </data>
  <data name="folder-open_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAAB8klE
        QVQ4T6WSX2jNYRjHH7OS1WQpf3JBFDdH7YYLF3ZScqFmhd1SapqM0ohJafJvrC3EjqxjylhspoUJ+8k6
        iU372znjyDbG5l9nFxubwz7e5/3NHCwbLp56+/V+vs/zfN6fAP9Vo378m5J6n0w15dQVCQ9PCQ9OCoHj
        wv0C4V6+XB0Nii0NcNqdpeZ8GqL5MJAL/TnQm0WwcgG3D4v/1kHx3tgv3uu5kvxbgHYeAft2WpAPG6En
        HV6vpq1iNnfyJmJgqvYJlXvF/1OAjm3BSOYP8NUqeLEcni+B8CJomwetM6EpkYo9ysUE6M683wDda1yw
        02vAxS4YmmvAGRbkcRzUC1d2/xKgwr60r6ChOH5EYm2hFUjNUVEHVB+Q2BUozxEu7xIuZktE1Pa72jk8
        val+fPD1BAweGha5ZXitddC10ky3jL5AIp87zKRv0rmw3QRopydlk3kbWj8mzLNkIk4Cg+EUXtZ4OL9N
        /OIcc8eOfjwyJkxoPj3Vk/jU4iFQlETJVkmzAcFrnnHBKrSrKp7+R7MozY7rtRJ1he7GteOCaZpCR/kE
        gqUJFG92/wcbEA2nmosp5uJCaJnOUPM0BuqSrDDdWcfWzgq3lrivc2aTpNmAu3ky9KenurRD1LYK41yW
        cDZT8GVIRGEb8P3wb4V8Aymc0VswzoADAAAAAElFTkSuQmCC
</value>
  </data>
  <data name="applications_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAACgklE
        QVQ4T3WTfUtTYRjGz0fYR/A7KKKICCKCfyiiwhBfmP6xCDXGcGUQOM2aNt9mGUiKaTTFVTvMTDTpqJCK
        KLM5NntzRgNfYB0NBUvi6rkejo5evGEczuH5Pdd1X/c95bKqre23WSz3UV3tQWVlj834fHlZrQMp4ndx
        UMDa2tonBAKrKC/v9PNbaeldU0nJHVtx8e0Ueei8DFhvbfVBKMcEPEzlk5NTHBwcwmy+p5eVuYYFHLvu
        GEJRUYteWOhMXkJlwqxoNI6REU0+I5E41tc/Y24uBI8ngGDwI1ZW3ouW3CgouJVsS1xgonIk8hX7+4dY
        XIygu3sS7e0q+vpeQdPCUNVVzMxswO1WCccMNFm07fMtSdjpnMDy8gfp6NfZGX7+OBUXJzA+/hZ2+yDy
        828OG9hF2v6qql6dtqlMeHo6KNQCaGt7jtHRBZwcH2NpKYKurgDy8m4gN9eh5eTYnVSWqnt7uuyZtlmE
        DQ2lsXEU34+OsLm5jY4OFV924qI1FdnZNihMe3Y2iN1dXQbGnmmbygav1NcP4VDXEQ5vo6XFJ85Mimn1
        ISvrGhQuiZizJkYl02Zg7NnnWwaVCdPNt0QCU1OrcDieUFkXsD8zsz45Cc7Z5Xom02Zg7Jm2qUx4KxpD
        c/MEKio6qZwM8by4JPNv3slRMW0GthXdkbapTLjd9QJjT18jI6Mulp5+1WSgErbU1T1EKBRDb+8kmpoe
        y7QZGHumbbO5A4OPXmLMO88JIC3tStK+2G2TWM9gTU2PXBLOWYxK3whuwetdkGnTNpXF6AjrqanWP/8P
        AjRxPfnku1Dx9z9Q0dAwQFiTh0RR+R/4fyWUbIYyRNpO4/NfpSi/Aavk9SZMePbOAAAAAElFTkSuQmCC
</value>
  </data>
  <data name="add_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANjr9RwUqgAAACBjSFJNAABu
        JwAAc68AAPY3AACApQAAcCMAAN0CAAAwPgAAFrLOXXcKAAAACXBIWXMAAAsSAAALEgHS3X78AAACNklE
        QVQ4T42SXUgUURTHz1MQJQxL9jCkTII+mCxTD6WsxAVTtyJoo4SK2EEI1o+WTYmSpcUSTS3D3BaXoi+L
        PkjQBx+koAmfYl9GwYgtKoIIImgfAimC/p173aaZQvAP/5d7z+/cc8859J/GyaIs2Wz8Y1vdrag0GZQh
        p2paR+xtIzI/W5H+YWF06RhGvh1BdLEeFZOlkDEq1qcrfDBGhZb5OmR/HVfwntxWaDc1aNc0ND6vweDX
        Q+j/cgCRF9sgYxXj6jI51kvhwkP8ooQL3wvKdIkU3Pd5P3o/7UOzXQ3JLMMXyap6qLuwLPvEuyaIKYE/
        oiFy4dTHvUh+CKP8dgCSJRokO5b3/7n9zS6ISU+CfvLBPe+bEJkLQrIkLyW86TFnHOduX2WPEsQjT4Jz
        fJZi97BPETYOlKA7L1RiWju8Rr0s4dXK6DVwdI6beZ4TBEbWq7Lly6uVcdbAYdtcroqSpOasT2gw75gQ
        9wXEXYHEbKIYDogsn2XYYwLmgIkNyXXoWKiFZInOkB3N1as5d+Yb0DofQvjJFohbnh50EVqemTj4NKhe
        lnB4phKSJW6KVZEu9c05mquFuO5JECecfLUT8cWQgtuc7dCHS2RDi6vdRc7umRp3VN2vG6CleJGWeJHY
        1E4+uO5emayquEhSCV7LOBWap6vdOYcebIZ2WlPwjhtlf+EJhjlWMT518kEHOeUXAojMBtWcvWWHpyqh
        93HZHKNiV1Qb/yvGzYlxh/221Z1PRL8B19UC2rZEmyUAAAAASUVORK5CYII=
</value>
  </data>
  <data name="redo_24" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABGdBTUEAANbY1E9YMgAAABl0RVh0U29m
        dHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAM3SURBVEhLrdZrSFNhGAdwu1pGFBkIlRBZ0YcKy0t9
        KSo/SFFkSQVdtIzMy5w2J2gQaWZz5jJtbtraMuc0dZakeSu6WIYWlSaZSUEJFWGB0uXr0/M/nbPmPI1a
        vfBjL+c8z/855zg883KzxrHxbCKb9Bs4hxrU/vFCMRp92MwoTfFWpeVKrtJcp021Nd0H7HEM51Aj1qJH
        GoRPyag1gfkEbYxYGFdsPaO2NY2kVbWQO6hBLXrQy3Bn3rFFZaH8OZkJC5NwYuYBrVGlsjaMqG3XufnP
        oSdao1dzxryonKKYVGvjMO99mSPcN95QYVeVX6N/oTh/+Ym058xFGIDHMmvfycJTR8qu0v/EuYEYMC10
        c+T6ZIud3EmtaKD02jYB9nI1rjg7GAP8YvIMDUpTNclRXaonTXsvnX36ZhQcS7HUyfZIODsEAxYnGKxf
        FKWV5Ep5oZq0HX105tFrWRn2G2N6nEkDAhMNVpKDgPzOgTHyOl5QWmWjbI8zYcDStWGb4/VlJAcDtBzm
        LOd2NyWba2TrXUl3EBJXaCY5KZZa4Vl7yjEAQbEF52Wl17QKVy0nq7VL9jjgbh0Dctt76JDO+FuKEhtl
        1N2k400PBNjj2OECk3AB2Tcfj3Gu951jQHDpq8/flKZKOpin90gKf+ezWh46nLrzjPR9H4aQjQGBWW2d
        d4t63lKsroRicos8En/uIh27do8yW7rI+HKIjtbfakY2Bixetj48yTjw6Xth91v+45pof06BRxSGciEc
        WchENgb4sbDdJ/Jt5sGvxI+LjtpbKTo7/6+gB73IQBYyxWyvaWwJ27XzmMaOAijue09ZzR2kLK2gqEyt
        LJxDDWqlPmQgS8xE9s//pmwF27Nu70FTYc/gsNQgKX7+nnRd/QLsXc+jB73IELOQiexf7wO2nG2b7T8/
        I1qrbz7d2f/RNcgValCLHvSKGchCpuOVKQ2ZwQLYGobbTAoIWqXbmKCqjjOU33YwWm9tSlRXLQxereWa
        BLZD7EEvMkaFOy/c0lQ2m6EY79VwFsG2s0jxE7awDWwlW8DQg17hsbhbmIxfCFMYrgbfhLlsHvMXYT+H
        IXQ682bOvyrE5eX1AwFGUYzob/BCAAAAAElFTkSuQmCC
</value>
  </data>
  <data name="redo_16" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAANbY1E9YMgAAABl0RVh0U29m
        dHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAIBSURBVDhPldNPSJNxGAfw+YeMVpckoW4iXazIckNy
        h9ghD9461EERweaayXL+OQgy/5JuutofmNrYZsNXSGbKxAol/NPy31AQLQs9CCKdxIvR9fH5/nj38mqS
        +MIHnvf3PN8H3rGfRvWksDSWwS6xy+yKDDXOLjDMpDLMg3hwcJFlPiwxFVr8ktsWiS3Z3sm4tgajbmOZ
        +QHPXGXqhSKszTUYb1d6wlLD0Ef6n0p3SNIVPy6yDYwucC4TC7Ap2xoY/lUXidF5cO4mFlwvbX8dqAmP
        kFptZIwao1MC6pN94Ow9LMit7pMOrYH3lFQvjZMrsU3u1R0BdU0oqvSTOKvDgvvVvYOk1vFlhXqWtgTn
        /CbVD8aO9ZM4q8cCfZUvTGrNE9/IEf8htH5e5M+YPJWywPp2iMxvAgqLN0T28a/0anpNQN00NqO8gyP+
        XVmg65pbI1O3/x8WT1BIvtcOjFDbZELwre8pv8Hdtqnl2cbhT1TR5TnTC3+Euud/EjLIYkFO3qPi5/3b
        +387Z1bpmdNH5R2uU6GHGcwigywW4N9UYHhS2uLb2DsI7f4hZ3yd7LHpY3CGHmYwi4ycFZfnBjOwMpM3
        +MGV2PqNYTWcoYcZeRYZZMWNwkXKYreYkT1lZvZShhpn6GEGs8gotxFFOtOyayyb3WH5MtQ4Qw8zmOWM
        RnMEKibKU2PgBZoAAAAASUVORK5CYII=
</value>
  </data>
  <data name="rename1" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAL
        EQAACxEBf2RfkQAAAjxJREFUOE9tkV9IFFEUxiV68iWilwoJUfqDPeRDPWmLWe1MhTiW0dIfyNYKgq0t
        KFopqIlK2kxacufBantIK1rZFaKRTC1zaVrcSAo0dlhHWiXbirIMLfLrnksOzU4fXM7hzPl+c8+5OQD4
        CcZnUP90GnXqJI62T8B99xO2h95DaEpjbeNIaLYv+5jJnYFfLNhVoryGu20cBacH/wsxk+vxKRbsWtOY
        gJIEVjWkket5ZYOYSTD2gwW7is/H4HsJbH0ALJaHMadWs0DMxN8zwYJdRb5urL8/hfnn3mFeXRJz9/Uh
        d7dqQkzA2Y7PLNiVV9OK5Z52LNoRQl6VgiUVASyobqFPVsCJaIaKXLIsQ5IkfhzlAiqrd+Hewxi6E8N4
        9CKFUi+bJxvgDY9TkUsURUQiERiGAV3XcaH+EkodZciwPY9NAptPqtRmBexvGaUiFwE0TeP59G9gyBhF
        fkEhNxvfgC3Ho/TJCth5c4SKXARwuVzwHPFiT40by1YUoSF4g5uHvjDAsTC1WQGSkqIiFwEC14KIqp1Y
        t1GA7L9qmt+wXVccbqU2K2BTQKcil1MQ0dWn8Zn1D9+RX7gU4Sf93Jz4CFQeukVtVkDZ5bdU5DNvcIro
        6NXMmZvDKlYWr0Z/ZgbP2a6lg83UmgXwD3Lz15+AErqNRDJtubbPr6AtnkLPGFBV22QHlF8c4ObZp/rX
        TNemP5O5Mw1s23vFDlh44DGcZ55BONXF35meirZNC6OZ6dr0ZzKXOLx/Acj5A2xkENiLFtSYAAAAAElF
        TkSuQmCC
</value>
  </data>
  <data name="PORTRAIT" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAO
        wgAADsIBFShKgAAAAO9JREFUWEftklEOwyAMQ7n/qXqzbQ/FEkKhBEJ/pj7JGiTG9cdKx+egtvicgBzT
        MhaRQzn81tQF6sMsbQ7nmhzEnuXoc7jX9AD2JIeXw6x+YYLZc5Bzo1ssIgb+lTd4r+u6LWHWGPhX3uA9
        VgBvqwj4/qMAPnl1jrzFc6yA4CzNwJMugKf16d7PPdgfKdDDTLqDfaoAe8+j+Wgv2KULjGAnjWC3XYDd
        ijyYpwrMwCN5MN8qwHy0a5Fv5Ge2XSAKXqmH2XIBZt58hPzeO+7hApw9jfC8reTZ/hOegPy3wFvgLTAt
        8LRmBQqGp2Wf+lHKF3UoBjbHdCTUAAAAAElFTkSuQmCC
</value>
  </data>
  <data name="sync" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAO
        wgAADsIBFShKgAAAABp0RVh0QXV0aG9yAFVsZWFkIFN5c3RlbXMsIEluYy7JHT52AAAB10lEQVQ4T6WT
        z0sbQRzFF3LIjz8h/8fca9UK2ho1GpvagpKqiEiRVMR6aCUtUgWpVaGIV7VRCDaKmFboYStBi6OCpYfq
        LTGJB3fX7OaSrOO8GIcVcoj08GHevHnvy7KzKzHG/ouy5n2Q3r2pF7hcLlugu4dE1qJ0eGT0560PDS/w
        socgY+0IATq7AiS6sSlnMudmcGhYDHjNNbzo+qaMjLUjhLfV515ZjdBUOm3mcjkWej+uvxoMnnOUicmp
        PLyzVOoqzDPe1ja3GOB0Om3POl6QxeUwVTWNGUaOKarG8oVCkUJpVbmHM6zI+jueE3QlX7ufLH1dkRPJ
        M1M3DKZpWc6lhbt7XTcYskvLYRld6cv8Ak0kkmY2qzOVByoBWXTQlaZn5ujB4ZGZSmeKj1cJyKIzPTNL
        JU9TM/n0eVb+tRMvDrlQtBtUlVPSHKW0RwZZdNCVHA6HreFJIxn/OEn3fu/zN51m/05O2fGfv3eAhzNk
        kEUHXXGND6oeusdCH2js+7YZ391jff0DSpvvaZKj9Pb15+FtxX5cIYOsuMZbAWof1ZG3YyE5svbNbGrx
        ig8JGh7OkLF2hAB2u91WVV1D+FdIHzd6xABoeDhDxtop+4Pch7Jm5TDpGhrRoDGNhQVZAAAAAElFTkSu
        QmCC
</value>
  </data>
  <data name="rename" type="System.Drawing.Bitmap, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>
        iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAL
        EQAACxEBf2RfkQAAAj9JREFUOE9tkV9IU3EUxyV68iWilwpJMqTyJR/qJUuGyXYrpGslRvVgTY2CxQqM
        lKJahKmZpGw3KFsPuf4tpmBMsmZa6k1atDTNP2yz7mRiRVmGFvntd37UD+5uX/hxDuee7+f+zvklAeDH
        1TePi51zqPDP4FjLNKx3PqHAHYfFqWFz3bj7X1/iEcnt0C8WjMpS+mF9MIm000P/hYjket8sC0ZtqAtC
        GQXW1WpItr02QETi6v7BglGZF7pR/grY2Qosd0SwoFjVQURS0zHNglEZ5QFsuT+Lxec/YFHFKBYefI7k
        /X4BEYBzbZ9ZMCrlgAerbS1YVuhGSr6CFXn1WLK7iT7pASeap6hoUM/bGHoHNHSF3iMQjODRizA22dk8
        iQC7d5KKXA6HA7Isi2MtKcWbkQim2J4nZoBtJ/3UpgeUNMWoyCVJEnw+H6LRKAZHxuCorMbGbBM3R78B
        28uaqU0P2HtjnIpcBFBVFXO/ga8/gf5wDKkrV3Hzuy8McNxLbXqArISpyEWAgsI9OGyzY1+RFelrMlDl
        bOTmAbbrvKMeatMDttaPUZHLbJFQ2+CC92E7TLkWnKm+IszBj8COIzepTQ8wXRqmIr92rllCW5fKZx6M
        f0dqWjruBl5ycy/btXzoGrUmAGqGxMw5DND6VBUzX73nx9rM9eiJz6NjAsgvdhoBOZUhbqanami8BXVY
        0127rEqBRw2jXQN2FV02ApaWPob57DNYTj3h70xPRdumhdHMdG36M5mzsu1/AUj6A3XkEJwShbgxAAAA
        AElFTkSuQmCC
</value>
  </data>
</root>